function scr_talk_amanda(){
		switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_amanda],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_amanda,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,1519,1790,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oi Amanda!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",0],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Oi Bunbun!! Como está? Tudo bem?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, apenas estou vendo como todos estão"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["HaaHaa! Como sempre, se te serve de algo, estou bem!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Perfeito!! O que está fazendo?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Hum... Promete não contar para ninguém?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Prometo..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ok! Confio em você! Vem cá!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",0],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",90],
					[scr_cutscene_wait,.5],
					[scr_cutscene_move_character,o_amanda,1482,1776,false,.5,true,true],
					[scr_cutscene_move_character,o_bunbun,1519,1776,false,.5,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ali está ele..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Lerroy?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sim..."]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
					[scr_cutscene_move_character,o_camera,1478,1669,false,1,false,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Ele não parece vivo?"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Vivo?"],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Sim! Vivo!"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Eu ouvi dizer que ele sai por ai de noite"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Saltitanto por ai, buscando crianças que ainda ficam acordadas de noite!"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Isso é mentira!"],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["O Lerroy é bom! Ele sai saltitando por aí, de noite, cuidando da área!"],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Você tem certeza disso?"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Eu confio no Lerroy!"],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Humm..."],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Se você confia no Lerroy, eu confio no Lerroy!"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["E se você confia no Lerroy, eu também confio no Lerroy!"],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["Vamos perguntar se o Lerroy é do bem?!"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Ah!! Claro!!"],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["No 3, ok?!"],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Ok!!"],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_amanda,["3!..."],-1,global.cw/3,global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["2!..."],-1,(global.cw/2)+(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["1!!!"],-1,(global.cw/2),global.ch/3,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["LERROY!! CONFIAMOS EM TI!!"],-1,(global.cw/2),global.ch/3,150,make_color_rgb(36,34,52),true,false,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["VOCÊ É DO BEM?!"],-1,(global.cw/2),global.ch/3,150,make_color_rgb(36,34,52),true,false,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["..............."],-1,(global.cw/2),global.ch/3,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_camera,1519,1776,false,1,false,false],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["HeeHee!!..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee!! Ah! Opsie~"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",0],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ahem!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Me pareceu bem convincente, da parte de Lerroy"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Honestamente, para mim também!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Devo dizer que Lerroy foi até mesmo cordial!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["HeeHee! tenho que confimar!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["O que esperar da realeza, não?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HaaHaa! Sim sim! Lerroy, o principe dos espantalhos!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["O que esperar da realeza, não?"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",90],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Vida longa ao principe!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Deus salve ele!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHeeHee!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["HaaHaaHaa!!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",0],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Tá com tempo, né, BunBun?!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olha quem fala!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sei sei"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom, vejo que você está bem! Vou ver como estão os outros, ok?!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ok! Se cuida BunBun! Nos falamos mais tarde!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro!!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",90],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_wait,.5],
					[scr_cutscene_move_character,o_bunbun,1519,1787,false,.5,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_amanda],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
					[scr_cutscene_variable,variable.normal,o_amanda,"ppl_to_look_at",o_bunbun],
					[scr_cutscene_variable,variable.normal,o_amanda,"ppl_looking_to",true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["BunBun! Seu desocupado!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Amanda! Sua desocupada!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHeeHee!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["HaaHaaHaa!!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_amanda,"ppl_looking_to",false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_variable,variable.normal,o_amanda,"direction",90],
					[scr_cutscene_wait,.5],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
			break;
		}
}