function scr_talk_mommy_allegra(){
	switch global.day{
		case 0:
			if(global.event[0][3]==progress.non_complete){
				quest_array=[
					[0,quest_type.have_item,item.uncle_spices],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
					[scr_cutscene_move_character,o_bunbun,681,354,false,1,true,true],
					[scr_cutscene_move_character,o_bunbun,681,327,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
					[scr_cutscene_move_character,o_todd,718,338,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
					[scr_cutscene_wait,1],
					[scr_cutscene_animation_sprite,o_mommy_allegra,[s_mommy_alegra_casual_spices_getting_down],[s_mommy_alegra_casual_idletalk_1_up],false,true,[.2,.2]],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",90],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"ppl_act_state",ppl_act.npc],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",225],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Oh! Vocês dois, conseguiram os temperos?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ainda não, o BunBun fica andando por ai"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não, não estou não!"]],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun, onde estão seus modos?"]],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_big_b_bedroom_gasp_intro],[s_bunbun_casual_big_b_bedroom_gasp_idle],false,true,[.35,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Todd...."]],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",225],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Desculpe, BunBun..."]],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_big_b_bedroom_gasp_outro],[s_bunbun_casual_idle_1_downright],false,true,[.35,.2]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["To começando a achar que você me odeia"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu não te odeio, BunBun"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tudo bem, Todd, meu coração já está partido"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["HaaHaa! Ai, meninos, por favor!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Bom, vão lá pedir os temperos para o Tio Big B, tudo bem?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Pode deixar!!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",90],
					[scr_cutscene_wait,.5],
					[scr_cutscene_animation_sprite,o_mommy_allegra,[s_mommy_alegra_casual_spices_getting_up],[s_mommy_alegra_casual_spices_idletalk_1],false,true,[.2,.2]],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
					[scr_cutscene_move_character,o_bunbun,681,354,false,1,true,true],
					[scr_cutscene_move_character,o_bunbun,681,327,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
					[scr_cutscene_move_character,o_todd,718,338,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
					[scr_cutscene_wait,1],
					[scr_cutscene_animation_sprite,o_mommy_allegra,[s_mommy_alegra_casual_spices_getting_down],[s_mommy_alegra_casual_idletalk_1_up],false,true,[.2,.2]],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",90],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"ppl_act_state",ppl_act.npc],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",225],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Oh! Vocês dois, conseguiram os temperos?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim, conseguimos! Aqui está!"]],
					[scr_cutscene_item,o_bunbun,item.uncle_spices,[-1,-1],false,true],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Obrigada, meninos"]],
					[scr_cutscene_item,o_bunbun,item.mother_list,[-1,-1],false,true],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Bom, acho que não preciso de mais nada..."]],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",270],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["E Todd, iremos ter espaguete ao molho branco, com soufflé de cenoura e suco de abacaxi com horteã"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
					[scr_cutscene_wait,.5],
					[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_spices_intro],[s_todd_casual_spices_idle],false,true,[.35,.2]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Deus, eu te pedi um almoço e me destes um banquete!"],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Ah Todd, fico feliz que goste tanto assim da minha comida!"]],
					[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_spices_outro],[s_todd_casual_idle_1_down],false,true,[.35,.2]],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["É uma das melhores!! Isso sim!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Muito obrigada, querido!!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_mommy_allegra,["Bom, meninos, vão lá brincar, de novo, muito obrigado pela ajuda!!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"direction",90],
					[scr_cutscene_wait,.5],
					[scr_cutscene_animation_sprite,o_mommy_allegra,[s_mommy_alegra_casual_spices_getting_up],[s_mommy_alegra_casual_spices_idletalk_1],false,true,[.2,.2]],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
					[scr_cutscene_variable,variable.normal,o_mommy_allegra,"ppl_talked",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false]
				];
			}
			break;
	}
}