function scr_talk_nina(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_nina],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_nina,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,842,1762,false,1,true,true],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_idle_1_3],false,true,[.2,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_nina,"sprite_index",s_nina_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Olá Nina!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Vejo que está colhendo flores de novo, não?"],-1,[-1,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Fuu-Fuu~ Olá BunBun"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Sim, estou de novo aqui com as flores"],-1,[-1,[s_nina_casual_playground_idle_1_1],[s_nina_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["O que eu posso fazer? Flores são tão românticas!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["HeeHee, realmente, sempre tão românticas!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["E você, BunBun, como está?"],-1,[-1,[s_nina_casual_playground_idle_1_3],[s_nina_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah, sim, bem, estou bem!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Estou apenas falando com as pessoas aqui da casa, para certificar se estão todos bem!!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Você é sempre tão atencioso! Sempre se preocupa com todos!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Espero que sobre um pouco desse cuidado para você mesmo"],-1,[-1,[s_nina_casual_playground_idle_1_1],[s_nina_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Uh? Como assim?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Sim, você é uma pessoa que cuida tanto das outras pessoas, espero que você se cuide também!"],-1,[-1,[s_nina_casual_playground_idle_1_3],[s_nina_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah! HeeHee! Sim sim, eu me cuido sim!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Menos mal, então!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["BunBun, você sempre preocupa com todos, mas tem alguém com quem você se preocupa mais?"],-1,[-1,[s_nina_casual_playground_idle_1_3],[s_nina_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, nunca parei para pensar nisso, na realidade"],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Talvez..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["O Todd!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["O Todd é uma das pessoas que possivelmente eu me preocuparia mais!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Ah! Que bonito! Isso é tão romântico!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_nina,"sprite_index",s_nina_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["E você? Tem alguém com quem você se preocupa mais?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Hum..."],-1,[-1,[s_nina_casual_playground_idle_1_1],[s_nina_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Seguramente a minha dupla Jill!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["E a Amanda, ela é tão legal e me ajudou em tantas coisas"],-1,[-1,[s_nina_casual_playground_idle_1_1],[s_nina_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Então seria injusto não incluir ela"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah que legal!!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Sim sim!!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["A Jill é sempre tão independente e sempre me ajudou com alguns problemas..."],-1,[-1,[s_nina_casual_playground_idle_1_1],[s_nina_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Por isso eu gosto dela! Ela é incrível!!"],-1,[-1,[s_nina_casual_playground_idle_1_2],[s_nina_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Enquanto a Amanda, além de ter me ajudado também, ela é tão bonita!!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Ela tem um cabelo tão bonito, ele deve ser bastante amada por ser bonita"],-1,[-1,[s_nina_casual_playground_idle_1_1],[s_nina_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_nina,"sprite_index",s_nina_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["E quem disse que você não é bonita?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Ah, BunBun, eu sei que não sou tão bonita como a Wendy ou Amanda"],-1,[-1,[s_nina_casual_playground_idle_1_1],[s_nina_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_nina,"sprite_index",s_nina_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Não! Para mim você é mais!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Para mim você tem a beleza da Wendy e a personalidade da Amanda!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Ah BunBun! Para!"],-1,[-1,[s_nina_casual_playground_idle_1_4],[s_nina_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Não não! Você é uma pessoa romantica que merece o seu romance!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Ora, BunBun! Assim eu fico corada!"],-1,[-1,[s_nina_casual_playground_idle_1_2],[s_nina_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas é exatamente o que eu penso!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Bom, BunBun, obrigada pelo carinho!"],-1,[-1,[s_nina_casual_playground_idle_1_3],[s_nina_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["De nada, Nina fofa!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, vou ver como os outros estão, ok?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_nina,["Claro, BunBun! Cuide-se, por favor"],-1,[-1,[s_nina_casual_playground_idle_1_3],[s_nina_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você também, Nina!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_nina,"sprite_index",s_nina_casual_playground_idle_1_0],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downright],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				]
				complete_cutscene=[
					[scr_cutscene_variable,variable.normal,o_nina,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,842,1762,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Uma outra coisa, a Grettel gosta de flores também!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Caso você queira falar com ela também"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_nina,"sprite_index",s_nina_casual_playground_idle_1_0],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downright],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah! Sério?! Obrigada por me avisar, BunBun!"],-1,[-1,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_nina,"sprite_index",s_nina_casual_playground_idle_1_0],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downright],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
			break;
	}
}