switch global.day{
	case 0:
		if(global.event[0][2]==progress.non_complete){
			#region
			if(o_hide_n_seek.children_playing[5][1]){
				non_avaliable_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
					[scr_cutscene_wait,1],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
					[scr_cutscene_room_goto,rm_bathroom_2,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"x",499],
					[scr_cutscene_variable,variable.normal,o_bunbun,"y",385],
					[scr_cutscene_refresh_party_member,true],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
					[scr_cutscene_variable,variable.normal,o_camera,"x",499],
					[scr_cutscene_variable,variable.normal,o_camera,"y",403],
					//[setting the camera x]
					//[setting the camera y]
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,499,400],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,499,403,false,1,true,true],
					[scr_cutscene_refresh_party_member,false],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,499,400],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false]
				];
			}else{
				non_avaliable_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
					[scr_cutscene_wait,1],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
					[scr_cutscene_room_goto,rm_bathroom_2,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"x",499],
					[scr_cutscene_variable,variable.normal,o_bunbun,"y",385],
					[scr_cutscene_instance_create,741,411,"Instances_People_2",o_lorie],
					//[scr_cutscene_instance_create,708,429,"Instances_People_2",o_cutscene_trigger_3],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",5.875,708,429],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",0.875,708,429],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_avaliable_cutscene",
					//	[
					//		[scr_cutscene_bars,true,true],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_move_character,o_bunbun,720,451,false,1,true,false],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
					//		[scr_cutscene_move_character,o_laszlo,745,464,false,1,true,false],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,731,435],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,"Te achamos!!"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,"De fato vocês me acharam..."],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,"Foi um bom esconderijo"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,"Não, não foi"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,"Ah! Qual é! Não seja assim!"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,"Apenas gosto daqui"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,"É silencioso... Bom, irei para o hall"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,"Oh... Tudo bem..."],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_lorie,"ppl_talked",true],
					//		[scr_cutscene_instance_destroy,o_lorie],
					//		[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger_3],
					//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,"Lorie sempre foi assim?"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,"Sim... Ela sempre foi meio apática..."],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,"Honestamente, acho que ela se daria bem com a Grettel..."],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,"Você acha?"],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,"Sim... Eu acho..."],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,"Oh! Ok!!"],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_bars,true,false],
					//	]
					//,708,429],
					[scr_cutscene_refresh_party_member,true],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
					[scr_cutscene_variable,variable.normal,o_camera,"x",499],
					[scr_cutscene_variable,variable.normal,o_camera,"y",403],
					//[setting the camera x]
					//[setting the camera y]
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,499,400],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,499,403,false,1,true,true],
					[scr_cutscene_refresh_party_member,false],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,499,400],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false]
				];
			}
			#endregion
		}else if(global.event[0][7]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.talk_to,o_todd],
			]
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_bathroom_2,false,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",499],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",385],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",499],
				[scr_cutscene_variable,variable.normal,o_camera,"y",403],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,499,400],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,499,403,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,499,400],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,499,471,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,699,471,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",false],
				[scr_cutscene_move_character,o_bunbun,722,471,false,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom, acho que estamos sós..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que você queria me contar?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Bom..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["É algo meio..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Nem sei como dizer... Mas bem..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Você ajudou a Hellen com uma carta, né?!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Sim, eu e o Todd"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Foi mais o todd do que eu na realidade..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Oh! Entendo... Mas eu prefiro a sua ajuda... Eu confio em você"]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ainda mais com a ajuda que você me deu com o meu diário"]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh!... Claro claro!... Mas do que você precisa? Para quem você quer escrever uma carta?"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["É para o James..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu quero escrever uma carta para o James"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Para o James?..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sim..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["O James... Ele anda mal ultimamente..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu sinto que ele anda bem..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Distante..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ele parece triste o tempo todo..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["E eu queria animar ele, um pouco, com uma carta"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Afinal a carta que você e o Todd fizeram junto da Hellen deu certo, e animou o Fritz"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Quem sabe pode ajudar o James também!..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu só..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu só quero ver ele feliz..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu só quero sentir que ele está do meu lado..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... O James está tão mal assim?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sim..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Tem vezes que ele só parece não estar ali, ele fica apenas observando o nada, fixamente..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Em momento assim, eu toco o ombro dele de level..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Na ultima vez, ele levou um pequeno susto, mas não falou nada, apenas me olhando de forma perdida..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu pedi desculpas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ele apenas continuou me olhando, até sorrir..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Depois disso ficamos apenas em silêncio..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... Se for para ajudar o James a se sentir melhor..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu ajudo!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah?! Sério?!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim! Sem problemas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah!! Obrigado mesmo BunBun!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Quando que você pretende entregar a carta para ele? Na formatura?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sim sim, apesar de ser uma despedida, quero que ele tenha algo para se lembrar de mim!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!! Que belezinha!! irei ajudar vocês amanhã depois do café, no parque, ok?!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Muito obrigado, BunBun, de verdade!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, eu apenas gosto de ajudar as pessoas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sei disso! HeeHee.... Bom... Queria pedir desculpas também pela situação com a Hierarquia Rosa..."]],
				[scr_cutscene_condition,question.have_item,item.love_letter,
					[
						//Tem a carta no iventário
						[
						
						],
						//Não tem a carta no iventário
						[
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Por você ter dado sua carta em troca do meu diário..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu sinto muito de verdade..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nah nah, não se preocupe com isso!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Me preocupe sim!... Além deles terem roubado algo completamente intimo, você não vai poder entregar seus sentimentos para o destinatário..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Mas... Eu posso escrever outra"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Não é a mesma coisa, BunBun!"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se você diz..."]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["É que não vai ter a mesma emoção!... E outra"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Qualquer um seria extremamente sortudo de receber uma carta dessas sua!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!... V-Você acha?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sim, na realidade sim, pelo menos seria um sentimento garantido!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Oh!... Agora... Que estamos aqui..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Para quem você escreveu a carta?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh! Eu?!... Bem..."]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Aquela carta..."]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bem... Eu escrevi aquela carta para..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que é aquilo?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah, BunBun! Não seja tímido!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não não..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Tio Antony está do lado de fora..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["O que?... A essa Hora?"]],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",true],
							[scr_cutscene_move_character,o_bunbun,722,491,false,1,true,true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim... O que ele está fazendo?"]],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",false],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah! Quero ver também!"]],
							[scr_cutscene_move_character,o_linus,693,491,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",270],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
							[scr_cutscene_room_goto,rm_house_ext_back,true,false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"x",1002],
							[scr_cutscene_variable,variable.normal,o_bunbun,"y",1316],
							[scr_cutscene_variable,variable.normal,o_camera,"x",1002],
							[scr_cutscene_variable,variable.normal,o_camera,"y",1316],
							[scr_cutscene_instance_create,1002,1316,"Instances_People_1",o_linus],
							//[scr_cutscene_instance_create,1002,1316,"Instances_People_1",o_linus],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_remove_party_member,true],
							[scr_cutscene_instance_layer,o_bunbun,"Instances_People_1"],
							[scr_cutscene_instance_layer,o_linus,"Instances_People_1"],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_act_state",ppl_act.custom],
							[scr_cutscene_variable,variable.normal,o_linus,"sprit_index",s_nothing],
							[scr_cutscene_instance_create,936,1780,"Instances_People_1",o_uncle_antony],
							[scr_cutscene_instance_create,982,2046,"Instances_People_1",o_soldier_sobakov],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_camera,959,1764,false,1,false,false],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Tá atrasado..."]],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"ppl_to_look_at",o_soldier_sobakov],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"ppl_looking_to",true],
							[scr_cutscene_move_character,o_soldier_sobakov,982,1780,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_soldier_sobakov,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Por que demorou tanto?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Desculpe... Desculpe..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Meus pais e Owen demoraram para pegar no sono..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Hum..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Desculpe..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Trouxe o que eu pedi?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Ah! Sim sim! Estão aqui!"]],
							[scr_cutscene_move_character,o_soldier_sobakov,-16,0,true,1,true,false],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_soldier_sobakov,16,0,true,1,true,false],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Aqui os jornais da cidade que vocé pediu"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["E também te rouxe esse agrado para ti!..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["...."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Oh..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Aqueles chocolates.... Nem sabia que aquela fábrica ainda existia"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Me lembro de você dizer que gostava deles, então decidi passar para comprar alguns!"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Nunca mais tente fazer algo arriscado assim..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Ah... Desculpe, e-eu só-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Tanto faz, eu te perdoo"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Apenas seja mais pontual mais próxima"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Pode deixar..."]],
							[scr_cutscene_variable,variable.normal,o_soldier_sobakov,"direction",225],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["É que tinha algumas roupas ainda para costurar e as remessas ainda não tinham chegado e-"]],
							[scr_cutscene_variable,variable.normal,o_soldier_sobakov,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Olha pra mim"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Ah... Descul-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["E para de pedir desculpas..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Desc-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["...."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Força do hábito..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["...."]],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"ppl_looking_to",false],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",45],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",90],
							[scr_cutscene_wait,2],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",45],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",0],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["As crianças estão jantando agora... Se você quiser, podemor ir para o lago..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Eles não vão dar falta de você?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Ele vão encontrar outro maluco para ficar no meu lugar se algo acontecer"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Por favor, você não é maluco!..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Sim, você quem é, por estar aqui junto de mim..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_soldier_sobakov,"direction",225],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_soldier_sobakov,"direction",270],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Não me arrependo nem um pouco......"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Hee-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["To sabendo"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",45],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",90],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Mas por mim, esse lugar poderia ir para os ares"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Seria muito mais fácil assim"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Hee-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Ai... Posso te fazer uma pergunta?"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",45],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_uncle_antony,"direction",0],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_soldier_sobakov,"direction",225],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_soldier_sobakov,"direction",180],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Por que tu tá usando essa roupa ainda?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Oh! Eu gosto dela!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Gosta, é?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["E por que?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["Alguém especial quem o fez"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["To sabendo... Vem, vamos logo para a porcaria desse lago"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["HeeHee! Foi você quem quem recomendou o lago!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_antony,["Sim, e eu gosto tanto da porcaria desse lago que vou chamar ele de porcaria"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_soldier_sobakov,["HeeHee! Vamos!"]],
							[scr_cutscene_move_character,o_camera,1002,1316,false,1,false,false],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
							[scr_cutscene_room_goto,rm_bathroom_2,true,false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"x",722],
							[scr_cutscene_variable,variable.normal,o_bunbun,"y",491],
							[scr_cutscene_variable,variable.normal,o_camera,"x",722],
							[scr_cutscene_variable,variable.normal,o_camera,"y",491],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_variable,variable.normal,o_linus,"x",693],
							[scr_cutscene_variable,variable.normal,o_linus,"y",491],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_act_state",ppl_act.flow],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",270],
							[scr_cutscene_instance_layer,o_bunbun,"Instances_People_2"],
							[scr_cutscene_instance_layer,o_linus,"Instances_People_2"],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Isso é estranho..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim... O que será que os dois foram fazer?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Não sei..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Fala, Linus"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["É um pouco dificil de se explicar... Mas..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["você sente que tem algo de errado nessa casa?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tipo em quesito de infraestrutura?..."]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Na realidade sim... Ouço uns sons estranhos da tubulação"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas isso deve ser por que a casa já deve ser antiga também"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Não digo disso..."]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Digo de... Não sei...."]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Mas..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",45],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",90],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_linus],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
							[scr_cutscene_move_character,o_linus,693,471,false,1,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sinto que tem algo de errado aqui..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Algo..."]],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_focused",true],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_focused",true],
							[scr_cutscene_variable,variable.normal,o_graphic,"graphic_amount_alp_focus",.0025],
							[scr_cutscene_variable,variable.normal,o_graphic,"graphic_focus_mode",true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Errado..."]],
							//
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu não sei explicar também... Apenas parece extremamente... Específico"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",45],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu não sei, mas ultimamente, eu venho tendo alguns sonhos muitos estranhos..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sonhos em que tinha uma árvore, com 8 crianças perto dessa árvore"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Elas levantaram as mãos, apontando para mim, até eu olhar para trás e notar que elas apontavam para a Esperança"]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu não sei muito bem o que isso significa, mas..."]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Elas todas apontavam para essa Esperança..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",270],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Tem algo errado com essa casa... Eu sinto..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",270],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Promete não contar para ninguém essa conversa, por favor..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... S-Sim..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Promete mesmo?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["S-Sim... Prometo..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu sinto... Algo..."]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun... Eu nunca entendi o por que de não deixarem a gente ir no terceiro andar e nem no porão..."]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Quer dizer... No porão seria mais por questões de segurança..."]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Mas enquanto ao terceiro andar?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["No terceiro andar são apenas os quartos dos Tios e da Mamãe"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu... Quero acreditar nisso..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Mas... E no porão?..."]],
							[scr_cutscene_audio_play,audio_type.sfx,sfx_007,false,1,0],
							[scr_cutscene_variable,variable.normal,o_graphic,"graphic_amount_alp_focus",1],
							[scr_cutscene_variable,variable.normal,o_graphic,"graphic_focus_mode",false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",135],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
							[scr_cutscene_wait,4],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["..............."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["..............."]],
							[scr_cutscene_wait,2],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_move_character,o_camera,499,385,false,.5,false,false],
							[scr_cutscene_instance_create,499,385,"Instances_People_2",o_todd],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.npc],
							[scr_cutscene_variable,variable.normal,o_todd,"x",499],
							[scr_cutscene_variable,variable.normal,o_todd,"y",385],
							[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_todd],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,499,400],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_todd,499,403,false,1,true,true],
							[scr_cutscene_refresh_party_member,false],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_todd,499,471,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",180],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ufa! Achei vocês!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Estava buscando por toda a casa e não achava em lugar algum!"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_bunbun],
							[scr_cutscene_move_character,o_camera,722,471,false,1,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Que susto que você me deu, Todd!..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que? Por que? Aconteceu algo?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Não não, na realidade apenas estava conversando com o BunBun! Coisa besta!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh... Foi mal, irei esperar lá fora"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Não, tá tudo bem, já terminei de falar o que tinha que falar para o BunBun"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh... Ok..."]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",315],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, obrigado pela ajuda!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Te vejo amanhã, então!!"]],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Irei descer para comer, ok?!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok! A comida está muito boa hoje!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah! Perfeito!! Obrigado, Todd!!"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_linus],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_linus],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
							[scr_cutscene_remove_party_member,o_linus],
							[scr_cutscene_move_character,o_linus,499,471,false,1,true,true],
							[scr_cutscene_move_character,o_linus,499,385,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
							[scr_cutscene_instance_destroy,o_linus],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
							[scr_cutscene_move_character,o_bunbun,722,471,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_move_character,o_bunbun,528,471,false,1,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá tudo bem, Todd?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu quem te pergunto"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Está tudo bem com o Linus? Ele parecia um pouco tenso..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, sim sim, ele só estava desabafando algumas coisas"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Foi mais pelo susto de ter alguém batido na porta que qualquer outra coisa"]],
							[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh... Mais tarde vou pedir desculpas de novo então..."]],
							[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Não se preocupe, vamos logo descer para jantar"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tudo bem"]],
							[scr_cutscene_move_character,o_bunbun,499,471,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
							[scr_cutscene_move_character,o_bunbun,499,403,false,1,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_wait,.1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você vem?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim... Eles... Já estão servindo a sobremesa"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Demoramos então..."]],
							[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim... É pudim de leite com morango... O seu favorito"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Pode ficar, tá tudo bem!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não... Os dois são seus..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah?... N-Não precisa disso, Todd!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim... Precisa..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["A-Até por que não quero que durma de estômago vazio..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E nem sou tão fã de doces..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh!... Obrigado, Todd!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom, vamos?"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_todd,499,441,false,1,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd?... Você está bem?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Você...."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Você é a melhor dupla que eu podia pedir"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Está tudo bem? Eu fiz algo?..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Nah... Apenas estou feliz por ser seu amigo"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Obrigado, Todd, você é o melhor amigo que eu poderia ter!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["HeeHee... Bom, vamos lá comer então"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tudo pelo pudim!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["HeeHee! Tudo pelo pudim!"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_new_party_member,o_todd],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,464,385],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_talked",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
							[scr_cutscene_room_goto,rm_bathroom_1,false,false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"x",737],
							[scr_cutscene_variable,variable.normal,o_bunbun,"y",385],
							[scr_cutscene_refresh_party_member,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"x",737],
							[scr_cutscene_variable,variable.normal,o_camera,"y",403],
							//[setting the camera x]
							//[setting the camera y]
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,499,400],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_bunbun,737,403,false,1,true,true],
							[scr_cutscene_refresh_party_member,false],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,499,400],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_graphic,"graphic_amount_alp_focus",.05],
							[scr_cutscene_bars,true,false]
						]
					]
				],
			];
			#endregion
		}
		break;
}