function scr_talk_uncle_big_b(){
	switch global.day{
		case 0:
			if(global.event[0][1]==progress.non_complete){
			#region
				quest_array=[
					[0,quest_type.talk_to,o_uncle_bruce],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,1076,1682,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_uncle_bruce],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá Tio Big B!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Ah, olá pequeno, como vai?"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_2],[s_uncle_bruce_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vou bem e o senhor?!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Estou bem também, fazendo a sua checagem de sempre?"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_2],[s_uncle_bruce_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh-hum!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["HeeHee, como sempre, não?"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_4],[s_uncle_bruce_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["O que achou do café? Está cheio?"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_3],[s_uncle_bruce_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, eu fico cheio rápido"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Bom, isso por que você você é pequeno..."],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_1],[s_uncle_bruce_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Mas você tem que comer mais para poder crescer mais, ok?"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_2],[s_uncle_bruce_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ok ok... Mas quando o senhor vai cozinhar?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Como assim?"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_2],[s_uncle_bruce_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, eu quero saber quando o senhor vai cozinhar por que eu gosto da sua comida!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Ah!... Isso é sério?"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_2],[s_uncle_bruce_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Ah... HeeHee, eu não imaginava que você gostava tanto assim da minha comida"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_4],[s_uncle_bruce_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Bom, o almoço vai ser a Mamãe quem vai fazer, posso falar com ela para deixar a janta pela minha conta"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_3],[s_uncle_bruce_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh!! Sério?!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Se você quiser, é claro"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_3],[s_uncle_bruce_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro que eu quero!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Pra mim o senhor é o que faz as melhores comidas!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Ah! Obrigado mesmo, pequeno!"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_3],[s_uncle_bruce_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nada tio!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_4],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downleft],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_uncle_bruce],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mal posso esperar para a janta!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Não se preocupe, irei fazer algo bom para vocês"],-1,[-1,[s_uncle_bruce_casual_playground_idle_1_3],[s_uncle_bruce_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Yay!!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_4],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
					[scr_cutscene_wait,.5],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			#endregion
			}else if(global.event[0][3]==progress.non_complete){
				quest_array=[
					[0,quest_type.have_item,item.irrigator],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_3_1],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_4_1],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_5_1],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_6_1],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_7_1],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_8_1],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_9_1],
					[-1,quest_type.talk_to,o_big_b_bedroom_detail_10_1],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"spd",0],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_to_look_at",o_bunbun],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_uncle_bruce],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Sim?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Onde que está o regador mesmo?..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Está ali na estante"]],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_to_look_at",o_big_b_bedroom_detail_2_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_big_b_bedroom_detail_2_1],
					[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_big_b_bedroom_detail_2_1],
					[scr_cutscene_wait,2],
					[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_bunbun],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah...."]],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_to_look_at",o_bunbun],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_uncle_bruce],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu não tinha reparado, desculpe"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Sem problemas, pequeno"]],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"spd",1],
				];
				var i=1; repeat array_length(quest_array)-1{
					non_complete_cutscene[i]=[
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"spd",0],
						[scr_cutscene_bars,true,true],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_to_look_at",o_bunbun],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",true],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_uncle_bruce],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Sim?"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Acho que eu já acabei"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Hum..."]],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",false],
						[scr_cutscene_wait,.5],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"direction",270],
						[scr_cutscene_wait,.5],
						[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_playground_getting_up_1],[s_uncle_bruce_casual_playground_idle_1_4],false,true,[.35,.2]],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_3],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_4],
						[scr_cutscene_wait,.1],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_7],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Falta um pouco ainda, meninos, algumas plantas e vocês já estarão finalizados"],-1,[[-1],[s_uncle_bruce_casual_playground_idle_1_4],[s_uncle_bruce_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
						//[scr_cutscene_wait,1],
						[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_playground_getting_down_1],[s_uncle_bruce_casual_idle_1_down],false,true,[.35,.2]],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"direction",270],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_act_state",ppl_act.npc],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",true],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Ânimo, garotos, eu confio em vocês!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Claro, pode deixar"]],
						//[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",false],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
						[scr_cutscene_wait,1],
						[scr_cutscene_bars,true,false],
						[scr_cutscene_variable,variable.normal,o_uncle_bruce,"spd",1],
					];
					i++;
				}
				complete_cutscene=[
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"spd",0],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_to_look_at",o_bunbun],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_uncle_bruce],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Sim?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Acho que eu já acabei"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Hum..."]],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",false],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"direction",270],
					[scr_cutscene_wait,.5],
					[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_playground_getting_up_1],[s_uncle_bruce_casual_playground_idle_1_4],false,true,[.35,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_3],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_4],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"sprite_index",s_uncle_bruce_casual_playground_idle_1_7],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Muito bom, muito bom, BunBun e Todd"],-1,[[-1],[s_uncle_bruce_casual_playground_idle_1_4],[s_uncle_bruce_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_uncle_bruce,["Vocês fizeram um trabalho exelente!"],-1,[[-1],[s_uncle_bruce_casual_playground_idle_1_4],[s_uncle_bruce_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_playground_getting_down_1],[s_uncle_bruce_casual_idle_1_down],false,true,[.35,.2]],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"direction",270],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_act_state",ppl_act.npc],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",true],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Aqui, como prometido"]],
					[scr_cutscene_item,o_bunbun,-1,[item.uncle_spices,1],true,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!! Muito obrigado, Tio!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Ora, por favor, eu quem agradeço!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Sempre que precisarem de alguma coisa, me digam, ok?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Aliás, eu fico com o regador, ok?"]],
					[scr_cutscene_item,o_bunbun,item.irrigator,[-1,-1],false,true],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, aqui está!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Se cuidem, pequenos"]],
					//[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_looking_to",false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_uncle_bruce,"spd",1],
				];
			}
			break;
	}
}