function scr_talk_petter(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.someone_party,o_petter],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_petter,"ppl_talked",true],
					[scr_cutscene_variable,variable.normal,o_jill,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,2043,1347,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["E no fim foi isso..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Ele ficou me zoando por isso..."],-1,[-1,[s_petter_casual_playground_idle_1_1],[s_petter_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Caramba, Petter..."],-1,[-1,[s_jill_casual_playground_idle_1_1],[s_jill_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Se eu fosse você, eu deixaria algo gosmento de baixo do travesseiro dele..."],-1,[-1,[s_jill_casual_playground_idle_1_4],[s_jill_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Não seja assim, não quero dar motivos para ele também..."],-1,[-1,[s_petter_casual_playground_idletalk_1_2],[s_petter_casual_playground_idletalk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Não é dar motivos, é dar uma resposta..."],-1,[-1,[s_jill_casual_playground_idle_1_4],[s_jill_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Até por que..."],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Ah! Oi, BunBun!"],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Ah! BunBun, Não te vi aí..."],-1,[-1,[s_petter_casual_playground_idletalk_1_2],[s_petter_casual_playground_idletalk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá... Tá tudo bem?..."]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Sim... Tá tudo sim..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Certeza? Você não me parece nada bem, Petter..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["O Petter tá meio mal por algumas coisas que vem acontecendo..."],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Jill!!"],-1,[-1,[s_petter_casual_playground_idletalk_1_2],[s_petter_casual_playground_idletalk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Apenas disse que você está mal, não entrei em detalhes..."],-1,[-1,[s_jill_casual_playground_idle_1_2],[s_jill_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["E outra... É do BunBun que estamos falando, se tu desabafar com ele, ele não vai contar para ninguém"],-1,[-1,[s_jill_casual_playground_idle_1_1],[s_jill_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["E se contar..."],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Eu sei onde você dorme..."],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E-Eu não vou contar nada para ninguém..."]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Acho bom mesmo"],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Deixa ele em paz..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["BunBun, o que tá acontecendo é que o Tío Antony fica pegando no meu pé..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Em sua maioria, por coisas estupidas..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Como meu tamanho e como não faço nada de util com isso..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Tipo... Ele diz que sou grande e que sou frouxo demais"],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Ele fala que meu tamanho é um disperdicio, que eu deveria ser mais forte, que eu deveria ser isso e aquilo..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu tô cansado dele ficar falando isso no meu ouvido..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu... Penso que talvez ele esteja certo..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Que talvez eu esteja disperdiçando o potencial do meu corpo e-"],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_3],
					[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_playground_idle_1_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Calma, vamos por partes..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Primeiro, você não é um disperdicio, por \"não fazer nada de util com seu corpo\""]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sendo você grande e forte ou pequeno e fraco!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E se ele te acha inútil baseado no conceito DELE, então é problema inteiramente dele"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Agora o que VOCÊ quer? Você está bem do jeito que está? Se sim, então tudo bem!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Agora se ele fica te atazanando, você deveria falar com a Mamãe e com os outros Tios e Tias sobre..."]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["É que... Eu tenho vergonha de falar sobre isso para os Tios..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_3],
					[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_playground_idle_1_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas vergonha do quê?"]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["E se eles... Estiverem de acordo com o Tio Antony?..."],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Ainda mais com a guerra que está tendo..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu não quero participar... Eu nunca pedi para estar nessa situação..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_3],
					[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_playground_idle_1_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter, a guerra já está no fim, ambos os reinos já estão firmando acordos de paz, tudo isso graças aos Omnis!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Logo logo, não teremos que nos preocupar com mais nada disso! E voltaremos para nosso pais!"]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_playground_idle_1_2],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_playground_idletalk_1_1],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["No melhor dos casos, sim..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_3],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter..."]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se você precisar de algo, não evite, não pense, de me chamar"]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Pode deixar, BunBun..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["De verdade, muito obrigado, BunBun"],-1,[-1,[s_petter_casual_playground_idle_1_1],[s_petter_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Acho... Que foi bom eu ter falado contigo"],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["De verdade, muito obrigado, BunBun"],-1,[-1,[s_petter_casual_playground_idle_1_2],[s_petter_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_3],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu quem agradeço por ter confiado em mim por ter me contado sobre isso"]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Obrigado, fofuxo"],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Ai, BunBun..."],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Obrigada por dar uma animada no coelhão aqui"],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Ele já estava todo borocoxo"],-1,[-1,[s_jill_casual_playground_idle_1_4],[s_jill_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Se não fosse por você, não sei o que seria de mim"],-1,[-1,[s_jill_casual_playground_idle_1_2],[s_jill_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_3],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Não não!! Eu apenas me preocupe com vocês, quero ver o bem de todos dessa casa!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Fofo"],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Eu espero de verdade que você tenha esse mesmo cuidado com você mesmo"],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Pode apostar!!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Perfeito"],-1,[-1,[s_jill_casual_playground_idle_1_4],[s_jill_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_playground_idletalk_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_move_character,o_bunbun,2043,1347,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_3],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter, se precisar de algo, estou aqui, ok?..."]],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["..."],-1,[-1,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jill,["Dê um tempo para ele, ok?...."],-1,[-1,[s_jill_casual_playground_idle_1_3],[s_jill_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ok..."]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_jill,"sprite_index",s_jill_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_playground_idletalk_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,.5],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
	}
}