// Los recursos de Script han cambiado para la v2.3.0 Consulta
// https://help.yoyogames.com/hc/en-us/articles/360005277377 para más información
function scr_talk_jeyjey(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_jeyjey],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_jeyjey,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,1652,1487,false,1,true,true],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_idle_1_4],false,true,[.2,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Olá, BunBun"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oi, JeyJey, buscando insetos?"],-1,[-1,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Sim, estou, formigas em especificos"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Enquanto Todd e Nickolais correm por aí, eu fico aqui vendo as formigas"],-1,[-1,[s_jeyjey_casual_playground_idle_1_2],[s_jeyjey_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Não entendo muito bem o por que deles ficarem correndo por aí..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_12],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Mas eu gosto de ficar vendo formigas..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["HeeHee, é legal que você goste de insetos!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, o Todd e o Nickolai gostam de brincar de caçar Maledictus"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["HeeHee, de fato!... Bom... Quer ver formigas comigo?"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Claro, JeyJey!!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_4],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você gosta bastante das formigas, né?"],-1,[-1,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Todos os insetos são legais, apesar das formigas serem interessantes"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Pensei que você gostasse mais das formigas"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Nah, elas são legais, mais fáceis de se achar..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Bom, isso tudo depende de onde você está, é claro"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_12],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["HeeHee"],-1,[-1,[s_jeyjey_casual_playground_idle_1_4],[s_jeyjey_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Aqui na casa, é mais fácil achar formigas, lacraias, moscas, libélulas, borboletas, larvas e besouros e... AH!"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Falando em besouros! Besouros são muito legais! Não são meus favoritos, mas eles são tão diversos!"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Por exemplo!"],-1,[-1,[s_jeyjey_casual_playground_idle_1_2],[s_jeyjey_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["As joaninhas são uma espécie de besouro! Sem falar que existem vários pelo mundo"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["HeeHee"],-1,[-1,[s_jeyjey_casual_playground_idle_1_4],[s_jeyjey_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jeyjey,"sprite_index",s_jeyjey_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["O que?! As joaninhas!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Sim sim! As joaninhas! O reino dos insetos é incrível!..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["E nojento..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Por exemplo!"],-1,[-1,[s_jeyjey_casual_playground_idle_1_2],[s_jeyjey_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["As formigas, as ainhas em específico, carregam uma parte da comida, com elas, quando saem dos ninhos, ara formarem novas colônias"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Quando encontram o lugar perfeito, elas cavam, vomitam essa comida, e mistura com suas próprias fezes, para fermentar e fazer uma espécie de \"fazenda\" onde ela vai sobreviver com isso por um tempo"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Isso tudo antes das primeiras operárias nascerem e começarem a salir para coletar comida"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["HeeHee"],-1,[-1,[s_jeyjey_casual_playground_idle_1_4],[s_jeyjey_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jeyjey,"sprite_index",s_jeyjey_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eca"],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Eca mesmo..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas JeyJey, qual o seu inseto favorito?"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Isso é uma pergunta dificil de se fazer..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_2],[s_jeyjey_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Poderia ser Besouro Hércules! A larva dele é do tamanho da mão do Tio"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Do Tio Big B, Tio Antomy ou Tio Dmitriy?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Seja qual for, a mão deles são enormes, não?"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você tem um ponto"],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Exato! Essa é a parte divertida! O Besouro Hércules é um dos maiores do mundo!"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sério?! Você já chegou a ver um?!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Não... Apenas os vi em livros aqui de casa..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_2],[s_jeyjey_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Mas ele também não é o meu favorito... Poderia ser também a Centopeia Amazônica"],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Centopeia Amazônica"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Sim, foi uma centopeia que existia antigamente, atualmente ela está em extinssão... O Rubbert teria medo dela..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Uh?... Por que?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["No passado, essas centopeias comiam morcegos..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah!! Isso é sério?!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Sim sim~"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Mas isso foi antes da guerra, há muito muito tempo atrás..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Mas elas também não são minhas favoritas... Apesar de terem sido uma das maiores centopeias do mundo"],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, então qual o seu inseto favorito? O favorito entre todos!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Uma mariposa branca, com detalhes vermelhos... Não sei o nome dela"],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh! E ela era grande? Uma das maiores?!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_jeyjey,"sprite_index",s_jeyjey_casual_playground_idle_1_1],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Não, ela era bem pequena... Menor que meu polegar"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh! E por que ela?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Eu achei ela bonita... E quando a vi, na parede da casa, ela estava tão..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Calma..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_jeyjey,"sprite_index",s_jeyjey_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Calma?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Sim... Essa pequena mariposa me fez gostar de insetos, de uma forma geral..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah!! Que bonito, Jeyjey!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["HeeHee"],-1,[-1,[s_jeyjey_casual_playground_idle_1_4],[s_jeyjey_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Bem, no geral é isso..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_2],[s_jeyjey_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu gosto de insetos..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["E você? Do que gosta?"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Uh? Eu?..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ainda não tenho certeza"],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Talvez ajudar as pessoas"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Bom..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_2],[s_jeyjey_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["O Todd gosta de comer, o Nickolai gosta de esportes, Grettel e Nina gostam de flores..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Se você ainda não descobriu, apenas sigue buscando mais, faça coisas novas e não tenha medo de falhar, ok?"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh!... Ok..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_4],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Obrigado por me ouvir falar sobre insetos..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Quando você achar o que gostar, venha me falar sobre o que achou..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_3],[s_jeyjey_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Tudo bem?"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Pode deixar!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Obrigado..."],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, vou ver como os outros estão, tudo bem?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Sem problemas, se cuide, por favor"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você também, JeyJey!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_jeyjey,"sprite_index",s_jeyjey_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downright],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_move_character,o_bunbun,1652,1487,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Olá BunBun"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oi, JeyJey, alguma novidade com as formigas?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Elas seguem em seu percurso"],-1,[-1,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Entendo"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_jeyjey,"sprite_index",s_jeyjey_casual_playground_idle_1_1],
					[scr_cutscene_wait,.5],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
	}
}