visible=false;
minigame=-1;
minigame_start=true;
temp=false;
minigame_timer=[0,0];
minigame_draw_gui=false;
minigame_screen=-1;
minigame_seting=true;
minigame_combo=1;
minigame_combo_count=0;
curtain_frm=0;
curtain_xx=[global.cw,0];
curtain_open=false;
minigame_index=0;
minigame_level=[
	[false],//open
	[false,288],//menu
	[false,0],//ingame?
	[false,-288,-288],//endgame
];
game_over=false;
minigame_bars=[[288/2,false],[288/2,false]];
minigame_score=0;
minigame_score_index=0;
minigame_index=0;
minigame_spr_time=0;
minigame_spr=-1;
minigame_sbg=-1;
minigame_end_alp_1=0;
minigame_end_alp_2=0;
minigame_point=0;
minigame_cursor_x=0;
minigame_cursor_y=0;
minigame_cursor_confirm=0;
_words=-1;
t_cutscene_play=0;
counter=-1;
timer=0;
freeze_start=false;
freeze_stop=false;
randomize();
freeze_limit=choose(3,3.5,4);
freeze_run_limit=3000;
freeze_round=1;
freeze_bg=0;
freeze_walk=false;
freeze_walk_timer=0;
freeze_p1_x=freeze_run_limit;
freeze_p1_s=s_hud_minigame_freeze_bunbun_idle_1;
freeze_p1_stop_s=0;
freeze_p1_idle_s=0;
freeze_p1_walk_s=0;
freeze_p2_x=freeze_run_limit;
freeze_frame=0;
freeze_p2_s=s_hud_minigame_freeze_vladmir_idle_1;
freeze_p2_stop_s=0;
freeze_p2_idle_s=0;
freeze_p2_walk_s=0;
freeze_paxton_s=s_hud_minigame_freeze_paxton_idle_1;
