function scr_talk_eleanor(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_eleanor],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_hellen,"ppl_talked",true],
					[scr_cutscene_variable,variable.normal,o_eleanor,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,1725,1671,false,1,true,true],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_idle_1_3],false,true,[.2,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_eleanor,"sprite_index",s_eleanor_casual_playground_idle_1_2],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Olá Hellen! Olá Eleanor!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Olá BunBun!"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Opa, BunBun!"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_eleanor,"sprite_index",s_eleanor_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Fazendo sua checagem habitual?"],-1,[-1,[s_hellen_casual_playground_idle_1_2],[s_hellen_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["HeeHee! Eu tenho meus costumes~"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Se eu tivesse a mesma determinação que o BunBun tem de ir de pessoa em pessoa perguntando se estão todos bem"],-1,[-1,[s_eleanor_casual_playground_idle_1_2],[s_eleanor_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Eu tenho certeza que já teria dominado o mundo"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Ora, Eleanor! Deixe dessas bobagens!"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Mas eu não tô mentindo!"],-1,[-1,[s_eleanor_casual_playground_idle_1_2],[s_eleanor_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["O BunBun faz isso por que ele tem carinho por todos"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Isso motiva muito ele, todas as vezes eu vejo pessoas determinadas pelo ódio, nunca por uma paixão sincera"],-1,[-1,[s_eleanor_casual_playground_idle_1_2],[s_eleanor_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Gosto de pensar que, com a dose certa, o mundo pode se tornar um lugar melhor"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Que afável!"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu gosto como você usa essas palavras bonitas"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Ela sempre usa, muitas vezes eu nem sei o que significa"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Ela pode tá me xingando?"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Sim, mas pelo menos está me xingando bonito"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Céus, Eleanor! Jamais te xingaria!"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["HeeHee!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_eleanor,"sprite_index",s_eleanor_casual_playground_idle_1_2],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas o que vocês estão fazendo?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Nada de mais, apenas jogando conversa fora"],-1,[-1,[s_eleanor_casual_playground_idle_1_2],[s_eleanor_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Tava contando para a Hellen sobre algumas coisas da guerra"],-1,[-1,[s_eleanor_casual_playground_idle_1_2],[s_eleanor_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Eleanor anda estudando bastante sobre carros"],-1,[-1,[s_hellen_casual_playground_idle_1_2],[s_hellen_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Seguramente assim que ela sair daqui, ela vai fazer uma escola de mecânica"],-1,[-1,[s_hellen_casual_playground_idle_1_2],[s_hellen_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Confio nela para ser uma grande engenheira mecânica"],-1,[-1,[s_hellen_casual_playground_idle_1_1],[s_hellen_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["HeeHee! Pode deixar, farei meu melhor!!"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_eleanor,"sprite_index",s_eleanor_casual_playground_idle_1_2],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas e você, Hellen? O que pretende ser quando sair daqui?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Honestamente, não pensei muito sobre..."],-1,[-1,[s_hellen_casual_playground_idle_1_4],[s_hellen_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Mas eu flerto muito com a área de medicina"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Claro, não seria medicina voltada para a guerra"],-1,[-1,[s_hellen_casual_playground_idle_1_4],[s_hellen_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Mas talvez enfermeira de uma Esperança ou um hospital comum seria interessante"],-1,[-1,[s_hellen_casual_playground_idle_1_2],[s_hellen_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["E você? Quer ser um Tio?"],-1,[-1,[s_hellen_casual_playground_idle_1_2],[s_hellen_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_12],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Com a maneira cuidadosa que sempre trata os outros, você seria um Tio exemplar!"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você não é a primeira a me comentar sobre"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Ora, tenha santa paciência! Claramente o BunBun tem vocação para isso!"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_3],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_12],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Sem falar que eu daria de tudo para ver o BunBun, baixinho como é, usando um avental como o do Tio Big B!"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Ok, ela tem um bom ponto, você ficaria incrível usando um avental de tamanho infantil"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["HeeHee! Que cruel, é dificil para os Tios encontrarem roupa para mim!"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_eleanor,"sprite_index",s_eleanor_casual_playground_idle_1_2],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, meninas, vou indo terminar de ver como os ostros estão, ok?"],-1,[-1,[s_bunbun_casual_playground_idle_1_12],[s_bunbun_casual_playground_talk_1_12]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Tudo bem! cuide-se BunBun!"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Voa, muleque!"],-1,[-1,[s_eleanor_casual_playground_idle_1_1],[s_eleanor_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_eleanor,"sprite_index",s_eleanor_casual_playground_talk_1_1],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downright],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_move_character,o_bunbun,1725,1671,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_eleanor,["Olá Mini-Tio!"],-1,[-1,[s_eleanor_casual_playground_idle_1_2],[s_eleanor_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Eleanor!"],-1,[-1,[s_hellen_casual_playground_idle_1_3],[s_hellen_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HaaHaa, por favor!! Mas essa foi boa"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_eleanor,"sprite_index",s_eleanor_casual_playground_talk_1_1],
					[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,.5],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
	}
}