if(global.event[0][2]==progress.non_complete){
	quest_array=[
		[0,quest_type.talk_to,o_olivia]
	]
	complete_cutscene=[];
	non_complete_cutscene[0]=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,584,362,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
		[scr_cutscene_move_character,o_laszlo,639,362,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
		[scr_cutscene_wait,1],
		[scr_cutscene_animation_sprite,o_olivia,[s_olivia_casual_hide_n_seek_intro],[s_olivia_casual_hide_n_seek_idle_1],false,true,[.35,.2]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Tah-dah!!!","¡¡¡Tah-dah!!!","Tah-dah!!!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_1],[s_olivia_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Podem tardar, porém nunca recusar!","¡Puedes tardar, pero nunca rechazar!","Yo can be late, but never decline!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_2],[s_olivia_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Eu mesma! A grandiosa Olivia!!","¡Yo misma! ¡¡La grandiosa Olivia!!","Yes, myself! The great Olivia!!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_1],[s_olivia_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
		[scr_cutscene_variable,variable.normal,o_olivia,"sprite_index",s_olivia_casual_hide_n_seek_idle_2],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bravo!! Bravo!!"]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uma grande entrada, não?!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah!... Sim, bem extravagante"]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["De fato, uma entrada bem olivia"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Obrigada! Obrigada!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_2],[s_olivia_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Me pergunto o que será da criança sem nome que você cuida"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Qual, a 47?"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_3],[s_olivia_casual_hide_n_seek_talk_3]],false,false,[0,.2,.2]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Precisamente"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Ah!! Sim!! Faltam poucos dias para o aniversário dela!! Ela vai finalmente conseguir o nome dela!!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_1],[s_olivia_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
		[scr_cutscene_variable,variable.normal,o_olivia,"sprite_index",s_olivia_casual_hide_n_seek_idle_3],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Estou curioso para saber que nome a criança sem nome 47 vai colocar a 48 e a 48 a 47"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["E eu do 45 para o 46 e vice-versa"]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Ah! Esses dois também!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_2],[s_olivia_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Não é nada pessoal, mas é que eu vejo a 47 como minha irmã!!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_2],[s_olivia_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["É quase que um clone de você!"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["HeeHee!! Bom, vou indo para o hall, esperar vocês, lerdões, terminarem"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_2],[s_olivia_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Haa! Bobona!"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_olivia,["Aprendi com o melhor!!"],-1,[[-1],[s_olivia_casual_hide_n_seek_idle_1],[s_olivia_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
		[scr_cutscene_variable,variable.normal,o_olivia,"ppl_talked",true],
		[scr_cutscene_wait,1],
		[scr_cutscene_instance_destroy,o_olivia],
		[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger_3],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ela é tão energética!!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Eu gosto dela, ela é toda agitada"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ela é quem passa mais tempo com a 47?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sim, ela cuida tanto da 47 quanto da 48, mas ela gosta mais da 47"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E o 45 e o 46?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Hum... Creio que ninguém... O 45 eu sei que ele gosta de ficar sozinho, mas o 46..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Um cuida do outro, né?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Da sua maneira..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Entendo... Pobre 46..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ele é inteligente, tipo, muito inteligente... Mas seus espinhos acabam afastando a todos"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Eu gosto dele, mas os espinhos machucam..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá tudo bem, eu entendo"]],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false]
	];
}