quest_array=[
	[0,quest_type.talk_to,o_cutscene_trigger_1],
];
complete_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,436,366,false,1,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
	[scr_cutscene_move_character,o_laszlo,474,366,false,1,true,false],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
	[scr_cutscene_wait,1],
	[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_intro_2],[s_danica_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Finalmente!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_2],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Eu pensei que vocês tinham se esquecido de mim!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HaaHaa! Não, nunca esqueceremos de você!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Fomos idiotas por não ter pensado aí antes..."]],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Bom, são vocês quem estão dizendo! HeeHee!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Na próxima serei a última a ser encontrada!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Yay! É assim que se fala!!"]],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
	[scr_cutscene_variable,variable.normal,o_danica,"ppl_talked",o_danica],
	[scr_cutscene_wait,1],
	[scr_cutscene_instance_destroy,o_danica],
	[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu não lembrava dela ser tão competitiva assim"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah... É que você não convive tanto assim com ela"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Me surpreende que ela não esteja planejando um golpe de estado para aplicar na Hierarquia Rosa"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não que você saiba..."]],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Bom ponto"]],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false],
];
non_complete_cutscene[0]=[
	[scr_cutscene_variable,variable.normal,o_danica,"ppl_talked",o_danica],
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,436,366,false,1,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
	[scr_cutscene_move_character,o_laszlo,474,366,false,1,true,false],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
	[scr_cutscene_wait,1],
	[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_intro_1],[s_danica_casual_hide_n_seek_idle_1],false,true,[.35,.2]],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Te achamos!!"]],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Hump!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_idle_1]],false,false,[0,.2,.2]],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Não foi um bom esconderijo"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas foi uma boa tentativa!"]],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Deixe disso! Farei melhor na próxima!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Confio que você fará melhor!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Uh-hum!..."]],
	[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Hump!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_idle_1]],false,false,[0,.2,.2]],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_instance_destroy,o_danica],
	[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu gostei da ideia de se esconder justo aqui"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Honestamente, me parecia bem previsível..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Era mais um golpe de sorte do que qualquer coisa"]],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Parando para pensar, você tem razão"]],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false],
];