#region dia 0
non_avaliable_cutscene=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
		[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
		[scr_cutscene_room_goto,rm_corridors,true,false],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",1031],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",312],
		[scr_cutscene_refresh_party_member,true,false],
		[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
		[scr_cutscene_variable,variable.normal,o_camera,"y",328],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1031,328,false,1,true,true],
		[scr_cutscene_refresh_party_member,false],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
];
#endregion
if(global.event[0][2]==progress.non_complete){
	quest_array=[
		[0,quest_type.talk_to,o_danica],
	];
	#region
	non_complete_cutscene[0]=[
		[scr_cutscene_variable,variable.normal,o_cutscene_trigger_1,"ppl_talked",true],
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
		[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
		[scr_cutscene_room_goto,rm_corridors,true,false],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",1031],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",312],
		[scr_cutscene_refresh_party_member,true],
		[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
		[scr_cutscene_variable,variable.normal,o_camera,"y",328],
		[scr_cutscene_wait,1],
		[scr_cutscene_instance_create,1182,549,"Instances_People_1",o_boris],
		[scr_cutscene_animation_sprite,o_boris,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1],false,true,[1,.21]],
		[scr_cutscene_instance_create,234,574-17,"Instances_People_1",o_julia],
		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_0],[s_julia_casual_hide_n_seek_idle_0],false,true,[1,.21]],
		[scr_cutscene_instance_create,1255,427,"Instances_People_2",o_jasenska],
		[scr_cutscene_animation_sprite,o_jasenska,[s_jasenska_casual_hide_n_seek_idle_0],[s_jasenska_casual_hide_n_seek_idle_0],false,true,[1,.21]],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1031,328,false,1,true,true],
		[scr_cutscene_refresh_party_member,false],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
		//[scr_cutscene_instance_create,1234,397,"Instances_People_2",o_cutscene_trigger_3],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",4.375,1234,397],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",5.25,1234,397],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_avaliable_cutscene",
		//	[
		//		[scr_cutscene_bars,true,true],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_move_character,o_bunbun,1214,413,false,1,true,true],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
		//		[scr_cutscene_move_character,o_laszlo,1191,433,false,1,true,true],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",0],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_animation_sprite,o_jasenska,[s_jasenska_casual_hide_n_seek_intro],[s_jasenska_casual_hide_n_seek_idle_1],false,true,[.1,2]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Tah-Dah!!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Vocês finalmente me encontraram!!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
		//		[scr_cutscene_variable,variable.normal,o_jasenska,"sprite_index",s_jasenska_casual_hide_n_seek_idle_2],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não vou vou mentir, foi um esconderijo criativo!!"]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Pera, sério?..."],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_2],[s_jasenska_casual_hide_n_seek_talk_2]],false,false,[0,.2,.25]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Digo, sim sim!! Eu sempre penso fora da caixa!!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Se é que você me entende!..."],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_2],[s_jasenska_casual_hide_n_seek_talk_2]],false,false,[0,.2,.25]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HaaHaa!! Essa foi boa!!"]],
		//		[scr_cutscene_variable,variable.normal,o_jasenska,"sprite_index",s_jasenska_casual_hide_n_seek_idle_3],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",45],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vamos, Laszlo, ânimo!!"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah... Sim!..."]],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",0],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["O BunBunn tem razão"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["A Dama de Pétalas, Jasenska, foi realmente criativa"]],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Ora, deixa disso! Estamos só nós aqui, não precisa disso tudo!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_4],[s_jasenska_casual_hide_n_seek_talk_4]],false,false,[0,.2,.25]],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah!... Mas"]],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Bom, se te faz se sentir melhor..."],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_3],[s_jasenska_casual_hide_n_seek_talk_3]],false,false,[0,.2,.25]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Como Dama de Pétalas! Eu ordeno que se divirta!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["E não conte para ninguém sobre isso, ok?!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_3],[s_jasenska_casual_hide_n_seek_talk_3]],false,false,[0,.2,.25]],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Bom, tudo bem, eu acho..."]],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Perfeito, bom, vou estar esperando por vocês no andar de baixo, ok?!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_4],[s_jasenska_casual_hide_n_seek_talk_4]],false,false,[0,.2,.25]],
		//		[scr_cutscene_variable,variable.normal,o_jasenska,"sprite_index",s_jasenska_casual_hide_n_seek_idle_3],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Tudo bem..."]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sem problemas!!"]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
		//		[scr_cutscene_instance_layer,o_jasenska,"Instances_People_1"],
		//		[scr_cutscene_variable,variable.normal,o_jasenska,"x",594],
		//		[scr_cutscene_variable,variable.normal,o_jasenska,"y",552],
		//		[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_act_state",ppl_act.npc],
		//		[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_talked",true],
		//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_refresh_party_member,false],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_bars,true,false],
		//		[scr_cutscene_instance_destroy_nearst,1214,413,o_cutscene_trigger_3],
		//	]
		//,1234,397],
		//[scr_cutscene_instance_create,1170,551,"Instances_People_1",o_cutscene_trigger_3],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",3,1170,551],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",.5,1170,551],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_avaliable_cutscene",
		//	[
		//		[scr_cutscene_bars,true,true],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_move_character,o_bunbun,1152,572,false,1,true,true],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
		//		[scr_cutscene_move_character,o_laszlo,1181,589,false,1,true,true],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["..."]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["..."]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["..."]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Nós..."]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Te achamos... Boris..."]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["Não"],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh, sim, te achamos..."]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["..."],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
		//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["Tá bom..."],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
		//		[scr_cutscene_variable,variable.normal,o_boris,"x",659],
		//		[scr_cutscene_variable,variable.normal,o_boris,"y",593],
		//		[scr_cutscene_variable,variable.normal,o_boris,"ppl_act_state",ppl_act.npc],
		//		[scr_cutscene_variable,variable.normal,o_boris,"ppl_talked",true],
		//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que foi isso?"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Foi o Boris"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum... Justo"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ele é a minha dupla, já estou acostumado com ele"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Sinto muito?"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não não! Eu gosto dele assim!"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Tudo bem!!"]],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_bars,true,false],
		//		[scr_cutscene_instance_destroy_nearst,1170,545,o_cutscene_trigger_3],
		//	]
		//,1170,551],
		//[scr_cutscene_instance_create,204,547,"Instances_People_1",o_cutscene_trigger_3],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",7.625,204,547],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",2,204,547],
		//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_avaliable_cutscene",
		//	[
		//		[scr_cutscene_bars,true,true],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_move_character,o_bunbun,212,584,false,1,true,true],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
		//		[scr_cutscene_move_character,o_laszlo,256,584,false,1,true,true],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_intro],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Te achamos, Julia!...."]],
		//		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_1],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["...."]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Foi um bom esconderijo, Dama de Espinhos..."]],
		//		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_1],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["...."]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
		//		[scr_cutscene_variable,variable.normal,o_julia,"x",621],
		//		[scr_cutscene_variable,variable.normal,o_julia,"y",552],
		//		[scr_cutscene_variable,variable.normal,o_julia,"ppl_act_state",ppl_act.npc],
		//		[scr_cutscene_variable,variable.normal,o_julia,"ppl_talked",true],
		//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Que clima..."]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["..."]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não fica assim!"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eles não aplicar um castigo em você, eu prometo em conversar com eles!!"]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não é sobre isso..."]],
		//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh Tudo bem..."]],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
		//		[scr_cutscene_wait,1],
		//		[scr_cutscene_bars,true,false],
		//		[scr_cutscene_instance_destroy_nearst,204,547,o_cutscene_trigger_3],
		//	]
		//,204,547],
	];
	
	complete_cutscene=[
		[scr_cutscene_variable,variable.normal,o_cutscene_trigger_1,"ppl_talked",true],
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
		[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
		[scr_cutscene_room_goto,rm_corridors,true,false],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",1031],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",312],
		[scr_cutscene_refresh_party_member,true],
		[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
		[scr_cutscene_variable,variable.normal,o_camera,"y",328],
		[scr_cutscene_wait,1],
		//[scr_cutscene_instance_create,545,566,"Instances_People_1",o_danica],
		//[scr_cutscene_variable,variable.normal,o_danica,"x",545],
		//[scr_cutscene_variable,variable.normal,o_danica,"y",566],
		//[scr_cutscene_variable,variable.normal,o_danica,"ppl_act_state",ppl_act.npc],
		[scr_cutscene_instance_create,1182,549,"Instances_People_1",o_boris],
		[scr_cutscene_animation_sprite,o_boris,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1],false,true,[1,.21]],
		[scr_cutscene_instance_create,234,574-17,"Instances_People_1",o_julia],
		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_0],[s_julia_casual_hide_n_seek_idle_0],false,true,[1,.21]],
		[scr_cutscene_instance_create,1255,427,"Instances_People_2",o_jasenska],
		[scr_cutscene_animation_sprite,o_jasenska,[s_jasenska_casual_hide_n_seek_idle_0],[s_jasenska_casual_hide_n_seek_idle_0],false,true,[1,.21]],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1031,328,false,1,true,true],
		[scr_cutscene_refresh_party_member,false],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
		[scr_cutscene_instance_create,1234,397,"Instances_People_2",o_cutscene_trigger_3],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",4.375,1234,397],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",5.25,1234,397],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_avaliable_cutscene",
			[
				[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_talked",true],
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,1214,413,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
				[scr_cutscene_move_character,o_laszlo,1191,433,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",0],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_jasenska,[s_jasenska_casual_hide_n_seek_intro],[s_jasenska_casual_hide_n_seek_idle_1],false,true,[.1,2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Tah-Dah!!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Vocês finalmente me encontraram!!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_jasenska,"sprite_index",s_jasenska_casual_hide_n_seek_idle_2],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não vou vou mentir, foi um esconderijo criativo!!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Pera, sério?..."],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_2],[s_jasenska_casual_hide_n_seek_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Digo, sim sim!! Eu sempre penso fora da caixa!!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Se é que você me entende!..."],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_2],[s_jasenska_casual_hide_n_seek_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HaaHaa!! Essa foi boa!!"]],
				[scr_cutscene_variable,variable.normal,o_jasenska,"sprite_index",s_jasenska_casual_hide_n_seek_idle_3],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",45],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vamos, Laszlo, ânimo!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah... Sim!..."]],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["O BunBunn tem razão"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["A Dama de Pétalas, Jasenska, foi realmente criativa"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Ora, deixa disso! Estamos só nós aqui, não precisa disso tudo!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_4],[s_jasenska_casual_hide_n_seek_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah!... Mas"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Bom, se te faz se sentir melhor..."],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_3],[s_jasenska_casual_hide_n_seek_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Como Dama de Pétalas! Eu ordeno que se divirta!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_1],[s_jasenska_casual_hide_n_seek_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["E não conte para ninguém sobre isso, ok?!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_3],[s_jasenska_casual_hide_n_seek_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Bom, tudo bem, eu acho..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jasenska,["Perfeito, bom, vou estar esperando por vocês no andar de baixo, ok?!"],-1,[-1,[s_jasenska_casual_hide_n_seek_idle_4],[s_jasenska_casual_hide_n_seek_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_jasenska,"sprite_index",s_jasenska_casual_hide_n_seek_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Tudo bem..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sem problemas!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_instance_layer,o_jasenska,"Instances_People_1"],
				[scr_cutscene_variable,variable.normal,o_jasenska,"x",594],
				[scr_cutscene_variable,variable.normal,o_jasenska,"y",552],
				[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_act_state",ppl_act.npc],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
				[scr_cutscene_instance_destroy_nearst,1214,413,o_cutscene_trigger_3],
			]
		,1234,397],
		[scr_cutscene_instance_create,1170,551,"Instances_People_1",o_cutscene_trigger_3],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",3,1170,551],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",.5,1170,551],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_avaliable_cutscene",
			[
				[scr_cutscene_variable,variable.normal,o_boris,"ppl_talked",true],
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,1152,572,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
				[scr_cutscene_move_character,o_laszlo,1181,589,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Nós..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Te achamos... Boris..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["Não"],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh, sim, te achamos..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["..."],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["Tá bom..."],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_variable,variable.normal,o_boris,"x",659],
				[scr_cutscene_variable,variable.normal,o_boris,"y",593],
				[scr_cutscene_variable,variable.normal,o_boris,"ppl_act_state",ppl_act.npc],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que foi isso?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Foi o Boris"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum... Justo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ele é a minha dupla, já estou acostumado com ele"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Sinto muito?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não não! Eu gosto dele assim!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Tudo bem!!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
				[scr_cutscene_instance_destroy_nearst,1170,545,o_cutscene_trigger_3],
			]
		,1170,551],
		[scr_cutscene_instance_create,204,547,"Instances_People_1",o_cutscene_trigger_3],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",7.625,204,547],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",2,204,547],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_avaliable_cutscene",
			[
				[scr_cutscene_variable,variable.normal,o_julia,"ppl_talked",true],
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,212,584,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
				[scr_cutscene_move_character,o_laszlo,256,584,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_intro],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Te achamos, Julia!...."]],
				[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_1],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["...."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Foi um bom esconderijo, Dama de Espinhos..."]],
				[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_1],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["...."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_variable,variable.normal,o_julia,"x",621],
				[scr_cutscene_variable,variable.normal,o_julia,"y",552],
				[scr_cutscene_variable,variable.normal,o_julia,"ppl_act_state",ppl_act.npc],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Que clima..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não fica assim!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eles não aplicar um castigo em você, eu prometo em conversar com eles!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não é sobre isso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh Tudo bem..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
				[scr_cutscene_instance_destroy_nearst,204,547,o_cutscene_trigger_3],
			]
		,204,547],
	];
	#endregion
}else if(global.event[0][5]==progress.non_complete){
	quest_array=[
		[0,quest_type.talk_to,o_bunbun],
	];
	non_complete_cutscene[0]=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
		[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
		[scr_cutscene_room_goto,rm_corridors,true,false],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",1031],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",312],
		[scr_cutscene_refresh_party_member,true,false],
		[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
		[scr_cutscene_variable,variable.normal,o_camera,"y",328],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1031,328,false,1,true,true],
		[scr_cutscene_refresh_party_member,false],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	];
	complete_cutscene=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
		[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
		[scr_cutscene_room_goto,rm_corridors,true,false],
		[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_talked",true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",1031],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",312],
		[scr_cutscene_refresh_party_member,true],
		[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
		[scr_cutscene_variable,variable.normal,o_camera,"y",328],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1031,328,false,1,true,true],
		[scr_cutscene_refresh_party_member,false],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
		[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,1031,328],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	];
}