function scr_talk_larry(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_larry],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_larry,"ppl_talked",true],
					[scr_cutscene_variable,variable.normal,o_clara,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,1255,1688,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Vamos vamos Todd!!"],-1,[-1,[s_larry_casual_playground_idle_1_1],[s_larry_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["O Nickolai é mais rápido!"],-1,[-1,[s_clara_casual_playground_idle_1_1],[s_clara_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Corta essa! O Todd é mais rápido!!"],-1,[-1,[s_larry_casual_playground_idle_1_2],[s_larry_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Corta essa você! Se o Todd fosse tão rápido, já teria alcançado o Nickolai!"],-1,[-1,[s_clara_casual_playground_idle_1_3],[s_clara_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["HaaHaa! Veremos!!"],-1,[-1,[s_larry_casual_playground_idle_1_1],[s_larry_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_2],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_2],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Vejo que os dois estão praticando para caçar Maledictus, não?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Pra valer!!"],-1,[-1,[s_larry_casual_playground_idle_1_2],[s_larry_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Eu to apostanto tudo no Nickolai! Ele é super rápido!"],-1,[-1,[s_clara_casual_playground_idle_1_3],[s_clara_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["E eu no Todd! Além de rápido, ele é forte!!"],-1,[-1,[s_larry_casual_playground_idle_1_2],[s_larry_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Corta essa!"],-1,[-1,[s_clara_casual_playground_idle_1_1],[s_clara_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Corta essa você!!"],-1,[-1,[s_larry_casual_playground_idle_1_2],[s_larry_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_2],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_2],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee, você também querem caçar Maledictus quando crescerem, né?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Pode apostar que sim!"],-1,[-1,[s_larry_casual_playground_idle_1_4],[s_larry_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Eu vou ser o maior caçador de Maledictus!!"],-1,[-1,[s_larry_casual_playground_idle_1_4],[s_larry_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_3],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_todd,["Só precisa parar de ser menos preguiçoso!"],-1,global.cw/2,global.ch/3,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Mas eu nem sou precuiçoso..."],-1,[-1,[s_larry_casual_playground_idle_1_3],[s_larry_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Ah, nem vem, tu é preguiçoso sim"],-1,[-1,[s_clara_casual_playground_idle_1_4],[s_clara_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Não sou não!"],-1,[-1,[s_larry_casual_playground_idle_1_3],[s_larry_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_todd,["VOCÊ É SIM!!"],-1,global.cw/2,global.ch/3,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_nickolai,["É! VOCÊ É PREGUIÇOSO MESMO!!"],-1,global.cw/2,global.ch/3,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Eu to cercado de idiotas..."],-1,[-1,[s_larry_casual_playground_idle_1_3],[s_larry_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Mas e você, Bun Bun? O que você vai querer ser?"],-1,[-1,[s_clara_casual_playground_idle_1_2],[s_clara_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!... Eu to pensando seriamente em me tornar um Tio, como Tio Big B"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Ah! Que belezinha!"],-1,[-1,[s_clara_casual_playground_idle_1_3],[s_clara_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["O BunBun seria um bom Tio"],-1,[-1,[s_larry_casual_playground_idle_1_2],[s_larry_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Sim sim! O BunBun seria um Tio perfeito!"],-1,[-1,[s_clara_casual_playground_idle_1_2],[s_clara_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Enquanto eu? Diferente de certas pessoas, eu me sairia bem como caçadora de Maledictus!"],-1,[-1,[s_clara_casual_playground_idle_1_4],[s_clara_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Se o seu tamanho for levado em consideração..."],-1,[-1,[s_larry_casual_playground_idle_1_3],[s_larry_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["A diferença é que eu posso usar minha altura para me esconder melhor!"],-1,[-1,[s_clara_casual_playground_idle_1_3],[s_clara_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Enquanto a você, seu preguiçoso?"],-1,[-1,[s_clara_casual_playground_idle_1_4],[s_clara_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Eu não sou preguiçoso..."],-1,[-1,[s_larry_casual_playground_idle_1_3],[s_larry_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["HaaHaa!! Se você diz!!"],-1,[-1,[s_clara_casual_playground_idle_1_3],[s_clara_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_2],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee, bom, vou terminar de ver como estão os outros, ok?"]],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Tudo bem, se cuida, BunBun!"],-1,[-1,[s_clara_casual_playground_idle_1_3],[s_clara_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["A gente se fala!"],-1,[-1,[s_larry_casual_playground_idle_1_4],[s_larry_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downleft],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_move_character,o_bunbun,1255,1688,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Vai todd!"],-1,[-1,[s_larry_casual_playground_idle_1_1],[s_larry_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Vai Nickolai!!"],-1,[-1,[s_clara_casual_playground_idle_1_1],[s_clara_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Todd!!"],-1,[-1,[s_larry_casual_playground_idle_1_2],[s_larry_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["Nickolai!!"],-1,[-1,[s_clara_casual_playground_idle_1_1],[s_clara_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["TODD!!"],-1,[-1,[s_larry_casual_playground_idle_1_4],[s_larry_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_clara,["NICKOLAI!!"],-1,[-1,[s_clara_casual_playground_idle_1_3],[s_clara_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_larry,"sprite_index",s_larry_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_clara,"sprite_index",s_clara_casual_playground_idle_1_1],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uau..."]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
	}
}