non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	
	[scr_cutscene_room_goto,rm_basement_2,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",601],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",424],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"x",601],
	[scr_cutscene_variable,variable.normal,o_camera,"y",454],
	[scr_cutscene_wait,1],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,601,454],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,601,454,false,1,true,true],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,601,454],
	[scr_cutscene_wait,1],
	[scr_cutscene_condition,question.have_person,o_todd,
		[
			[
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh?..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah não não não!..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["É uma daquelas portas que só abre de um lado..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vou ter que achar outra saída..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			],
			[
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_move_character,o_todd,24,24,true,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh?..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_todd],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A gente tá preso"],-1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Como assim?!"],-1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A gente tá preso"],-1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu sabia que descer aqui contigo era furada!!"],-1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu... Desculpe..."],-1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá tá... Só vamos achar uma outra saída..."],-1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá..."],-1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",-1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",-1],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
		]
	],
];