function scr_talk_grettel(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_grettel]
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_grettel,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,267,1582,false,1,true,true],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_idle_1_3],false,true,[.2,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Olá, Grettel!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Olá, BunBun"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_11],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["No que posso ajudar, BunBun?"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Só queria saber como você está, se você está bem e tudo mais..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Hum..."],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Eu estou bem até o momento..."],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Sabe, BunBun, você gosta de flores?"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim, eu gosto!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Isso é bom, flores são importantes, além de serem bonitas e calmas"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Eu gosto das flores pois além de serem importantes para a polinização, elas dizem muitos sobre as coisas nosso ao redor..."],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Sobre nossas emoções, sensações e até mesmo o que desejamos"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Caso os entregamos como presente para alguém..."],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh! Você tem alguma flor favorita?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["De fato tenho sim, BunBun..."],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["E são os lírios brancos"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Lírios brancos? É por que elas são bonitas?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Podemos dizer que sim, também, mas no fundo..."],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["É por conta da mensagem que elas carregam..."],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["E qual seria?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Simples... Elas significam o luto"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_2],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh... Bem..."],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Vou ser honesto, eu não esperava por essa resposta"],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas se não for um incômodo, por que?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Por que uma flor com uma mensagem tão funebre?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["O luto, BunBun, não é totalmente sobre a morte, mas sim sobre a aceitação das coisas que não podemos mudar"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Existem certas coisas que não podemos lutar contra, e a morte é uma delas... O luto é processar, aceitar e viver com a ausência"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Entende?"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim, entendo, apenas não estou totalmente de acordo com a ideia..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ou melhor, não a digeri por completo..."],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["A única coisa que peço é que não interprete como se eu estivesse cultundo a morte"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Apenas sinto que a morte é uma grande mudança para a vida de todos..."],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você diz isso mais pelos soldados?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Precisamente, BunBun..."],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Eu sinto luto por todos os saldados que lutaram, e lutam, na guerra..."],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Isso é bem bonito, na realidade..."],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Sim... Acho que sim..."],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_11],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Que flor você seria?"],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Creio que Calênculas"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh! Elas são bonitas?!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Sim, bem bonitas"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh! E qual eu seria?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Sem sombra de dúvidas, Girassóis"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Girassóis?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Sim, sempre em diração ao sol, sempre tão positivo e alegre"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["De fato, um girassol"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh! Muito obrigado, Grettel!!"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Sem problemas, BunBun"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, vou ver como as outras pessoas estão, ok?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Tudo bem, se precisar de alguma coisa, estou aqui, tudo bem?"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Claro!! Fique bem, ok?"],-1,[-1,[s_bunbun_casual_playground_idle_1_3],[s_bunbun_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_1],
					[scr_cutscene_wait,.2],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_2],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downright],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,267,1582,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_grettel],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_2],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Calêndula"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Girassol"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Como tem estado?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Calmo... E você?"],-1,[-1,[s_grettel_casual_playground_idle_1_2],[s_grettel_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bem! Bom, só vim ver como estava o jardim!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_grettel,["Você sempre chega, trazendo o sol contigo"],-1,[-1,[s_grettel_casual_playground_idle_1_3],[s_grettel_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_grettel,"sprite_index",s_grettel_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
			break;
	}
}