switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_calina],
					[-1,quest_type.talk_to,o_edgar],
					[-1,quest_type.talk_to,o_grettel],
					[-1,quest_type.talk_to,o_tomas],
					[-1,quest_type.talk_to,o_fritz],
					[-1,quest_type.talk_to,o_nina],
					[-1,quest_type.talk_to,o_linus],
					[-1,quest_type.talk_to,o_james],
					[-1,quest_type.talk_to,o_wendy],
					[-1,quest_type.talk_to,o_larry],
					[-1,quest_type.talk_to,o_clara],
					[-1,quest_type.talk_to,o_hellen],
					[-1,quest_type.talk_to,o_eleanor],
					[-1,quest_type.talk_to,o_amanda],
					[-1,quest_type.talk_to,o_jeyjey],
					[-1,quest_type.talk_to,o_iriya],
					[-1,quest_type.talk_to,o_danya],
					[-1,quest_type.talk_to,o_darya],
					[-1,quest_type.talk_to,o_uncle_bruce],
					[-1,quest_type.talk_to,o_rubbert],
					[-1,quest_type.talk_to,o_petter],
					[-1,quest_type.talk_to,o_jill],
				];
				var i=0; repeat array_length(quest_array){
					non_complete_cutscene[i]=[
						[scr_cutscene_bars,true,true],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O está vendo..."]],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E eu ainda tenho que terminar de ver se todos estão bem..."]],
						[scr_cutscene_wait,1],
						[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,false],
						[scr_cutscene_wait,1],
						[scr_cutscene_bars,true,false]
					];
					i++;
				}
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Esquece"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Dhan ainda não terminou essa parte, nem perca seu tempo"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false]
				]
				/*
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
					[scr_cutscene_move_character,o_bunbun,0,80,true,.5,true,false],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
					[scr_cutscene_room_goto,rm_forest_1,true],
					[scr_cutscene_variable,variable.normal,o_camera,"x",1178],
					[scr_cutscene_variable,variable.normal,o_camera,"y",94],
					[scr_cutscene_variable,variable.normal,o_bunbun,"x",1178],
					[scr_cutscene_variable,variable.normal,o_bunbun,"y",0],
					[scr_cutscene_audio_play,audio_type.bgm,bgm_006,true,.25,1],
					[scr_cutscene_wait,1],
					[scr_cutscene_audio_play,audio_type.bgm,bgs_001,true,1,1],
					[scr_cutscene_circle_wake_up,true,false,1178,94,true,true,false,make_color_rgb(36,34,52)],
					[scr_cutscene_move_character,o_bunbun,0,80,true,.5,true,false],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false]
				]
				*/
			}
			#endregion
			break;
}