non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,x,y],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_corridors,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",1094],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",184],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_variable,variable.normal,o_camera,"x",1094],
	[scr_cutscene_variable,variable.normal,o_camera,"y",198],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,1094,184],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,1094,201,false,1,true,true],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,1094,184],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
];
switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				#region
				quest_array=[
					[0,quest_type.talk_to,o_calina],
					[-1,quest_type.talk_to,o_edgar],
					[-1,quest_type.talk_to,o_grettel],
					[-1,quest_type.talk_to,o_tomas],
					[-1,quest_type.talk_to,o_fritz],
					[-1,quest_type.talk_to,o_nina],
					[-1,quest_type.talk_to,o_linus],
					[-1,quest_type.talk_to,o_james],
					[-1,quest_type.talk_to,o_wendy],
					[-1,quest_type.talk_to,o_larry],
					[-1,quest_type.talk_to,o_clara],
					[-1,quest_type.talk_to,o_hellen],
					[-1,quest_type.talk_to,o_eleanor],
					[-1,quest_type.talk_to,o_amanda],
					[-1,quest_type.talk_to,o_jeyjey],
					[-1,quest_type.talk_to,o_iriya],
					[-1,quest_type.talk_to,o_danya],
					[-1,quest_type.talk_to,o_darya],
					[-1,quest_type.talk_to,o_uncle_bruce],
					[-1,quest_type.talk_to,o_rubbert],
					[-1,quest_type.talk_to,o_petter],
					[-1,quest_type.talk_to,o_jill],
				];
				var i=0; repeat array_length(quest_array){
					non_complete_cutscene[i]=[
						[scr_cutscene_bars,true,true],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum..."]],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
						[scr_cutscene_wait,.1],
						[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
						[scr_cutscene_wait,.1],
						[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
						[scr_cutscene_wait,.1],
						[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ainda tenho que terminar de ver como todos estão"]],
						[scr_cutscene_wait,1],
						[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,false],
						[scr_cutscene_wait,1],
						[scr_cutscene_bars,true,false]
					];
					i++;
				}
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,x,y],
					[scr_cutscene_wait,1],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
					[scr_cutscene_set_event,[0,1,progress.complete],[0,2,progress.non_complete]],
					[scr_cutscene_room_goto,rm_corridors,true,false],
					[scr_cutscene_variable,variable.normal,o_camera,"x",1096],
					[scr_cutscene_variable,variable.normal,o_camera,"y",198],
					[scr_cutscene_variable,variable.normal,o_bunbun,"x",1096],
					[scr_cutscene_variable,variable.normal,o_bunbun,"y",198],
					[scr_cutscene_audio_play,audio_type.bgm,bgm_006,true,0,1],
					[scr_cutscene_instance_create,1096,270,"Instances_People_1",o_laszlo],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
					[scr_cutscene_instance_create,1083,224,"Instances_People_1",o_jasenska],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",270],
					[scr_cutscene_instance_create,1111,224,"Instances_People_1",o_julia],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
					[scr_cutscene_instance_create,1137,229,"Instances_People_1",o_ksenia],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
					[scr_cutscene_instance_create,1051,234,"Instances_People_1",o_lorie],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
					[scr_cutscene_instance_create,1159,246,"Instances_People_1",o_olivia],
					[scr_cutscene_variable,variable.normal,o_olivia,"direction",225],
					[scr_cutscene_instance_create,1026,253,"Instances_People_1",o_danica],
					[scr_cutscene_variable,variable.normal,o_danica,"direction",315],
					[scr_cutscene_instance_create,1143,270,"Instances_People_1",o_boris],
					[scr_cutscene_variable,variable.normal,o_boris,"direction",180],
					
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_laszlo,["Mas por que?!"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_jasenska,["Já te dissemos, por que não!"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_laszlo,["Mas isso é injusto!..."],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_julia,["Basta!"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
					//[scr_cutscene_circle_wake_up,true,false,1178,94,true,true,false,make_color_rgb(36,34,52)],
					[scr_cutscene_wait,2],
					[scr_cutscene_audio_play,audio_type.bgm,bgm_007,true,1,0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Você já sabe como as coisas funcionam!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Não e ponto!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Mas a Lorie e a Olivia também estão abaixo!... Por que não podemos também?!"]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Laszlo, deixe isso de lado!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Apenas reconheça seu posto na Hierarquia e vamos de uma vez!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Isso é mais do que simplesmente reconhecer meu posto na Hierarquia!"]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
					[scr_cutscene_variable,variable.normal,o_boris,"direction",135],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_danica,["Ah! É sobre o que então?!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_danica,["Essa atitude, esse motim!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_danica,["Você sabe que o seu interior não corrobora com os padrões de nossa sociedade!"]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",45],
					[scr_cutscene_variable,variable.normal,o_boris,"direction",90],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_olivia,["Não precisamos chegar a niveis extremos, Laszlo..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["N-Não!... Apenas.. Eu..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Apenas..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que está acontecendo?"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",315],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",0],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",45],
					[scr_cutscene_variable,variable.normal,o_danica,"direction",0],
					[scr_cutscene_variable,variable.normal,o_olivia,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",45],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
					[scr_cutscene_variable,variable.normal,o_danica,"direction",45],
					[scr_cutscene_variable,variable.normal,o_olivia,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",135],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Poupe-nos, BunBun, de seu filantropismo, por favor"]],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia, não seja rude!"]],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Peço perdão, porém não deixarei que um externo se intrometa nos assuntos da Hierarquia Rosa!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["B-Bom..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,["Laszlo quer brincar de esconde-esconde com a gente"]],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",0],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",180],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Lorie!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,["Eventualmente ele iria descobrir, Dama Julia"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Que atitude vil de sua parte!"]],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",315],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",315],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_olivia,["Ele quer brincar com a gente, porém ele não foi convidado"]],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",45],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",180],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,["Exatamente, Laszlo segue com essa teimosia"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["deixe isso de lado"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",270],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["BunBun, Laszlo não está convidado para brincar com a gente"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",315],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",45],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Porém você sim!"]],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Como?..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você sim está convidado"]],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Dama Jasenska, isso vai contra a legislação! Código dois da quarto Seguimento da Hierarquia Rosa!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Eu tenho ciência da norma, Dama Julia, porém gostaria de fazer essa exceção ao nosso convidado, BunBun!"]],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",225],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",225],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_danica,["Sim! O BunBun! Ele é completamente bem vindo!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,["A ideia me parece afável, de fato..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",315],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_olivia,["Ah! Sim! Vamos nessa!!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Ksenia, você também?"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Ai, tenha santa paciência..."]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",225],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",45],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",135],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",135],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Tudo bem, você tem todo o aval para se juntar a nós"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas eu nem disse se eu queria brincar ou não..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Uh!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Então você está dizendo que não vai brincar com a gente, né?"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu também não falei isso..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Na realidade, eu quero sim!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Perfeito!! Perfeito!!"]],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",135],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas... Com apenas uma condição"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Oh, diga"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Que o Laszlo possa jogar também"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Que"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Que"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Que"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_olivia,["Hein?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,["Como?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_danica,["Gente"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E que ele não sofra nenhuma punição por isso!..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Sem chance! Não vamos fazer isso!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Isso vai contra a legislação da Hierarquia Rosa!!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["De fato, não, Dama Jasenska?!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Dama Jasenska?..."]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Olha..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Não... Sem chance..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Sou a Dama de espinhos, estou aqui para proteger a senhora e a Hierarquia Rosa!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E se um externo ameaça a integridade física, social, estrutural e psicológica da nossa sociedade, meu dever é aniquilar o inimigo!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Dama Julia, eu sei qual é o seu papel, apenas..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Laszlo"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["AH!"]],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Código dois, terceiro Seguimento..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Vamos..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Uh..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["......."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Código dois, terceiro Seguimento da Hierarquia Rosa:\"Os membros das classes inferiores a da Classe de Pétala devem ser convidados a participar das atividades recreativas, qualquer meio de atrevimento resulta em punição\""]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Exato..."]],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Essas leis foram feitas com um propósito, e o propósito é manter a ordem e a paz!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E a senhora como Dama de Pétala e líder da Hierarquia Rosa, deveria respeitar essas leis impostas!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Por favor..."]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você tem razão, eu sou a líder... E como líder eu decreto que BunBun pode fazer parte da brincadeira..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Porém ele terá a ajuda de Laszlo..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Ambos os dois irão buscar pelos nós, ok?"]],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",270],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
					[scr_cutscene_variable,variable.normal,o_olivia,"direction",225],
					[scr_cutscene_variable,variable.normal,o_danica,"direction",315],
					[scr_cutscene_variable,variable.normal,o_boris,"direction",180],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Estamos entendidos, vocês dois?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sim, entendido"]],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",45],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",135],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",135],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",45],
					[scr_cutscene_variable,variable.normal,o_olivia,"direction",135],
					[scr_cutscene_variable,variable.normal,o_danica,"direction",45],
					[scr_cutscene_variable,variable.normal,o_boris,"direction",90],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Entendido?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim, entendido"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Perfeito..."]],
					[scr_cutscene_variable,variable.normal,o_jasenska,"direction",270],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
					[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
					[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
					[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
					[scr_cutscene_variable,variable.normal,o_olivia,"direction",225],
					[scr_cutscene_variable,variable.normal,o_danica,"direction",315],
					[scr_cutscene_variable,variable.normal,o_boris,"direction",180],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Laszlo e BunBun"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Vocês sabem os únicos locais permitidos a andar dentro de casa"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Ou seja, os únicos lugares que podemos nos esconder são no primeiro e no segundo andar"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["E por conta do que aconteceu aqui, agora..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Será válido se esconder em qualquer quarto dentro dos limites locias"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Mas"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Silêncio"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Vocês vão começar... Ok..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tudo bem..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Mas vocês não vão começar aqui... Venham conoco"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
					[scr_cutscene_audio_play,audio_type.bgm,bgm_007,true,0,1],
					[scr_cutscene_new_party_member,o_laszlo],
					[scr_cutscene_room_goto,rm_k_bedroom,false],
					[scr_cutscene_instance_layer,o_bunbun,"Instances_People_2"],
					[scr_cutscene_instance_layer,o_laszlo,"Instances_People_2"],
					[scr_cutscene_variable,variable.normal,o_bunbun,"x",708],
					[scr_cutscene_variable,variable.normal,o_bunbun,"y",440],
					[scr_cutscene_refresh_party_member,true],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
					[scr_cutscene_variable,variable.normal,o_laszlo,"x",732],
					[scr_cutscene_variable,variable.normal,o_laszlo,"y",440],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",0],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
					[scr_cutscene_variable,variable.normal,o_camera,"x",720],
					[scr_cutscene_variable,variable.normal,o_camera,"y",440],
					[scr_cutscene_instance_create,455,333,"Instances_People_2",o_danica],
					[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_idle_0],[s_danica_casual_hide_n_seek_idle_0],false,true,[1,1]],
					//[scr_cutscene_instance_create,425,330,"Instances_People_2",o_cutscene_trigger_3],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",7.625,425,330],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",2.125,425,330],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"complete_cutscene",
					//	[
					//		[scr_cutscene_bars,true,true],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_move_character,o_bunbun,436,366,false,1,true,true],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
					//		[scr_cutscene_move_character,o_laszlo,474,366,false,1,true,true],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_intro_2],[s_danica_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Finalmente!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_2],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Eu pensei que vocês tinham se esquecido de mim!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HaaHaa! Não, nunca esqueceremos de você!"]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Fomos idiotas por não ter pensado aí antes..."]],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Bom, são vocês quem estão dizendo! HeeHee!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Na próxima serei a última a ser encontrada!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Yay! É assim que se fala!!"]],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
					//		[scr_cutscene_variable,variable.normal,o_danica,"ppl_talked",o_danica],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_instance_destroy,o_danica],
					//		[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger_3],
					//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu não lembrava dela ser tão competitiva assim"]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah... É que você não convive tanto assim com ela"]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Me surpreende que ela não esteja planejando um golpe de estado para aplicar na Hierarquia Rosa"]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não que você saiba..."]],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Bom ponto"]],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_bars,true,false],
					//	],425,330],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_complete_cutscene",
					//	[[
					//		[scr_cutscene_bars,true,true],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_move_character,o_bunbun,436,366,false,1,true,true],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
					//		[scr_cutscene_move_character,o_laszlo,474,366,false,1,true,true],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_intro_1],[s_danica_casual_hide_n_seek_idle_1],false,true,[.35,.2]],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Te achamos!!"]],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Hump!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_idle_1]],false,false,[0,.2,.2]],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Não foi um bom esconderijo"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas foi uma boa tentativa!"]],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Deixe disso! Farei melhor na próxima!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Confio que você fará melhor!"]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Uh-hum!..."]],
					//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Hump!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_idle_1]],false,false,[0,.2,.2]],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_danica,"ppl_talked",o_danica],
					//		[scr_cutscene_instance_destroy,o_danica],
					//		[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger_3],
					//		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu gostei da ideia de se esconder justo aqui"]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Honestamente, me parecia bem previsível..."]],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Era mais um golpe de sorte do que qualquer coisa"]],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Parando para pensar, você tem razão"]],
					//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
					//		[scr_cutscene_wait,1],
					//		[scr_cutscene_bars,true,false],
					//	]],425,330],
					//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"quest_array",[[0,quest_type.talk_to,o_cutscene_trigger_1]],425,330],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,-1,["1... 2... 3..."],dag_001,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_wait,2],
					[scr_cutscene_circle_wake_up,true,false,718,440-16,true,true,true,make_color_rgb(36,34,52)],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,-1,["4... 5... 6..."],dag_001,(global.cw/3),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,-1,["7... 8... 9..."],dag_001,(global.cw/2)+(global.cw/6),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,-1,["10!!!"],dag_001,(global.cw/2),global.ch/3,150,make_color_rgb(36,34,52),true,true,false],
					[scr_cutscene_circle_wake_up,true,false,720,440-16,true,true,false,make_color_rgb(36,34,52)],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Prontos ou não..."]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",315],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Lá vamos nós!!!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Laszlo... Não fica assim, por favor!~"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eles não vão te punir, eles me prometeram..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Eu não preocupado com isso..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Eu não quero que a sua relação com eles fique manchada..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Você sabe como a Julia é..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, eu sei! E é por isso que eu vou pegar no pé dela, até ela te deixar em paz!"]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não é assim que as coisas funcionam, BunBun..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E nem da maneira como a Julia ou a Jasenska dizem que tem que ser!"]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Laszlo... Eu entendo que a Hierarquia Rosa tem suas leis"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu mesmo já passei por ela!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ainda mais quando era a Wendy como Dama de Pétala"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["O Tomas?..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim! A Wendy como Dama de pétalas e o Tomas como Amo de Espinhos..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Me atrevo a dizer que ele ganhou esse posto contra a vontade da Wendy, mesmo que ele tenha merecido"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Como assim?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee!... Isso é segredo, ok?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ok!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... Antigamente, A Wendy queria que quem fosse eu Amo de Espinhos fosse o Nickolai, mas quem ganhou a disputa foi o Tomas"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Oh! Sério?!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas apesar disso, os dois começaram a se dar super bem!"]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Que legal!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim!! Por isso que eu digo que é sempre bom fazer algumas mudanças"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tudo bem as coisas não saírem do jeito como esperado, ou como determinado!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Apenas vamos aproveitar o momento, ok?!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Acho que sim..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vamos buscar por todos estão?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sim, vamos lá..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Perfeito! Vamos!!"]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_instance_create,720,440,"Instances_Config",o_hide_n_seek]
				]
			#endregion
			}else if(global.event[0][5]==progress.non_complete){
				non_avaliable_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,x,y],
					[scr_cutscene_wait,1],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
					[scr_cutscene_room_goto,rm_corridors,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"x",1094],
					[scr_cutscene_variable,variable.normal,o_bunbun,"y",184],
					[scr_cutscene_instance_create,0,0,"Instances_People_1",o_petter],
					[scr_cutscene_variable,variable.normal,o_petter,"ppl_act_state",ppl_act.flow],
					[scr_cutscene_variable,variable.normal,o_petter,"pos",24],
					[scr_cutscene_variable,variable.normal,o_petter,"persistent",true],
					[scr_cutscene_refresh_party_member,true],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
					[scr_cutscene_variable,variable.normal,o_camera,"x",1094],
					[scr_cutscene_variable,variable.normal,o_camera,"y",198],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,1094,184],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,1094,201,false,1,true,true],
					[scr_cutscene_refresh_party_member,false],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,1094,184],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false]
				];
			}
			#endregion
			
			break;
}