function scr_talk_oliver(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][2]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_oliver]
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_oliver,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,492,547,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
					[scr_cutscene_move_character,o_laszlo,511,560,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá 46!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["O que está fazendo, 46?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Ah! Eu?..."],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Apenas estou praticando morse..."],-1,[-1,[s_oliver_casual_chill_1_idle_1],[s_oliver_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Morse?!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
					[scr_cutscene_animation_sprite,o_laszlo,[s_laszlo_casual_joy_intro],[s_laszlo_casual_joy_idle],false,true,[.35,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_laszlo,["Ah! Sério?! O que aprendeu de novo?"],-1,[-1,[s_laszlo_casual_joy_idle],[s_laszlo_casual_joy_talk]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Ah, nada de mais, na realidade..."],-1,[-1,[s_oliver_casual_chill_1_idle_1],[s_oliver_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Ainda estou decorando alguns sinais..."],-1,[-1,[s_oliver_casual_chill_1_idle_1],[s_oliver_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Mas pelo o que eu noto, os sinais mais simples são os mais usados"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Como A, E, T..."],-1,[-1,[s_oliver_casual_chill_1_idle_1],[s_oliver_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Isso é impressionante!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sabe alguma mesagem codificada?"]],
					[scr_cutscene_animation_sprite,o_laszlo,[s_laszlo_casual_joy_end],[s_laszlo_casual_idle_1_down],false,true,[.35,.2]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_act_state",ppl_act.flow],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sim sim! Fale para a gente!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Hum... Sim, na realidade sim..."],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Deixe-me ver..."],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_0],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_oliver,["Hum....."]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Doot dot dot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Dot dot doot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Doot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Doot dot dot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Dot dot doot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Doot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_0],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Dot doot dot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Dot doot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Dot dot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Doot doot dot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Dot doot dot dot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Doot doot doot"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Pronto"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! E o que seria isso que tu disse?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["O nome de vocês"],-1,[-1,[s_oliver_casual_chill_1_idle_1],[s_oliver_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah! Sério?!!"]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_4],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Isso é tão legal!!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Ah, não é grande coisa, por favor!"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
					[scr_cutscene_animation_sprite,o_laszlo,[s_laszlo_casual_joy_intro],[s_laszlo_casual_joy_idle],false,true,[.35,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_laszlo,["Claro que é! isso é muito legal!!"],-1,[-1,[s_laszlo_casual_joy_idle],[s_laszlo_casual_joy_talk]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_laszlo,["Você tem 2 anos e sabe código morse!!"],-1,[-1,[s_laszlo_casual_joy_idle],[s_laszlo_casual_joy_talk]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Laszlo tem razão, 46, isso é incrivel!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Bom, acho que sim"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Mas me deixa feliz que vocês tenham gostado"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Espero que você se torne alguém grandioso quando crescer, 46!!"]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_4],
					[scr_cutscene_animation_sprite,o_laszlo,[s_laszlo_casual_joy_end],[s_laszlo_casual_idle_1_down],false,true,[.35,.2]],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_act_state",ppl_act.flow],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sim sim! O 46 tem um dos maiores cérebros daqui da casa!!"]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Espera..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["46, quantos cérebros você tem?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Bom, acho que apenas um..."],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Hum... Tudo bem, mas ele deve ser bem grande, para caber tanta informação, né?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Ah... Ele apenas encaixa"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah! Menos mal então!!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom, a gente vai terminar de brincar, mais tarde voltamos para falar contigo"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Claro! Divirtam-se!!"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Se vocês quiserem qualquer outra coisa, estarei aqui, ok?"],-1,[-1,[s_oliver_casual_chill_1_idle_4],[s_oliver_casual_chill_1_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_0],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,492,547,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
					[scr_cutscene_move_character,o_laszlo,511,560,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_4],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá, 46, continua com os códigos?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Sim, continuo com os códigos"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["E os cérebros?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Continuam aqui dentro"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_4],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Bom se precisar de ajuda com isso, estou aqui"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Você se refere ao cérebro ou ao código morse?"],-1,[-1,[s_oliver_casual_chill_1_idle_1],[s_oliver_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Os dois"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Faz sentido"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_4],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom, se cuida, 46!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Vocês também!"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_0],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				]
			}else if(global.event[0][3]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_oliver]
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,492,547,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
					[scr_cutscene_move_character,o_todd,511,560,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E ai, 46'zinho!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oi 46!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Ah! Oi Todd, oi BunBun"],-1,[-1,[s_oliver_casual_chill_1_idle_1],[s_oliver_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Está tudo bem?"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Sim sim, apenas um pouco cansado"],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Cansado do que? O dia mal começou!"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Ah! Não é nada demais!"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Apenas estou desenhando para descansar um pouco"],-1,[-1,[s_oliver_casual_chill_1_idle_4],[s_oliver_casual_chill_1_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Apenas estou cansado de estudar, então decidi não fazer nada por um tempo..."],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Entendo... Não se esforce tanto"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Reconheça seus limites e descanse sempre que necessário, ok?"]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_2],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Acho que sim... Talvez..."],-1,[-1,[s_oliver_casual_chill_1_idle_2],[s_oliver_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
					[scr_cutscene_wait,.5],
					[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_catchphrase_intro],[s_todd_casual_catchphrase_idle],false,true,[.35,.2]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Qual é, 46'zinho!"],-1,[-1,[s_todd_casual_catchphrase_idle],[s_todd_casual_catchphrase_talk]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Se tu quiser, pode andar com a gente"],-1,[-1,[s_todd_casual_catchphrase_idle],[s_todd_casual_catchphrase_talk]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["As vezes o que falta para a gente é um pouco de movimento!"],-1,[-1,[s_todd_casual_catchphrase_idle],[s_todd_casual_catchphrase_talk]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["HeeHee, acredito em ti"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Acredito em ti, mas passo dessa vez, obrigado, Todd!"],-1,[-1,[s_oliver_casual_chill_1_idle_4],[s_oliver_casual_chill_1_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_3],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bom, você quem sabe"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_catchphrase_end],[s_todd_casual_idle_1_down],false,true,[.35,.2]],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
					[scr_cutscene_wait,.1],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_4],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu e o BunBun estaremos zanzando por ai, se precisar é só chamar"]],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bora, BunBun?"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Claro, claro"]],
					[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se cuida, Laszlo"]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_oliver,["Vocês também, divirtam-se"],-1,[-1,[s_oliver_casual_chill_1_idle_3],[s_oliver_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
					[scr_cutscene_variable,variable.normal,o_oliver,"sprite_index",s_oliver_casual_chill_1_idle_0],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				]
			}
			#endregion
			break;
	}
}