//============================================================
//config the camera and debug mode
//============================================================
#region
if(keyboard_check_pressed(vk_f1)){debbug_mode=!debbug_mode;}
if(debbug_mode){
//cunt
}
show_debug_overlay(debbug_mode);
//instance_deactivate_all(true);
//instance_activate_region(global.cx,global.cy,global.cw,global.ch,true);
//instance_activate_object(o_camera);
//instance_activate_object(o_graphic);
//instance_activate_object(o_cutscene);
//if(global.player!=-1) instance_activate_object(global.player);
//============================================================
camera_set_view_size(view_camera[0],global.cw,global.ch);

if(flow_npc){
	if(npc_to_flow!=-1)and(instance_exists(npc_to_flow)){
		x=lerp(x,npc_to_flow.x,.05);
		y=lerp(y,npc_to_flow.y,.05);
	}
}

var xx,yy;
if(shake_permit){
	xx=random_range(-shake_power,shake_power);
	yy=random_range(-shake_power,shake_power);
}else{
	xx=0;
	yy=0;
}

var x1=((o_camera.x-global.cw/2)+xx);
var y1=((o_camera.y-global.ch/2)+yy);
x1=clamp(x1,0,room_width-global.cw);
y1=clamp(y1,0,room_height-global.ch);
camera_set_view_pos(view_camera[0],x1,y1);
global.cx=camera_get_view_x(view_camera[0]);
global.cy=camera_get_view_y(view_camera[0]);
timer++;
if(timer>.5*60){
	if(ww!=window_get_width())and(wh!=window_get_height()){
		global.window_change=true;
		event_perform(ev_other,ev_user0);
	}else{
		global.window_change=false;
		timer=0;
	}
}
#endregion
//============================================================
//setting the audio
//============================================================
#region
if(!window_has_focus()){
	audio_pause_all()
}else{
	audio_master_gain(global.volume_master);
	if(audio_group_is_loaded(audio_BGM)){audio_group_set_gain(audio_BGM,global.volume_master*global.volume_bgm,0);}else{audio_group_load(audio_BGM);}
	if(audio_group_is_loaded(audio_BGS)){audio_group_set_gain(audio_BGS,global.volume_master*global.volume_bgs,0);}else{audio_group_load(audio_BGS);}
	if(audio_group_is_loaded(audio_SFX)){audio_group_set_gain(audio_SFX,global.volume_master*global.volume_sfx,0);}else{audio_group_load(audio_SFX);}
	audio_resume_all();
}
#endregion
//============================================================
//creating the main menu
//============================================================
#region
//if(!instance_exists(o_audio)){
//	instance_create_layer(x,y,layer,o_audio);
//}
if(!instance_exists(o_main_menu))and((!global.game_start)and(!global.game_load)and(!global.game_end)){
	instance_create_layer(x,y,layer,o_main_menu);
}
//if(keyboard_check_pressed(ord("M"))){
//	instance_create_layer(x,y,"Instances_Config",o_mini_game);
//	show_debug_message("Instancia criada");
//	}
//if(instance_exists(o_mini_game)) show_debug_message("Minigame");
#endregion
//============================================================
//pause the game
//============================================================
#region
if(can_pause)and(!instance_exists(o_meal)){
	scr_inputs();
	if(global.input_pause) global.pause=!global.pause;
	if(global.pause)and(!instance_exists(o_pause)){
		instance_create_layer(x,y,layer,o_pause);
	}
}
#endregion
//============================================================
//jumping to scenes
//============================================================
var _t_cutscene=-1;
if(keyboard_check_pressed(ord("0"))){
	_t_cutscene=[
		[scr_cutscene_instance_create,global.player.x,global.player.y,global.player.layer,o_quick_time],
	]
	//instance_create_layer(x,y,layer,o_papers);
}
if(keyboard_check_pressed(ord("1"))){
	_t_cutscene=[
		[scr_cutscene_refresh_party_member,true],
		[scr_cutscene_audio_stop,audio_type.bgm,bgm_004],
		[scr_cutscene_audio_stop,audio_type.bgm,bgm_002],
		[scr_cutscene_audio_play,audio_type.bgm,bgm_006,true,1,0],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.non_complete]],
		[scr_cutscene_room_goto,rm_house_ext_back,false,true],
		[scr_cutscene_variable,variable.normal,o_camera,"x",1496],
		[scr_cutscene_variable,variable.normal,o_camera,"y",492],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",492],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",1496],
		[scr_cutscene_instance_layer,o_bunbun,"Instances_People_1"],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
		[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_instance_create,1105,1668,"Instances_People_1",o_uncle_bruce],
		[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_playground_idle_1_1],[s_uncle_bruce_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1128,1665,"Instances_People_1",o_rubbert],
		[scr_cutscene_animation_sprite,o_rubbert,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1013,1676,"Instances_People_1",o_linus],
		[scr_cutscene_animation_sprite,o_linus,[s_linus_casual_playground_idle_1_1],[s_linus_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,992,1683,"Instances_People_1",o_james],
		[scr_cutscene_animation_sprite,o_james,[s_james_casual_playground_talk_1_1],[s_james_casual_playground_talk_1_1],false,true,[3,.25]],
		[scr_cutscene_instance_create,1197,1681,"Instances_People_1",o_larry],
		[scr_cutscene_animation_sprite,o_larry,[s_larry_casual_playground_idle_1_1],[s_larry_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1226,1692,"Instances_People_1",o_clara],
		[scr_cutscene_animation_sprite,o_clara,[s_clara_casual_playground_idle_1_1],[s_clara_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,955,1737,"Instances_People_1",o_wendy],
		[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_playground_idle_1_1],[s_wendy_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,870,1766,"Instances_People_1",o_nina],
		[scr_cutscene_animation_sprite,o_nina,[s_nina_casual_playground_idle_1_0],[s_nina_casual_playground_idle_1_0],false,true,[3,.2]],
		[scr_cutscene_instance_create,578,1762,"Instances_People_1",o_tomas],
		[scr_cutscene_animation_sprite,o_tomas,[s_tomas_casual_playground_idle_1_1],[s_tomas_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,291,1851,"Instances_People_1",o_fritz],
		[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_playground_talk_1_1],[s_fritz_casual_playground_talk_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,326,1677,"Instances_People_1",o_edgar],
		[scr_cutscene_animation_sprite,o_edgar,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,297,1584,"Instances_People_1",o_grettel],
		[scr_cutscene_animation_sprite,o_grettel,[s_grettel_casual_playground_idle_1_1],[s_grettel_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,522,1532,"Instances_People_1",o_calina],
		[scr_cutscene_animation_sprite,o_calina,[s_calina_casual_playground_idle_1_1],[s_calina_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1482,1783,"Instances_People_1",o_amanda],
		[scr_cutscene_variable,variable.normal,o_amanda,"direction",90],
		[scr_cutscene_instance_create,1503,1550,"Instances_People_1",o_iriya],
		[scr_cutscene_animation_sprite,o_iriya,[s_iriya_casual_playground_idle_1_1],[s_iriya_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1688,1491,"Instances_People_1",o_jeyjey],
		[scr_cutscene_animation_sprite,o_jeyjey,[s_jeyjey_casual_playground_idle_1_1],[s_jeyjey_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1757,1670,"Instances_People_1",o_hellen],
		[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_playground_idle_1_1],[s_hellen_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1786,1672,"Instances_People_1",o_eleanor],
		[scr_cutscene_animation_sprite,o_eleanor,[s_eleanor_casual_playground_talk_1_1],[s_eleanor_casual_playground_talk_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1790,1431,"Instances_People_1",o_danya],
		[scr_cutscene_animation_sprite,o_danya,[s_danya_casual_playground_idle_1_1],[s_danya_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,1813,1431,"Instances_People_1",o_darya],
		[scr_cutscene_animation_sprite,o_darya,[s_darya_casual_playground_idle_1_1],[s_darya_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,2077,1341,"Instances_People_1",o_jill],
		[scr_cutscene_animation_sprite,o_jill,[s_jill_casual_playground_idle_1_1],[s_jill_casual_playground_idle_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,2102,1351,"Instances_People_1",o_petter],
		[scr_cutscene_animation_sprite,o_petter,[s_petter_casual_playground_idletalk_1_1],[s_petter_casual_playground_idletalk_1_1],false,true,[3,.2]],
		[scr_cutscene_instance_create,2102,1351,"Instances_People_1",o_todd],
		[scr_cutscene_block_create,314,1635.5,"Instances_Block_1",o_block_1,3.125,4.6875],
		[scr_cutscene_remove_party_member,o_todd],
		[scr_cutscene_instance_create,2102,1351,"Instances_People_1",o_nickolai],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
		[scr_cutscene_set_path,o_todd,p_playground_day_1_1,1.5,path_action_restart,true],
		[scr_cutscene_set_path,o_nickolai,p_playground_day_1_2,1.5,path_action_restart,true],
	];
}
if(keyboard_check_pressed(ord("2"))){
	_t_cutscene=[
		[scr_cutscene_remove_party_member,o_todd],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.non_complete]],
		[scr_cutscene_set_event,[0,1,progress.complete],[0,2,progress.non_complete]],
		[scr_cutscene_room_goto,rm_k_bedroom,false,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",720],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",440],
		[scr_cutscene_variable,variable.normal,o_camera,"x",720],
		[scr_cutscene_variable,variable.normal,o_camera,"y",440],
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_instance_create,720,440,"Instances_People_2",o_laszlo],
		[scr_cutscene_new_party_member,o_laszlo],
		[scr_cutscene_instance_create,720,440,"Instances_Config",o_hide_n_seek],
		[scr_cutscene_instance_create,455,333,"Instances_People_2",o_danica],
		[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_idle_0],[s_danica_casual_hide_n_seek_idle_0],false,true,[1,1]],
		[scr_cutscene_instance_create,425,330,"Instances_People_2",o_cutscene_trigger_3],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",7.625,425,330],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",2.125,425,330],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"complete_cutscene",
			[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,436,366,false,1,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
				[scr_cutscene_move_character,o_laszlo,474,366,false,1,true,false],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_intro_2],[s_danica_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Finalmente!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_2],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Eu pensei que vocês tinham se esquecido de mim!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HaaHaa! Não, nunca esqueceremos de você!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Fomos idiotas por não ter pensado aí antes..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Bom, são vocês quem estão dizendo! HeeHee!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Na próxima serei a última a ser encontrada!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_3],[s_danica_casual_hide_n_seek_talk_2]],false,false,[0,.2,.2]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Yay! É assim que se fala!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_variable,variable.normal,o_danica,"ppl_talked",o_danica],
				[scr_cutscene_wait,1],
				[scr_cutscene_instance_destroy,o_danica],
				[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger_3],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu não lembrava dela ser tão competitiva assim"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah... É que você não convive tanto assim com ela"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Me surpreende que ela não esteja planejando um golpe de estado para aplicar na Hierarquia Rosa"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não que você saiba..."]],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Bom ponto"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			],425,330],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_complete_cutscene",
			[[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,436,366,false,1,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
				[scr_cutscene_move_character,o_laszlo,474,366,false,1,true,false],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_danica,[s_danica_casual_hide_n_seek_intro_1],[s_danica_casual_hide_n_seek_idle_1],false,true,[.35,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Te achamos!!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Hump!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_idle_1]],false,false,[0,.2,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Não foi um bom esconderijo"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas foi uma boa tentativa!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Deixe disso! Farei melhor na próxima!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_talk_1]],false,false,[0,.2,.2]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Confio que você fará melhor!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Uh-hum!..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_danica,["Hump!!"],-1,[[-1],[s_danica_casual_hide_n_seek_idle_1],[s_danica_casual_hide_n_seek_idle_1]],false,false,[0,.2,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_danica,"ppl_talked",o_danica],
				[scr_cutscene_instance_destroy,o_danica],
				[scr_cutscene_instance_destroy_nearst,x,y,o_cutscene_trigger_3],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu gostei da ideia de se esconder justo aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Honestamente, me parecia bem previsível..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Era mais um golpe de sorte do que qualquer coisa"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Parando para pensar, você tem razão"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]],425,330],
		[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"quest_array",[[0,quest_type.talk_to,o_cutscene_trigger_1]],425,330],
	];
	
}
if(keyboard_check_pressed(ord("3"))){
	_t_cutscene=[
		[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,1,1],
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.non_complete]],
		[scr_cutscene_room_goto,rm_corridors,false,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",605],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",618],
		[scr_cutscene_variable,variable.normal,o_camera,"x",605],
		[scr_cutscene_variable,variable.normal,o_camera,"y",618],
		[scr_cutscene_instance_layer,o_bunbun,"Instances_People_1"],
		[scr_cutscene_instance_layer,o_todd,"Instances_People_1"],
		//[scr_cutscene_item,o_bunbun,-1,[item.mother_list,1],true,false],
		//[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["-1"]],
		//[scr_cutscene_item,o_bunbun,-1,[item.irrigator,1],true,false],
		//[scr_cutscene_wait,1],
		//[scr_cutscene_item,o_bunbun,item.irrigator,[-1,-1],true,true],
		[scr_cutscene_refresh_party_member,true],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
	]
}
if(keyboard_check_pressed(ord("4"))){
	_t_cutscene=[
		[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,1,1],
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,4,progress.non_complete]],
		[scr_cutscene_room_goto,rm_corridors,false,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",605],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",618],
		[scr_cutscene_variable,variable.normal,o_camera,"x",605],
		[scr_cutscene_variable,variable.normal,o_camera,"y",618],
		[scr_cutscene_set_children],
		[scr_cutscene_new_party_member,o_hellen],
		[scr_cutscene_refresh_party_member,true],
		[scr_cutscene_instance_create,605,618,"Instances_People_1",o_hellen],
		[scr_cutscene_instance_layer,o_bunbun,"Instances_People_1"],
		[scr_cutscene_instance_layer,o_todd,"Instances_People_1"],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
		[scr_cutscene_instance_create,420,557,"Instances_People_1",o_cutscene_trigger_2],
		[scr_cutscene_variable,variable.normal,o_cutscene_trigger_2,"image_xscale",1.125],
		[scr_cutscene_variable,variable.normal,o_cutscene_trigger_2,"image_yscale",5.625],
		[scr_cutscene_variable,variable.normal,o_cutscene_trigger_2,"non_avaliable_cutscene",
			[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_hellen],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_hellen],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... Bom... Garotos..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Acho... Acho que eu consigo daqui para frente..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh, você tem certeza, Hellen?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Sim... Acho que sim"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Quer que a gente fique em algum lugar para te dar suporte ou algo do tipo?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom... Se quiserem ficar lá em cima, tudo bem"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sem problemas! Vamos ficar caladinhos, te dando suporte"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim! Estaremos te desejando o melhor"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Obrigado, garotos!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_instance_create,357,470,"Instances_People_2",o_wendy],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				[scr_cutscene_move_character,o_bunbun,503,574,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,503,532,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,464,532,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,432,502,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,384,502,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,384,411,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,304,411,false,1,true,true],
				[scr_cutscene_move_character,o_bunbun,304,466,false,1,true,true],
				//[scr_cutscene_move_character,o_bunbun,304,502,false,1,true,true],
					
				//[scr_cutscene_move_character,o_bunbun,304,413,false,1,true,true],
					
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_move_character,o_todd,-24,0,true,1,true,true],
				[scr_cutscene_move_character,o_todd,0,24,true,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Wendy?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Sim?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nada, apenas não esperava por você aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Bom... Eu ajudei ela também, não?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["De fato sim!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Bom, ficarei aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro que você pode ficar"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Não foi uma pergunta, eu ficarei aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh, desculpe-"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Desculpe também"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd..."]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Desculpe..."]],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bobo"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_player",false],
				[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_layer",1],
				[scr_cutscene_move_character,o_camera,288,619,false,1,false,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Uff... Vamos Hellen..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Você consegue!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Você consegue! Você consegue!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_hellen,423,582,false,1,true,true],
				[scr_cutscene_move_character,o_hellen,323,619,false,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... Fritz!..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Ah! Olá, Hellen!"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Deseja algo?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu... Eu queria saber o que você está lendo, na realidade"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Oh! Isso? Bom..."],-1,[[-1],[s_fritz_casual_loveletter_idle_5],[s_fritz_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["É um romance, na realidade"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Um romance? Nunca imaginei você lendo romance"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Sei que você conhece o movimento romancista"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Mas consumir... Isso é inovador, na realidade"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Bom, sim, na realidade, é um livro tragediano, que conta a história de um romance"],-1,[[-1],[s_fritz_casual_loveletter_idle_5],[s_fritz_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Mas não se deixe enganar pelas tragédias, o amor empregado nesse livro é realmente bom e lindo"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Você gosta de livros romancistas, não?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom, sim, eu gosto, apesar de preferir os mais didáticos"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Como está acontecendo uma guerra aos exteriores dessa casa, eu prefiro consumir coisas mais positivas... Entende?"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Eu entendo... Apesar de que eu prefira ler os poemas daqueles que estavam na guerra, ler seus pensamentos e memórias em estrofes é uma experiência"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu... Nunca li esses poemas... Você poderia... Me mostrar alguns?"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Para ti? Com todo o prazer, Hellen!..."],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Mas..."],-1,[[-1],[s_fritz_casual_loveletter_idle_5],[s_fritz_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Posso te fazer uma pergunta?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Claro, o que quiser"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_loveletter_look_1],[s_fritz_casual_loveletter_idle_5],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Você veio apenas para falar do meu livro, certo?..."],-1,[[-1],[s_fritz_casual_loveletter_idle_5],[s_fritz_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Na realidade..."]],
				[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_loveletter_look_2],[s_fritz_casual_loveletter_idle_look_2],false,true,[.3,.2]],
				[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_loveletter_getting_up],[s_fritz_casual_idle_1_down],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_confess_idle_1_down],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_confess_idle_1_downright],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_confess_idle_1_right],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Eu vi que você estava andando para cima e para baixo com o BunBun e com o Todd, tem algo errado?"],-1,[[-1],[s_fritz_casual_confess_idle_1_right],[s_fritz_casual_confess_talk_1_right]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Tem algo te incomodando?"],-1,[[-1],[s_fritz_casual_confess_idle_1_right],[s_fritz_casual_confess_talk_1_right]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah! Não não..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eles estavam apenas me ajudando"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Ajudando? Hellen... Está tudo bem de verdade?"],-1,[[-1],[s_fritz_casual_confess_idle_1_right],[s_fritz_casual_confess_talk_1_right]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Fritz... Eles só estavam... Me ajudando..."]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_1],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_1],[s_hellen_casual_confession_both_idle_1_1],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_1_2],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_1],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Com isso..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_1],[s_hellen_casual_loveletter_confession_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Oh!... Um livro?"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_1],[s_fritz_casual_loveletter_confession_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Pega, é para você"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_1],[s_hellen_casual_loveletter_confession_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_1_1],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_2],[s_hellen_casual_confession_both_idle_2],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_3],[s_hellen_casual_confession_both_idle_3],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_2],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_3],
				[scr_cutscene_instance_create,328,465,"Instances_People_2",o_nickolai],
				[scr_cutscene_instance_create,256,470,"Instances_People_2",o_rubbert],
				[scr_cutscene_instance_create,333,473,"Instances_People_2",o_clara],
				[scr_cutscene_instance_create,295,457,"Instances_People_2",o_nina],
				[scr_cutscene_instance_create,260,456,"Instances_People_2",o_amanda],
				[scr_cutscene_instance_create,383,457,"Instances_People_2",o_eleanor],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Um livro..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_2],[s_fritz_casual_loveletter_confession_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["É para você..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_3],[s_hellen_casual_loveletter_confession_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Pedi ajuda para eles para me ajudar a buscar um livro que você ainda não leu..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_4],[s_hellen_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_3],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Um livro?... Que ainda não li..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_2],[s_fritz_casual_loveletter_confession_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Isso é tão doce, Hellen!"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_2],[s_fritz_casual_loveletter_confession_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Você é tão atenta!"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_2],[s_fritz_casual_loveletter_confession_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_3],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_4],[s_hellen_casual_confession_both_idle_4],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_3],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_4],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Uma carta? Isso estava aqui antes?"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_3],[s_fritz_casual_loveletter_confession_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Eu coloquei"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_4],[s_hellen_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_4],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_5],[s_hellen_casual_confession_both_idle_5],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_4],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_3],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["A carta é sua?"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_4],[s_fritz_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Sim..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_4],[s_hellen_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Ela... É linda, Hellen"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_4],[s_fritz_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você...!"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_4],[s_hellen_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você... Você realmente gostou?"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_3],[s_hellen_casual_loveletter_confession_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["É tudo isso o que você sente?"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_4],[s_fritz_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Sim... Cada palavra..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_4],[s_hellen_casual_loveletter_confession_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_5],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_6],[s_hellen_casual_confession_both_idle_6],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_5],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_5],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Aqui, para você"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_5],[s_fritz_casual_loveletter_confession_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Espera... Você... Você também?..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_5],[s_hellen_casual_loveletter_confession_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Sim..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_5],[s_fritz_casual_loveletter_confession_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_6],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_7],[s_hellen_casual_confession_both_idle_7],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_6],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_6],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Para você"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_6],[s_fritz_casual_loveletter_confession_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_7],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_8],[s_hellen_casual_confession_both_idle_8],false,true,[.3,.2]],
				[scr_cutscene_wait,2],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_9],[s_hellen_casual_confession_both_idle_7],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_6],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_6],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["F-Frtiz... Isso... É tão lindo!!!"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_6],[s_hellen_casual_loveletter_confession_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Hellen... Isso é apenas a verdade sobre o que sinto"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_6],[s_fritz_casual_loveletter_confession_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Sobre o que eu sempre senti, na realidade"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_7],[s_fritz_casual_loveletter_confession_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_7],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_10],[s_hellen_casual_confession_both_idle_10],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_11],[s_hellen_casual_confession_both_idle_11],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_8],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_5],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Frtiz..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_5],[s_hellen_casual_loveletter_confession_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Hellen..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_8],[s_fritz_casual_loveletter_confession_talk_8]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_11],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_12],[s_hellen_casual_confession_both_idle_12],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_9],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_8],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Frtiz..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_8],[s_hellen_casual_loveletter_confession_talk_8]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Hellen..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_9],[s_fritz_casual_loveletter_confession_talk_9]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Shhh!"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
				[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_todd,["Shhh você!"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_12],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_13],[s_hellen_casual_confession_both_idle_13],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_player",true],
				[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_layer",2],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				[scr_cutscene_variable,variable.normal,o_fritz,"direction",45],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_fritz,"direction",90],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Ignora a gente"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Exato, não estamos aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_eleanor,["Ajam normalmente"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["A culpa é do Nickolai..."]],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",225],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["O QUE?! POR QUE?!"]],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",315],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",0],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				[scr_cutscene_variable,variable.normal,o_nina,"direction",315],
				[scr_cutscene_variable,variable.normal,o_eleanor,"direction",225],
				[scr_cutscene_variable,variable.normal,o_wendy,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Apenas fiquem quietos de uma vez, por favor!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Wendy está certa, deixem eles terminarem!"]],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",270],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",270],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",270],
				[scr_cutscene_variable,variable.normal,o_nina,"direction",270],
				[scr_cutscene_variable,variable.normal,o_eleanor,"direction",270],
				[scr_cutscene_variable,variable.normal,o_wendy,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Ignora a gente"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu..."]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_13],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_14],[s_hellen_casual_confession_both_idle_15],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_10],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_9],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Eu... Eu não sabia disso..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_9],[s_hellen_casual_loveletter_confession_talk_9]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Fritz, eu não sabia que eles estavam vendo, me desculpe!"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_11],[s_hellen_casual_loveletter_confession_talk_11]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Hellen!"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_10],[s_fritz_casual_loveletter_confession_talk_10]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_9],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Deixem que eles vejam"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_11],[s_fritz_casual_loveletter_confession_talk_11]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Ui, meu Deus-"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["A existência deles, no NOSSO mundo, não importa"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_11],[s_fritz_casual_loveletter_confession_talk_11]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Ai... Me machucou..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Hellen, eu queria..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_10],[s_fritz_casual_loveletter_confession_talk_10]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Ai, é agora!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Eu queria dizer..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_10],[s_fritz_casual_loveletter_confession_talk_10]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ele vai falar, ele vai falar!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Dizer que..."],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_11],[s_fritz_casual_loveletter_confession_talk_11]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Minha nossa, isso é tão romântico!"]],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_12],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_13],[s_hellen_casual_confession_both_idle_13],false,true,[.3,.2]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["VOCÊS PODEM, POR FAVOR, CALAREM A BOCA?!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Aff, que mal educado"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["É a internet de hoje em dia"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que é internet"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sei lá, acabei de criar essa palavra"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["É uma boa palavra"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ah! Valeu BunBun!"]],
				[scr_cutscene_variable,variable.normal,o_wendy,"direction",180],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",315],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",0],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				[scr_cutscene_variable,variable.normal,o_nina,"direction",315],
				[scr_cutscene_variable,variable.normal,o_eleanor,"direction",225],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Seguinte, ou vocês ficam quietos, eu vou fazer questão de fazer cada um se arrepender de ter vindo para cá..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",270],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",270],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",270],
				[scr_cutscene_variable,variable.normal,o_nina,"direction",270],
				[scr_cutscene_variable,variable.normal,o_eleanor,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_wendy,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Desculpem, podem continuar"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Tá..."]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_13],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_14],[s_hellen_casual_confession_both_idle_15],false,true,[.3,.2]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_10],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_confession_idle_9],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Eu queria dizer que eu te amo, Hellen"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_10],[s_fritz_casual_loveletter_confession_talk_10]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Que esse sentimento que você expressou nessa carta, é reciproco"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_11],[s_fritz_casual_loveletter_confession_talk_11]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Fritz!!"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_9],[s_hellen_casual_loveletter_confession_idle_9]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_confession_idle_9],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Frtiz!... Isso... É tão lindo!!"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_10],[s_hellen_casual_loveletter_confession_talk_10]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Eu... Eu quero que você fique com esse livro, se possível..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_8],[s_hellen_casual_loveletter_confession_talk_8]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Logo logo é o seu aniversário e não sei qual será a próxima vez que iremos nos ver depois desse dia"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_8],[s_hellen_casual_loveletter_confession_talk_8]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Uma confissão e uma despedida?"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_11],[s_fritz_casual_loveletter_confession_talk_11]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Desculpe... Eu apenas tomei coragem hoje..."],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_8],[s_hellen_casual_loveletter_confession_talk_8]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Antes tarde do que nunca, minha querida Hellen"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_9],[s_fritz_casual_loveletter_confession_talk_9]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Oh, Fritz!... Eu te amo tanto"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_8],[s_hellen_casual_loveletter_confession_talk_8]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["E te amo igualmente, Hellen"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_9],[s_fritz_casual_loveletter_confession_talk_9]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Sou o ser mais sortudo por te ter em minha vida"],-1,[[-1],[s_fritz_casual_loveletter_confession_idle_9],[s_fritz_casual_loveletter_confession_talk_9]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Somos sortudos por termos um ao outro"],-1,[[-1],[s_hellen_casual_loveletter_confession_idle_8],[s_hellen_casual_loveletter_confession_talk_8]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_12],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_15],[s_hellen_casual_confession_both_idle_14],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Todd! BunBun! Muito obrigada pela ajuda"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_confession_both_idle_14],
				[scr_cutscene_variable,variable.normal,o_hellen,"image_index",0],
				[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_nothing],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_16],[s_hellen_casual_confession_both_idle_12],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_confession_17],[s_hellen_casual_confession_both_idle_16],false,true,[.3,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Que evento tão lindo! Isso é tão romântico!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Gente, que final feliz!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_eleanor,["Hellen, minha dupla, eu vi ela crescendo!! A vida é tão rápida!~"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Eu acho que não vou suportar! Meu coração, eu to quase chorando"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ai gente! Que iti malia!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que é \"ti Malia\"?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sei lá, acabei de criar essa palavra também!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Que criativa você está hoje!"]],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá parecendo a Hellen! Criando palavras do nada"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["A mãe aqui pode tudo, chefe!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee!!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E ai? Vai falar com ela?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Quem? Eu?!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E quem mais seria?"]],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_blush_1],[s_todd_casual_blush_3],false,true,[.25,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee! Eu vou contigo, bobo!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_blush_4],[s_todd_casual_idle_1_left],false,true,[.25,.2]],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
				[scr_cutscene_instance_create,382,404,"Instances_People_1",o_uncle_dmitriy],
				[scr_cutscene_move_character,o_uncle_dmitriy,303,404,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_uncle_dmitriy,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Uh... O que está acontecendo?"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_wendy,"direction",225],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",315],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_wendy,"direction",180],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",0],
				[scr_cutscene_variable,variable.normal,o_eleanor,"direction",225],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_wendy,"direction",135],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",45],
				[scr_cutscene_variable,variable.normal,o_eleanor,"direction",180],
				[scr_cutscene_variable,variable.normal,o_rubbert,"direction",135],
				[scr_cutscene_variable,variable.normal,o_nina,"direction",315],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",180],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_eleanor,"direction",135],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",90],
				[scr_cutscene_variable,variable.normal,o_rubbert,"direction",0],
				[scr_cutscene_variable,variable.normal,o_nina,"direction",0],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_rubbert,"direction",45],
				[scr_cutscene_variable,variable.normal,o_nina,"direction",45],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",0],
				[scr_cutscene_variable,variable.normal,o_clara,"direction",90],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Foi lindo, tio!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Sim, tio! Foi tão romântico!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_eleanor,["Foi babilônico!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Teve drama, teve romance, teve tudo! Uma novela inteira!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Eu vou chorar, foi tão lindo!"]],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",135],
				[scr_cutscene_variable,variable.normal,o_rubbert,"direction",45],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["E não me critica por isso, Nickolai!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Não vou, por que eu vou chorar também!!"]],
				[scr_cutscene_variable,variable.normal,o_nickolai,"direction",90],
				[scr_cutscene_variable,variable.normal,o_rubbert,"direction",45],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Foi fofo, eu achei lindissimo!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Eu deveria ter terminado aquele mestrado...."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["AHEM!... Bom! Acho melhor vocês se recomporem"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Pois a aula já vai começar"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Mesmo no nosso estado emocional?!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Não importa quando e onde, é sempre bom aprender"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Aprendizagem nessa ecônomia... Que coisa..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["O Tio Big B vai contar sobre a história do mundo, para vocês"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sério?!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Diz que é verdade!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Não brinca!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Se eu pedir eu acho que ele canta..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["AHEM! Sim! Ele vai cantar"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Yay!! Vamos!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Já estamos baixando!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Vamos vamos!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_can_play",false],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,0,1],
				[scr_cutscene_wait,1],
				[scr_cutscene_audio_stop,audio_type.bgm,bgm_008],
				[scr_cutscene_variable,variable.normal,o_camera,"x",592],
				[scr_cutscene_variable,variable.normal,o_camera,"y",555],
				[scr_cutscene_wait,2],
				[scr_cutscene_video,story_tell.world_1,sq_world_story],
				[scr_cutscene_remove_party_member,o_hellen],
				[scr_cutscene_bars,true,false]
			]
		],
	]
}
if(keyboard_check_pressed(ord("5"))){
	_t_cutscene=[
		[scr_cutscene_remove_party_member,o_todd],
		[scr_cutscene_item,o_bunbun,-1,[item.love_letter,1]],
		//[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,1,1],
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.complete]],
		[scr_cutscene_set_event,[0,4,progress.complete],[0,5,progress.non_complete]],
		[scr_cutscene_room_goto,rm_corridors,false,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",495],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",585],
		[scr_cutscene_variable,variable.normal,o_camera,"x",495],
		[scr_cutscene_variable,variable.normal,o_camera,"y",585],
		[scr_cutscene_instance_layer,o_bunbun,"Instances_People_1"],
		[scr_cutscene_instance_create,492,585,"Instances_People_1",o_petter],
		[scr_cutscene_instance_create,492,585,"Instances_People_1",o_linus],
		[scr_cutscene_new_party_member,o_petter],
		[scr_cutscene_new_party_member,o_linus],
		[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_talked",true],
		[scr_cutscene_variable,variable.normal,o_petter,"ppl_talked",true],
		[scr_cutscene_variable,variable.normal,o_door_2,"ppl_talked",true],
		[scr_cutscene_item,o_bunbun,-1,[item.linus_diary,1]],
		//[scr_cutscene_room_goto,rm_corridors],
		//[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
		//[scr_cutscene_variable,variable.normal,o_camera,"x",592],
		//[scr_cutscene_variable,variable.normal,o_camera,"y",555],
		//[scr_cutscene_wait,1],
		//[scr_cutscene_video,story_tell.world_1,sq_world_story],
	]
}
if(keyboard_check_pressed(ord("6"))){
	_t_cutscene=[
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.complete]],
		[scr_cutscene_set_event,[0,4,progress.complete],[0,5,progress.non_complete]],
		[scr_cutscene_set_event,[0,5,progress.complete],[0,6,progress.non_complete]],
		[scr_cutscene_room_goto,rm_b_bedroom_2,false,true],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_remove_party_member,o_todd],
		[scr_cutscene_new_party_member,o_todd],
	]
}
if(keyboard_check_pressed(ord("7"))){
	_t_cutscene=[
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.complete]],
		[scr_cutscene_set_event,[0,4,progress.complete],[0,5,progress.non_complete]],
		[scr_cutscene_set_event,[0,5,progress.complete],[0,6,progress.non_complete]],
		[scr_cutscene_set_event,[0,6,progress.complete],[0,7,progress.non_complete]],
		[scr_cutscene_remove_party_member,o_todd],
		[scr_cutscene_instance_destroy,o_todd],
		[scr_cutscene_room_goto,rm_corridors,false,true],
		[scr_cutscene_variable,variable.normal,o_camera,"x",852],
		[scr_cutscene_variable,variable.normal,o_camera,"y",309],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",852],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",309],
		[scr_cutscene_instance_create,852,309,"Instances_People_2",o_linus],
		[scr_cutscene_wait,1],
		[scr_cutscene_new_party_member,o_linus],
	]
}
if(keyboard_check_pressed(ord("8"))){
	_t_cutscene=[
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.complete]],
		[scr_cutscene_set_event,[0,4,progress.complete],[0,5,progress.complete]],
		[scr_cutscene_set_event,[0,5,progress.complete],[0,6,progress.complete]],
		[scr_cutscene_set_event,[0,7,progress.complete],[0,8,progress.non_complete]],
		[scr_cutscene_room_goto,rm_corridors,false,true],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_variable,variable.normal,o_camera,"x",852],
		[scr_cutscene_variable,variable.normal,o_camera,"y",309],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",852],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",309],
		[scr_cutscene_refresh_party_member,true],
		[scr_cutscene_remove_party_member,o_todd],
		[scr_cutscene_new_party_member,o_todd],
	];
}
if(keyboard_check_pressed(ord("9"))){
	_t_cutscene=[
		[scr_cutscene_remove_party_member,o_todd],
		[scr_cutscene_variable,variable.global,-1,"time",time.night],
		[scr_cutscene_set_event,[0,0,progress.complete],[0,1,progress.complete]],
		[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.complete]],
		[scr_cutscene_set_event,[0,4,progress.complete],[0,5,progress.complete]],
		[scr_cutscene_set_event,[0,5,progress.complete],[0,6,progress.complete]],
		[scr_cutscene_set_event,[0,7,progress.complete],[0,8,progress.non_complete]],
		[scr_cutscene_set_event,[0,8,progress.complete],[0,9,progress.non_complete]],
		[scr_cutscene_room_goto,rm_b_bedroom_2,false,false],
		[scr_cutscene_instance_create,663,394,"Instances_People_2",o_bunbun],
		[scr_cutscene_instance_create,663,394,"Instances_People_2",o_todd],
		[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_sleeping],[s_todd_pijama_todd_bedtalk_sleeping],false,true,[.05,.05]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"x",663],
		[scr_cutscene_variable,variable.normal,o_bunbun,"y",394],
		[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_can_play",true],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
		[scr_cutscene_variable,variable.normal,o_todd,"x",649],
		[scr_cutscene_variable,variable.normal,o_todd,"y",335],
		[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.pijama],
		[scr_cutscene_variable,variable.normal,o_todd,"clothe",clothes.pijama],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
		[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
		[scr_cutscene_audio_stop,audio_type.bgm,bgm_002],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	];
}


if(!instance_exists(o_cutscene))and(_t_cutscene!=-1){
	scr_cutscene_create(_t_cutscene);
	_t_cutscene=-1;
}
if(keyboard_check_pressed(ord("Q"))){
	with(o_people) ppl_talked=true;
}
