function scr_talk_edgar(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_edgar]
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_edgar,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,295,1652,false,1,true,true],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_idle_1_4],false,true,[.2,.2]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Olá, pequeno BunBun"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah! Como você sabia que era eu?"],-1,[-1,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Eu apenas sei"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Então, em que eu posso te ajudar?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah, nada demais, eu apenas queria saber como que você está"],-1,[-1,[s_bunbun_casual_playground_idle_1_11],[s_bunbun_casual_playground_talk_1_11]],false,false,[0,.2,.25]],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_idle_1_4],false,true,[.2,.2]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Ah, eu estou bem, Pequeno BunBun, quer saber o que estou fazendo?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim, quero saber sim!..."],-1,[-1,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Bom, poderia se juntar a mim?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Quer que eu deite do seu lado?"],-1,[-1,[s_bunbun_casual_playground_idle_1_4],[s_bunbun_casual_playground_talk_1_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Precisamente, pequeno BunBun"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,297,1675,false,1,true,true],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_1],[s_bunbun_casual_playground_idle_1_1],false,true,[.2,.2]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Então... O que-"],-1,[-1,[s_bunbun_casual_playground_idle_1_1],[s_bunbun_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Feche os olhos... Respire fundo... E sinta o sol bater em sua pele"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_idle_1_2],false,true,[.2,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["E ai?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Fechei"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Perfeito... Agora respire fundo, BunBun... Não há com o que se preocupar quando você está debaixo do sol..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Ele beija a todos igualmente..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Alguns mais fortes, outros mais fraco, mas seus beijos alcançam a todos, igualmente..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Pequeno BunBun... O mundo é um lugar vasto..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Somos o futuro do nosso planeta e temos que fazer um bom trabalho"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Há uma guerra além desses bosques"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["E o futuro está em nossas mãos"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Mas por enquanto... Enquanto não chega a nossa vez de tomar alguma atitude sobre o nosso mundo... Sobre os nossos futuros..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Vamos deitar sobre o sol, pequeno BunBun... Apenas vamos sentir o sol, de forma calma, beijar nossa pele..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Ou no seu caso, pelo..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas eu também tenho pele"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["De fato, pequeno BunBun... Você tem pele..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Edgar..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Sim, pequeno BunBun?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você só está deitado aqui, em baixo do sol, por que você é um lagarto e repteis tem sangue frio... Né?..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Precisamente, pequeno BunBun"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Entendo..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Edgar..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Sim, pequeno BunBun?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Apesar de você só estar se aquecendo, vou levar isso como um \"estou apenas me preparando para quando minha vez chegar\"..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você não está errado, sobre relaxar enquanto não podemos fazer nada... O futuro está em nossas mãos, de fato"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas, enquanto a única coisa que eu puder fazer for nada, então não farei nada"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Você pegou o ponto, pequeno BunBun"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Não sofra se não há o por que de sofrer"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Apenas faça o que puder e dê o seu melhor, enquanto ainda puder fazer algo"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Entendi..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Pequeno BunBun"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim, Edgar?"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Eu gosto da sua companhia, você me pareceu preocupado, então decidi dizer isso para ti..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Isso também é uma desculpa?"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Na realidade sim..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tudo bem, eu gostei de ficar deitado aqui contigo..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você também é uma companhia, Edgar"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Obrigado... Mas você se sente um pouco melhor?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Acho que sim"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Então fique um pouco mais..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Um desabafo, um abraço, um ouvido, um ombro amigo ou até mesmo uma companhia para deixar debaixo do sol"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Estou aqui... Estou aqui para te fazer melhor..."],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Obrigado, Edgar"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Isso soa tão formal"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas é literal seu nome..."],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Pode me chamar por outra coisa?"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tipo o que?"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Grandioso e bonito-"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Não vou te chamar assim"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Justo"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Obrigado de novo, Edgar"],-1,[-1,[s_bunbun_casual_playground_idle_1_2],[s_bunbun_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Não há de quer, pequeno BunBun"],-1,[-1,[s_edgar_casual_playground_idle_1_1],[s_edgar_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_down],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					//animação do BunBun fazendo cariño na cabeça do Edgar
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
			break;
			
	}
}