function scr_talk_rubbert(){
	switch global.day{
		case 0:
			#region
			if(global.event[0][1]==progress.non_complete){
				quest_array=[
					[0,quest_type.talk_to,o_rubbert],
				];
				non_complete_cutscene[0]=[
					[scr_cutscene_variable,variable.normal,o_rubbert,"ppl_talked",true],
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,1164,1663,false,1,true,true],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_idle_1_5],false,true,[.2,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Olá Rubbert!"],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Rubbert?..."],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Ah! Olá, BunBun!"],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Desculpe, eu estava terminando de ler um trecho do livro, perto do Tio Big B"],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Além do sol atrapalhar a leitura, não posso muito com ele, então fico aqui na sombra sombra dele"],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh, tudo bem, Rubbert"],-1,[-1,[s_bunbun_casual_playground_idle_1_13],[s_bunbun_casual_playground_talk_1_13]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas o que você está lendo?"],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Ah... Bom..."],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Desculpe, eu estava terminando de ler um trecho desse livro"],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_rubbert,"sprite_index",s_rubbert_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas o que você está lendo?"],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Bom, é um conjunto de histórias, são umas 90 histórias..."],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Bom, foi o Fritz quem me recomendou... Então..."],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah... Entendo... Bom..."],-1,[-1,[s_bunbun_casual_playground_idle_1_6],[s_bunbun_casual_playground_talk_1_6]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Em qual história você está?"],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["18"],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["18?"],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["18"],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Bom, é que as histórias não possuem titulos, apenas números"],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_rubbert,"sprite_index",s_rubbert_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tipo \"História número 1\"?"],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Mais ou menos..."],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Tipo, a primeira história é a de número 1, ao em vez de ter algo escrito, é apenas uma página grande com o número 1 e depois começa a história..."],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah, bem conceitual, para dizer a verdade"],-1,[-1,[s_bunbun_casual_playground_idle_1_6],[s_bunbun_casual_playground_talk_1_6]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bem a cara do Fritz"],-1,[-1,[s_bunbun_casual_playground_idle_1_6],[s_bunbun_casual_playground_talk_1_6]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_5],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Pra falar a verdade, é bem a cara dele isso mesmo..."],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_rubbert,"sprite_index",s_rubbert_casual_playground_idle_1_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Poderia ler para mim, por favor?"],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Claro!!"],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_rubbert,"sprite_index",s_rubbert_casual_playground_idle_1_1],
					[scr_cutscene_wait,.5],
					[scr_cutscene_audio_play,audio_type.bgm,bgm_006,true,.5,.5],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Em um lugar muito distante...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Havia uma floresta... E nessa floresta, havia uma casa...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"E nessa casa, havia várias crianças que viviam nela...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Todas crianças e nenhum adulto... Apenas as crianças cuidando umas das outras\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Porém, nessa casa, todas as noite, uma criança ia embora\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Sem dizer nada para ninguém, essa criança ia embora...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"E sem dizer nada para ninguém, um bebê aparecia na porta, deixado naquela casa, todas as manhãs\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Porém havia uma criança que sempre se perguntava o por que?\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Por que ela se foi? Para onde ela foi? Ela vai voltar?\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"E a unica coisa que era respondido para ela, era...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Não se preocupe, ela está bem agora...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Mais do que tudo, a criança que sempre perguntava, tinha medo...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Mas dia após dia...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Criança após criança iam embora...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Bebê após bebê iam chegando...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Todas as crianças se ajudavam para cuidar umas das outras\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Todas as crianças se revesavam para brincar\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"A casa permanecia alegre e contente, limpa e sorridente\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Mas um dia...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"A criança que perguntava, acordou no meio da noite...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Sem dizer nada para ninguém, essa criança foi embora...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Ela caminhou no meio do bosque\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Ela caminhou no meio das pedras\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Ela caminhou no meio de uma plantação\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"E então ela encontrou uma casa...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Ela bateu na porta e então, a única coisa que lhe foi dito foi...\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["\"Seja bem vinda, estavamos te esperando\""],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Fim..."],-1,[-1,[s_rubbert_casual_playground_idle_1_1],[s_rubbert_casual_playground_talk_1_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_audio_play,audio_type.bgm,bgm_006,true,1,.5],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["É isso..."],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah... Apenas isso?..."],-1,[-1,[s_bunbun_casual_playground_idle_1_5],[s_bunbun_casual_playground_talk_1_5]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Sim... Algumas são maiores que outras, as primeiras dificilmente passavam de uma linha..."],-1,[-1,[s_rubbert_casual_playground_idle_1_3],[s_rubbert_casual_playground_talk_1_3]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Depois começaram a ficar mais complexas..."],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tenho que dizer que elas são um pouco anti-climáticas...."],-1,[-1,[s_bunbun_casual_playground_idle_1_6],[s_bunbun_casual_playground_talk_1_6]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_playground_idle_1_5],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Precisamente..."],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Bom, vou ver como os outros estão, ok?!"],-1,[-1,[s_bunbun_casual_playground_idle_1_13],[s_bunbun_casual_playground_talk_1_13]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_rubbert,["Tudo bem, BunBun, se cuide"],-1,[-1,[s_rubbert_casual_playground_idle_1_2],[s_rubbert_casual_playground_talk_1_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você também, Rubbert!!"],-1,[-1,[s_bunbun_casual_playground_idle_1_13],[s_bunbun_casual_playground_talk_1_13]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_rubbert,"sprite_index",s_rubbert_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_idle_1_downleft],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
				complete_cutscene=[
					[scr_cutscene_bars,true,true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_rubbert],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
					[scr_cutscene_wait,.5],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Como está a leitura?"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee, está boa, então!"]],
					[scr_cutscene_wait,.5],
					[scr_cutscene_variable,variable.normal,o_rubbert,"sprite_index",s_rubbert_casual_playground_idle_1_1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
					[scr_cutscene_wait,.5],
					[scr_cutscene_bars,true,false],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play]
				];
			}
			#endregion
			break;
	}
}