sprite_index=s_nothing;
enum quick_type{
	spam_press,
	mult_press
}
quicktime_event_type=quick_type.spam_press;
timer=0;
quick_button_timer=0;
quick_button_limit=0;
quick_button_current=0;
button_index=-1;
quick_button_list=[
	ord("Q"),
	ord("W"),
	ord("E"),
	ord("A"),
	ord("S"),
	ord("D"),
	ord("Z"),
	ord("X"),
	ord("C"),
	global.input_select_down,
	global.input_select_up,
	global.input_select_left,
	global.input_select_right,
];
quick_button=-1;
quick_button_end=false;
cutscene_1=-1;
cutscene_2=-1;
t_cutscene_play=-1;
quick_button_start=false;