quest_array=[
	[0,quest_type.have_item,item.basement_key_1],
]
non_complete_cutscene[0]=[
	[scr_cutscene_condition,question.have_person,o_todd,
		[
			[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Trancado..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			],
			[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Trancado..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Quanta sorte..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Desculpe, Todd..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Apenas vamos bucar pela chave"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
		]
	]
]

complete_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_basement_5,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",714],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",190],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"x",714],
	[scr_cutscene_variable,variable.normal,o_camera,"y",217],
	[scr_cutscene_instance_create,547,296,"Instances_People_1",o_they],
	[scr_cutscene_variable,variable.normal,o_l_basement_light,"light_set_alpha",0],
	[scr_cutscene_variable,variable.normal,o_graphic,"graphic_color_bg",c_black],
	[scr_cutscene_variable,variable.normal,o_graphic,"graphic_custom_at_light_color",merge_color(c_white,c_red,.15)],
	[scr_cutscene_variable,variable.normal,o_graphic,"graphic_custom_bg_light_color",c_red],
	[scr_cutscene_wait,1],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,714,217],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,714,217,false,1,true,true],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,714,217],
	[scr_cutscene_wait,1],
	[scr_cutscene_condition,question.have_person,o_todd,
		[
			[
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh..."]],
				[scr_cutscene_wait,2],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_camera,0,100,true,1,false,false],
				[scr_cutscene_wait,2],
				[scr_cutscene_move_character,o_camera,0,-150,true,1,false,false],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Um... Longo corredor...."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_camera,-50,0,true,1,false,false],
				[scr_cutscene_wait,2],
				[scr_cutscene_move_character,o_camera,50,0,true,1,false,false],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E outro mais escuro..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Talvez se eu seguir o fim desse corredor, talvez me leve a algum lugar..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu..."]],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu não deveria ter vindo sozinho..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["..."]],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu sou muito intrometido..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Talvez eu deveria apenas-"]],
				[scr_cutscene_move_character,o_they,704,296,false,1,false,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah..."]],
				[scr_cutscene_move_character,o_they,0,8,true,1,false,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu... Não consigo..."]],
				[scr_cutscene_move_character,o_they,0,8,true,1,false,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_audio_play,audio_type.sfx,sfx_019,false,1,0],
				[scr_cutscene_move_character,o_bunbun,0,8,true,1,true,false],
				[scr_cutscene_wait,4],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Correr"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.run],
				[scr_cutscene_variable,variable.normal,o_they,"ppl_act_state",ppl_act.run],
				[scr_cutscene_bars,false,false]
			],
			[
			
			]
		]
	],
];