icon_left=global.cw+64;
show_icon=true;
icon_alp=0
children_playing=[
	[o_boris,false,s_boris_faceicon_idle_1,"Boris",659,593],
	[o_danica,false,s_danica_faceicon_idle_1,"Danica",545,566],
	[o_jasenska,false,s_jasenska_faceicon_idle_1,"Jasenska",594,552],
	[o_julia,false,s_julia_faceicon_idle_1,"Julia",621,552],
	[o_ksenia,false,s_ksenia_faceicon_idle_1,"Ksenia",647,561],
	[o_lorie,false,s_lorie_faceicon_idle_1,"Lorie",565,544],
	[o_olivia,false,s_olivia_faceicon_idle_1,"Olivia",533,596]
];
complete_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,-8,0,true,1,true,false],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_laszlo],
	[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
	[scr_cutscene_move_character,o_laszlo,8,0,true,1,true,false],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_bunbun],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_looking_to",true],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Laszlo, parece que encontramos a todos!!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Realmente"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Parabéns para nós!!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Acho que sim... Vamos para o hall ver quem será o próximo"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ok! Vamos!!"]],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
	[scr_cutscene_set_event,[0,2,progress.complete],[0,3,progress.non_complete]],
	[scr_cutscene_room_goto,rm_corridors,false],
	[scr_cutscene_instance_layer,o_bunbun,"Instances_People_1"],
	[scr_cutscene_instance_layer,o_laszlo,"Instances_People_1"],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",605],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",618],
	[scr_cutscene_variable,variable.normal,o_laszlo,"x",580],
	[scr_cutscene_variable,variable.normal,o_laszlo,"y",628],
	[scr_cutscene_wait,.25],
	[scr_cutscene_instance_destroy,o_hide_n_seek],
	[scr_cutscene_wait,.25],
	[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
	
	[scr_cutscene_variable,variable.normal,o_boris,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_danica,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_julia,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_lorie,"ppl_looking_to",false],
	[scr_cutscene_variable,variable.normal,o_olivia,"ppl_looking_to",false],
	
	[scr_cutscene_variable,variable.normal,o_boris,"direction",225],
	[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
	[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",315],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",315],
	[scr_cutscene_wait,.5],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Demoramos um pouco, mas encontramos a todos!!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Como fomos?"]],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_olivia,["Foi legal jogar com o BunBun!!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_lorie,["De fato"]],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",45],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["O BunBun é bom jogando isso, ele sabe exatamente onde buscar"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você estava atrás de um abajur..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Ninguém nunca pensaria nisso!..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Apenas você"]],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",45],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E você, Laszlo? Se divertiu?"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ah! Eu?... Bom... Na realidade-"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E por algum caso isso importa?"]],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
	[scr_cutscene_variable,variable.normal,o_boris,"direction",135],
	[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
	[scr_cutscene_variable,variable.normal,o_lorie,"direction",0],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",45],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",45],
	[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia"]],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Minha Dama de Pétalas, a senhora vem sendo muito permissiva com eles, apenas por causa que é o BunBun"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E se tivesse sido, Petter, Grettel, ou Hellen?"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E se tivesse sido qualquer outra criança nessa casa? A senhora ainda assim seria permissiva?"]],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
	[scr_cutscene_variable,variable.normal,o_boris,"direction",225],
	[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
	[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",315],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",315],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E eu discordo, não foi nada legal brincar com o BunBun"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Sua presença em território interno é uma mancha na nossa sociedade"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E eu nunca, jamais, irei respeitar alguém que quebre as regras da Hierarquia Rosa"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Ainda mais por atitudes nepotistas, seu externo baderneiro!"]],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
	[scr_cutscene_variable,variable.normal,o_boris,"direction",135],
	[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
	[scr_cutscene_variable,variable.normal,o_lorie,"direction",0],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",45],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",45],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Basta, Julia!!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Não, minha dama! Basta de ti! basta de tuas atitudes para com nossa sociedade!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Não vê o que isso está causando?"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Eu não ceder em tentar manter as regras, em fazer com que elas sejam seguidas! Mas..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Mas?..."]],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Mas..."]],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_boris,"direction",225],
	[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
	[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",315],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",315],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sou eu o mártir dessa história"]],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",225],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
	[scr_cutscene_variable,variable.normal,o_jasenska,"direction",315],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_jasenska,"direction",270],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Minhas crenças da injustuiça nessa sociedade foram o estopim para a destruição deste, nesse momento"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Meus pensamentos desnecessários trouxeram a ruína e o caos para nós"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Eu sou o culpado por tudo isso"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sou eu o mártir dessa história"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas Laszlo!..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não, BunBun... Esse é o destino original"]],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",45],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sinto muito, BunBun, mas eu quebrei as regras, e ainda envolvi um externo"]],
	[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Eu mereço isso..."]],
	[scr_cutscene_wait,1],
	//[scr_cutscene_variable,variable.normal,o_julia,"direction",180],	
	[scr_cutscene_variable,variable.normal,o_boris,"direction",180],
	[scr_cutscene_variable,variable.normal,o_lorie,"direction",0],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",0],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
	[scr_cutscene_variable,variable.normal,o_boris,"direction",135],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",45],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",0],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",45],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",225],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",180],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["..."]],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Pela quebra do Código dois, terceiro e quarto seguimento da Hierarquia Rosa, eu te declaro culpado, e te aplicaremos a devida punição pelos crimes cometidos"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Eu aceito minha punição"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia..."]],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Minha dama..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Iremos para o quarto, para decidir e aplicar sua punição..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Mas é claro, minha dama"]],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_boris,"direction",180],
	[scr_cutscene_variable,variable.normal,o_lorie,"direction",315],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",0],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
	[scr_cutscene_variable,variable.normal,o_boris,"direction",225],
	[scr_cutscene_variable,variable.normal,o_danica,"direction",315],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",315],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_olivia,"direction",315],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",225],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_julia,"direction",270],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Vamos todos..."]],
	[scr_cutscene_wait,1],
	[scr_cutscene_set_path,o_lorie,p_lorie_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,.25],
	[scr_cutscene_set_path,o_danica,p_danica_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,.25],
	[scr_cutscene_set_path,o_olivia,p_olivia_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,.25],
	[scr_cutscene_set_path,o_boris,p_boris_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,.25],
	[scr_cutscene_set_path,o_ksenia,p_ksenia_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,.25],
	[scr_cutscene_set_path,o_julia,p_julia_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_laszlo],
	[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Desculpe, BunBun..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Vamos, Laszlo..."]],
	[scr_cutscene_instance_create,1133,577,"Instances_People_1",o_todd],
	[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.npc],
	[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
	[scr_cutscene_variable,variable.normal,o_todd,"x",1133],
	[scr_cutscene_variable,variable.normal,o_todd,"y",577],
	[scr_cutscene_wait,1],
	[scr_cutscene_set_path,o_jasenska,p_jasenska_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,.5],
	[scr_cutscene_remove_party_member,o_laszlo],
	[scr_cutscene_set_path,o_laszlo,p_laszlo_hide_n_seek_end,1,path_action_stop,true,path_act.delet],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
	[scr_cutscene_move_character,o_todd,698,577,false,1,true,true],
	[scr_cutscene_new_party_member,o_todd],
	[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_bunbun],
	[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun?"]],
	[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
	[scr_cutscene_move_character,o_todd,637,618,false,1,true,false],
	[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun? Tá tudo bem?..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu vi a galera da Hierarquia Rosa saindo e você no meio deles"]],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
	[scr_cutscene_wait,.1],
	[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
	[scr_cutscene_wait,1],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eles estavam brincando de esconde-esconde, o Laszlo queria brincar também..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu brinquei junto deles, porém apenas se o Laszlo pudesse brincar com a gente..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["No fim, o Laszlo foi punido por minha causa"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ai, BunBun... Você não tem jeito mesmo"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu já falei para você não se envolver com a Hierarquia Rosa, eles só vão te machucar"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Lembra quando a gente ainda estava no quarto infantil e fazia parte da Hierarquia Rosa?"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, mas a Wendy não era tão má quanto a Julia..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ai, BunBun... Você não tem jeito mesmo"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["A Wendy e o Tomas não eram nada fáceis, mas eu tenho que concordar que essa Julia me dá um pouco de medo, heehee"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você com medo, haahaa..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["HeeHee! Bom, BunBun, vamos deixar isso de lado, tudo bem? Sei que você não gosta de ver injustiça"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mas as vezes não há muito o que possamos fazer"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["As vezes o melhor que podemos fazer é nada, tudo bem?"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu entendo... Eu só gosto de ajudar quem eu amo..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sei que você faria de tudo por quem ama, e eu faço o mesmo"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E por causa disso eu quero que você venha comigo fazer outra coisa, para ocupar a mente, tudo bem?"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... O que seria?..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["HeeHee!... Bom..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Queria saber o que a Mamãe está fazendo de almoço..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Sério?..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Por favor, BunBun!!"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas acabamos de tomar café... Não deve fazer nem uma hora"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Mas mas... É que-"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tudo bem, tudo bem... Vou com você, seu chorão"]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Yeah! Valeu, BunBun!! Vamos lá na cafeteria, Acho que a Mamãe vai estar lá!..."]],
	[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tudo bem, vamos lá, grandão"]],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false],
];