if(global.event[0][6]==progress.non_complete){
	quest_array=[
		[0,quest_type.someone_party,o_calina],
	]
	complete_cutscene=[];
	non_complete_cutscene[0]=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,855,581,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
		[scr_cutscene_move_character,o_todd,913,581,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá, Calina!!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oi Calina!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Está tudo bem?... Você parece..."]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Olá BunBun, desculpe pelo meu humor..."],-1,[[0],[s_calina_casual_crayon_idle_2],[s_calina_casual_crayon_talk_2]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Mas pegaram meus materiais de desenho..."],-1,[[0],[s_calina_casual_crayon_idle_1],[s_calina_casual_crayon_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_calina,"sprite_index",s_calina_casual_crayon_idle_2],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh! Mas... Você sabe quem foi?"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Sim... Eu sei... Foi o Julian"],-1,[[0],[s_calina_casual_crayon_idle_3],[s_calina_casual_crayon_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Só que eu não faço ideia de onde ele possa estár"],-1,[[0],[s_calina_casual_crayon_idle_2],[s_calina_casual_crayon_talk_2]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Julian?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom, o Julian sempre está com o Vladmir, Gleb e Paxton..."]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Sim... Mas onde estão esses quatro agora?"],-1,[[0],[s_calina_casual_crayon_idle_3],[s_calina_casual_crayon_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_calina,"sprite_index",s_calina_casual_crayon_idle_2],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ela apresentou um bom ponto"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Realmente, um bom ponto"]],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Exatamente"],-1,[[0],[s_calina_casual_crayon_idle_3],[s_calina_casual_crayon_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Sem isso, não posso desenhar nada... Justo quando eu estava praticando..."],-1,[[0],[s_calina_casual_crayon_idle_1],[s_calina_casual_crayon_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_calina,"sprite_index",s_calina_casual_crayon_idle_4],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A gente pode te ajudar a procurar eles"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Oh! Vocês estão falando sério?"],-1,[[0],[s_calina_casual_crayon_idle_4],[s_calina_casual_crayon_talk_4]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim, claro que sim! Mas..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Se você puder me ensinar a desenhar em troca..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu ficaria super feliz"]],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você também seria grato!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mas não é a mesma coisa?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Estarem conectados não quer dizer ser a mesma coisa"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mas minha nossa"]],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["É pegar ou largar"]],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd!!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que?!"]],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_animation_sprite,o_calina,[s_calina_casual_crayon_down],[s_calina_casual_crayon_idle_5],false,true,[.3,.2]],
		[scr_cutscene_wait,.5],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Bom!! A troca me parece muito justa!"],-1,[[0],[s_calina_casual_crayon_idle_5],[s_calina_casual_crayon_talk_5]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Na realidade eu fico muito feliz que você queira aprender a desenhar, Todd!!"],-1,[[0],[s_calina_casual_crayon_idle_6],[s_calina_casual_crayon_talk_6]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Não existe coisa mlehor do que expressar a criatividade!!"],-1,[[0],[s_calina_casual_crayon_idle_5],[s_calina_casual_crayon_talk_5]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim!! Eu falei isso para ele!!"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Ouça mais o BunBun, Todd!!"],-1,[[0],[s_calina_casual_crayon_idle_6],[s_calina_casual_crayon_talk_6]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Nunca fui tão humilhado na minha vida..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Bom..."]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_calina,["Bom, ainda assim, obrigado de verdade por me ajudarem!!"],-1,[[0],[s_calina_casual_crayon_idle_5],[s_calina_casual_crayon_talk_5]],false,false,[0,.2,.25]],
		[scr_cutscene_wait,.5],
		[scr_cutscene_animation_sprite,o_calina,[s_calina_casual_crayon_getting_up],[s_calina_casual_idle_1_down],false,true,[.35,.2]],
		[scr_cutscene_variable,variable.normal,o_calina,"ppl_act_state",ppl_act.npc],
		[scr_cutscene_wait,.5],
		[scr_cutscene_variable,variable.normal,o_calina,"direction",225],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Agora vamos atrás do Julian..."]],
		[scr_cutscene_variable,variable.normal,o_calina,"direction",315],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos nessa!!"]],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_new_party_member,o_calina],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	]
}