non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_k_bedroom,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",395],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",663],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_variable,variable.normal,o_camera,"x",395],
	[scr_cutscene_variable,variable.normal,o_camera,"y",563],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,395,563,false,1,true,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
];
switch global.day{
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto das crinaças pequenas... Busca por algo?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Não não, só tô explorando mesmo... Mas seria legal buscar por alguma pista..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Você diz pelo 45 e 46, e pela 47 e 48?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim! Eu to curioso para saber qual nome eles vão colocar entre si!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Deixa de ser fofoqueiro, BunBun!...."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mas eu concordo... Eu também ando curioso"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][3]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.mother_list],
				[-1,quest_type.have_item,item.uncle_spices],
			]
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não acredito que a Mamãe vai estar no quarto de uma das crianças..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Certeza?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim e por que motivo ela estaria?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Por que ela é nossa mãe e sempre nos ajuda com tudo! Ela quem nos ensinava a arrumar a cama, bobo"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok, você tem um ponto, mas ainda assim, ela não vai estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá bom..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto do Tio Big B não é aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, eu sei, apenas pensei que ele pudesse estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E por que raios ele estaria em um quarto de uma das crianças?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele sempre se certifica do bem estar de todos aqui!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Chorei 5 unidades de lágrimas, vamos logo para o quarto dele"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bobo..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Depois você vê o que tem nas gavetas do povo, vamos entregar os temperos para a Mamãe!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["QUE?! Eu não vejo o que tem nas gavetas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vê sim! Você é todo curioso!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não!... Na realidade sim, sou curioso... MAS EU NÃO VEJO O QUE TEM NAS GAVETAS!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][4]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.love_letter],
				[-1,quest_type.talk_to,o_noah],
				[-1,quest_type.talk_to,o_hellen],
				[-1,quest_type.have_item,item.noah_gift],
			];
			complete_cutscene=[]
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... BunBun... Esse não é meu quarto..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele tem memória de curto prazo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você é quem tem memória de curto prazo!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Então vamos logo para o quarto da Hellen!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá tá..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O 45 estaria aqui?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu tenho certeza que vi ele no andar de baixo.."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh? Pensei que ele estava aqui, vamos lá então"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos nessa!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[2]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["A Wendy não está aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh? Como você sabe?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ela gosta de ficar lendo no quarto dela, depois de brincar lá fora..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, bom... Tudo bem, vamos lá então!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[3]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ainda temos que pegar o presente com o 45"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh! É verdade!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Se não sou eu"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, Não seja assim!..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O Fritz está lá em baixo..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Fica calma, já, respira, ok?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Falar é fácil!... Meu Deus, que medo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu sei!! Logo logo será eu!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][5]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.someone_party,o_petter],
				[-1,quest_type.talk_to,o_door_1],
				[-1,quest_type.talk_to,o_bunbun],
				[-1,quest_type.talk_to,o_door_2],
				[-1,quest_type.someone_party,o_linus],
				[-1,quest_type.have_item,item.linus_diary],
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_variable,variable.normal,o_door_1,"ppl_talked",true],
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["BunBun..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_petter],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh! Sim?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A ideia de estar com uma das crianças pequenas não é má..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... Acho que sim... Na realidade, eu pensei no Tio Antony ter entregado sua pelúcia para um bebê"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Um bebê?... Oh..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... Acho que sim... Mas não temos muita certeza! Quem sabe está com Laszlo ou com o 45!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ou quem sabe com a 47!! Se pedir, eu tenho certeza que vão devolver..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Tudo bem... Só de eu saber com quem está, já me deixa feliz"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh, Ok, Petter..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_k_bedroom,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",395],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",663],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",395],
				[scr_cutscene_variable,variable.normal,o_camera,"y",563],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,395,563,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[2]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_k_bedroom,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",395],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",663],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",395],
				[scr_cutscene_variable,variable.normal,o_camera,"y",563],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,395,563,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[0]=non_complete_cutscene[2];
			non_complete_cutscene[3]=non_complete_cutscene[2];
			non_complete_cutscene[4]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A porta está entre aberta..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Oh... Que estranho..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Melhor não pertubar as crinças menores"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você tem razão"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			
			non_complete_cutscene[5]=[
				[scr_cutscene_condition,question.have_item,item.jeyjey_colar,
					[
						[
							[scr_cutscene_bars,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! A porta está entre aberta"]],
							//som da porta fechando
							[scr_cutscene_variable,variable.nearst,o_door_1,"image_index",0,x,y],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_boris],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_julia],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_jasenska],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_noah],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah! Fecharam ela!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Hey!! Abram essa porta!! Sabemos que estão ai!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Não estamos não"]],
							[scr_cutscene_wait,2],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Isso é sério?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Poxa, Boris"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_noah,["Tenha santa paciência, Boris"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Deus, me dê paciencia, por que se me der forças..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Mas eu só fiz o que me pediram!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Abram a porta e devolvam o que é meu!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A-Ah!... Sim! Devolvam!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vocês não tinham o menor direito!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["É o BunBun?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["UGH! Que surpresa!! Deixem ele entrar..."]],
							[scr_cutscene_instance_destroy,o_jasenska],
							[scr_cutscene_instance_destroy,o_julia],
							[scr_cutscene_instance_destroy,o_boris],
							[scr_cutscene_instance_destroy,o_noah],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
							[scr_cutscene_room_goto,rm_k_bedroom,true,false],
				
							[scr_cutscene_instance_create,395,553,"Instances_People_2",o_boris],
							[scr_cutscene_instance_create,717,428,"Instances_People_2",o_julia],
							[scr_cutscene_instance_create,685,442,"Instances_People_2",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
							[scr_cutscene_instance_create,691,374,"Instances_People_2",o_oliver],
							[scr_cutscene_variable,variable.normal,o_oliver,"direction",315],
							[scr_cutscene_instance_create,713,379,"Instances_People_2",o_noah],
							[scr_cutscene_variable,variable.normal,o_noah,"direction",315],
							[scr_cutscene_instance_create,748,442,"Instances_People_2",o_laszlo],
							[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
							[scr_cutscene_instance_create,584,427,"Instances_People_2",o_sofia],
							[scr_cutscene_variable,variable.normal,o_sofia,"direction",0],
							[scr_cutscene_instance_create,600,474,"Instances_People_2",o_ophelia],
							[scr_cutscene_variable,variable.normal,o_ophelia,"direction",0],
							[scr_cutscene_instance_create,752,497,"Instances_People_2",o_lorie],
							[scr_cutscene_variable,variable.normal,o_lorie,"direction",135],
							[scr_cutscene_instance_create,726,508,"Instances_People_2",o_olivia],
							[scr_cutscene_variable,variable.normal,o_olivia,"direction",135],
							[scr_cutscene_instance_create,811,453,"Instances_People_2",o_ksenia],
							[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
							[scr_cutscene_instance_create,789,446,"Instances_People_2",o_danica],
							[scr_cutscene_variable,variable.normal,o_danica,"direction",180],
							[scr_cutscene_variable,variable.normal,o_bunbun,"x",395],
							[scr_cutscene_variable,variable.normal,o_bunbun,"y",663],
							[scr_cutscene_instance_create,395,663,"Instances_People_2",o_linus],
							[scr_cutscene_variable,variable.normal,o_linus,"pos",48],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_act_state",ppl_act.flow],
							[scr_cutscene_refresh_party_member,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"x",395],
							[scr_cutscene_variable,variable.normal,o_camera,"y",563],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_looking_to",true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Ah!!"]],
							[scr_cutscene_move_character,o_boris,395,430,false,1,true,false],
							[scr_cutscene_move_character,o_bunbun,395,513,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_boris,"direction",0],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Eles entraram!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_noah,["Não me diga, Boris-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["A gente não tinha percebido..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Vocês são crueis"]],
							[scr_cutscene_variable,variable.normal,o_boris,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Vocês ouviram, entrem"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Obrigado..."]],
							[scr_cutscene_wait,.5],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_wait,.5],
							[scr_cutscene_move_character,o_bunbun,395,442,false,1,true,true],
							[scr_cutscene_move_character,o_bunbun,592,445,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["O que você veio fazer aqui, BunBun?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Se intrometer, é claro!..."]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E o que mais você acha que ele fez até agora?!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Se intrometendo e piorando toda a situação"]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu... Eu vim arrumar as coisas"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Claro que sim!..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Você sabe muito bem como são as regras"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Vocè sabe que em caso de quebra de regras, punições devem ser aplicadas!"]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_linus],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_linus],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu pouco me importo para essas regras!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu só quero de volta!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Eu..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Linus-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Regras são regras, linus! Não iremos devolver!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu... Por favor... Devolva..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Por favor, devolva...."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que foi que vocês pegaram dele?"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_linus],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Um livro..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh?... Um livro?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Não é um livro..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["É um diário"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Por favor... Apenas devolvam..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Um diário... Um item muito importente..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tomem..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu quero trocar isso pelo diário do Linus"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["E o que seria isso?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uma carta de amor..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Uma!!-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Uma carta?! De amor?!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim... Uma carta que eu escrevi para uma pessoa que eu amo muito..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uma pessoa que eu morreria por ela..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uma pessoa que eu escutaria a voz até que a ultima estrela brilhasse no céu..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Que patético!... Ambos se quer tem o mesmo valor-"]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["QUE DROGA, JULIA, CALA A BOCA!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["EU sou a Dama de pétalas e VOCÊ é a Dama de Espinhos"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Lembre-se que você está ABAIXO DE MIM na Hierarquia!!"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Sim senhora"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você realmente quer trocar essa carta por esse diário?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["O que?! BunBun-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se isso fizer Linus feliz"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, não alimente esse desejo deles!"]],
							[scr_cutscene_move_character,o_bunbun,655,442,false,1,true,true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Aqui..."]],
							[scr_cutscene_item,o_bunbun,item.love_letter,[-1,-1],false],
							[scr_cutscene_item,o_bunbun,-1,[item.linus_diary,1],true],
							[scr_cutscene_wait,2],
							[scr_cutscene_move_character,o_bunbun,592,445,false,1,true,false],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Bom..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Obrigada..."]],
							[scr_cutscene_wait,2],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_jasenska,"direction",270],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Laszlo..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["S-Sim"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Sua divida não foi anulada, porém sim reduzida"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["UH?! Mas!-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Basta, BunBun"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia foi hostil e extremamente severa"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Mas ela está certa de uma coisa..."]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_looking_to",true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você é intrometido... E vive tentando ajudar os outros e falhando"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["BunBun, seja mais egoísta, caso o contrário você apenas irá machucar ainda mais as pessoas"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Assim como você machucou o Laszlo... E o Linus..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você se propõe a fazer apenas uma coisa e ainda assim é falho nessa única coisa que deveria fazer"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Se realmente você deseja ajudar... Saia..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Saia desse quarto e entenda que você não é bem vindo aqui"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Entendo..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... Você está certa"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Meu trabalho aqui está completo"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
							[scr_cutscene_move_character,o_bunbun,395,442,false,1,true,true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Só vamos embora.... Por favor..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["BunBun..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_petter,"direction",0],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Vocês são horríveis!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Horríveis, horríveis, horríveis!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A Hierarquia Rosa é a pior coisa que aconteceu nessa casa!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["E eu odeio cada minuto que eu passei na Hierarquia Rosa!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["O BunBun é incrível e ele sim me ajudou!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["E eu não conseguiria sem o BunBun!..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Eu... Eu não teria coragem sem ele..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Se ele é intromedito então eu também sou!"]],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",true],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",180],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
							[scr_cutscene_wait,1.5],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Só vamos embora daqui..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_petter,"petter",0],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",true],
							[scr_cutscene_wait,1.5],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eles não merecem nem uma palavra..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Desculpe, BunBun... Apenas vamos embora daqui..."]],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh-hum"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_bunbun,395,563,false,1,true,true],[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
							[scr_cutscene_room_goto,rm_corridors,true,false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"x",1031],
							[scr_cutscene_variable,variable.normal,o_bunbun,"y",312],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_refresh_party_member,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
							[scr_cutscene_variable,variable.normal,o_camera,"y",328],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
							[scr_cutscene_variable,variable.normal,o_camera,"y",328],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,1031,328],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_bunbun,1031,328,false,1,true,true],
							[scr_cutscene_refresh_party_member,false],
							[scr_cutscene_wait,1.5],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,1031,328],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",false],
							[scr_cutscene_move_character,o_linus,-24,0,true,1,true,true],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
							[scr_cutscene_move_character,o_petter,0,24,true,1,true,true],
							[scr_cutscene_move_character,o_petter,24,0,true,1,true,true],
							[scr_cutscene_variable,variable.normal,o_petter,"direction",135],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh, BunBun... Você está bem? O que eles disseram para você foi crueldade extrema!"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu tenho que concordar, BunBun... Foi extremamente maldoso o que eles falaram"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Acho que sim... Mas Eles estavam certos"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se eu não tivesse me intrometido, o Laszlo e nem você teriam sido afetados..."]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah! Não BunBun! Você foi quem me ajudou a contar o que eu sinto para a Mamãe e para o Tio Big B!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Se você é um intrometido, então quero ser intrometido como você!"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu também, BunBun"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Se você não ajuda ninguém, como eles dizem, então não há ninguém que ajude"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Até por que os próprios Omnis foram intrometidos"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["E agora temos um lugar para nos abrigar da guerra"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Mas bem... Falando em ser intrometido"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vamos lá falar sobre o Tio Antony, com a Mamãe e o Tio Big B"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah! É verdade! Eu tinha me esquecido por completo!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, ok ok..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E... Obrigado por isso"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Não se preocupe, BunBun, apenas vamos terminar com essa parte"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ok, coelhamigo?"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ok, coelhamigo..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",true],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vocês inventam cada coisa"]],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_bars,true,false]
						],
						[
							[scr_cutscene_bars,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! A porta está entre aberta"]],
							//som da porta fechando
							[scr_cutscene_variable,variable.nearst,o_door_1,"image_index",0,x,y],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_boris],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_julia],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_jasenska],
							[scr_cutscene_instance_create,1025,302,"Instances_People_2",o_noah],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah! Fecharam ela!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Hey!! Abram essa porta!! Sabemos que estão ai!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Não estamos não"]],
							[scr_cutscene_wait,2],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Isso é sério?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Poxa, Boris"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_noah,["Tenha santa paciência, Boris"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Deus, me dê paciencia, por que se me der forças..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Mas eu só fiz o que me pediram!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Abram a porta e devolvam o que é meu!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A-Ah!... Sim! Devolvam!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vocês não tinham o menor direito!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["É o BunBun?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["UGH! Que surpresa!! Deixem ele entrar..."]],
							[scr_cutscene_instance_destroy,o_jasenska],
							[scr_cutscene_instance_destroy,o_julia],
							[scr_cutscene_instance_destroy,o_boris],
							[scr_cutscene_instance_destroy,o_noah],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
							[scr_cutscene_room_goto,rm_k_bedroom,true,false],
				
							[scr_cutscene_instance_create,395,553,"Instances_People_2",o_boris],
							[scr_cutscene_instance_create,717,428,"Instances_People_2",o_julia],
							[scr_cutscene_instance_create,685,442,"Instances_People_2",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
							[scr_cutscene_instance_create,691,374,"Instances_People_2",o_oliver],
							[scr_cutscene_variable,variable.normal,o_oliver,"direction",315],
							[scr_cutscene_instance_create,713,379,"Instances_People_2",o_noah],
							[scr_cutscene_variable,variable.normal,o_noah,"direction",315],
							[scr_cutscene_instance_create,748,442,"Instances_People_2",o_laszlo],
							[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
							[scr_cutscene_instance_create,584,427,"Instances_People_2",o_sofia],
							[scr_cutscene_variable,variable.normal,o_sofia,"direction",0],
							[scr_cutscene_instance_create,600,474,"Instances_People_2",o_ophelia],
							[scr_cutscene_variable,variable.normal,o_ophelia,"direction",0],
							[scr_cutscene_instance_create,752,497,"Instances_People_2",o_lorie],
							[scr_cutscene_variable,variable.normal,o_lorie,"direction",135],
							[scr_cutscene_instance_create,726,508,"Instances_People_2",o_olivia],
							[scr_cutscene_variable,variable.normal,o_olivia,"direction",135],
							[scr_cutscene_instance_create,811,453,"Instances_People_2",o_ksenia],
							[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
							[scr_cutscene_instance_create,789,446,"Instances_People_2",o_danica],
							[scr_cutscene_variable,variable.normal,o_danica,"direction",180],
							[scr_cutscene_variable,variable.normal,o_bunbun,"x",395],
							[scr_cutscene_variable,variable.normal,o_bunbun,"y",663],
							[scr_cutscene_instance_create,395,663,"Instances_People_2",o_linus],
							[scr_cutscene_variable,variable.normal,o_linus,"pos",48],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_act_state",ppl_act.flow],
							[scr_cutscene_refresh_party_member,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"x",395],
							[scr_cutscene_variable,variable.normal,o_camera,"y",563],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_boris],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_looking_to",true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Ah!!"]],
							[scr_cutscene_move_character,o_boris,395,430,false,1,true,false],
							[scr_cutscene_move_character,o_bunbun,395,513,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_boris,"direction",0],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Eles entraram!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_noah,["Não me diga, Boris-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["A gente não tinha percebido..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Vocês são crueis"]],
							[scr_cutscene_variable,variable.normal,o_boris,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["Vocês ouviram, entrem"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Obrigado..."]],
							[scr_cutscene_wait,.5],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_wait,.5],
							[scr_cutscene_move_character,o_bunbun,395,442,false,1,true,true],
							[scr_cutscene_move_character,o_bunbun,592,445,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",true],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["O que você veio fazer aqui, BunBun?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Se intrometer, é claro!..."]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["E o que mais você acha que ele fez até agora?!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Se intrometendo e piorando toda a situação"]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu... Eu vim arrumar as coisas"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Claro que sim!..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Você sabe muito bem como são as regras"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Vocè sabe que em caso de quebra de regras, punições devem ser aplicadas!"]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_linus],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_linus],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu pouco me importo para essas regras!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu só quero de volta!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Eu..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Linus-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Regras são regras, linus! Não iremos devolver!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu... Por favor... Devolva..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Por favor, devolva...."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que foi que vocês pegaram dele?"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_linus],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Um livro..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh?... Um livro?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Não é um livro..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["É um diário"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Por favor... Apenas devolvam..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Um diário... Um item muito importente..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tomem..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu quero trocar isso pelo diário do Linus"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["E o que seria isso?"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uma carta de amor..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Uma!!-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Uma carta?! De amor?!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim... Uma carta que eu escrevi para uma pessoa que eu amo muito..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uma pessoa que eu morreria por ela..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uma pessoa que eu escutaria a voz até que a ultima estrela brilhasse no céu..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Que patético!... Ambos se quer tem o mesmo valor-"]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_julia],
							[scr_cutscene_variable,variable.normal,o_julia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_jasenska],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["QUE DROGA, JULIA, CALA A BOCA!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["EU sou a Dama de pétalas e VOCÊ é a Dama de Espinhos"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Lembre-se que você está ABAIXO DE MIM na Hierarquia!!"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["Sim senhora"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_boris,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_oliver,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_noah,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_sofia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ophelia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_lorie,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_danica,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_olivia,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você realmente quer trocar essa carta por esse diário?..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["O que?! BunBun-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se isso fizer Linus feliz"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, não alimente esse desejo deles!"]],
							[scr_cutscene_move_character,o_bunbun,655,442,false,1,true,true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Aqui..."]],
							[scr_cutscene_item,o_bunbun,item.love_letter,[-1,-1],false],
							[scr_cutscene_item,o_bunbun,-1,[item.linus_diary,1],true],
							[scr_cutscene_wait,2],
							[scr_cutscene_move_character,o_bunbun,592,445,false,1,true,false],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Bom..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Obrigada..."]],
							[scr_cutscene_wait,2],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_jasenska,"direction",270],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_jasenska,"direction",0],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Laszlo..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["S-Sim"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Sua divida não foi anulada, porém sim reduzida"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["UH?! Mas!-"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Basta, BunBun"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Julia foi hostil e extremamente severa"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Mas ela está certa de uma coisa..."]],
							[scr_cutscene_variable,variable.normal,o_jasenska,"ppl_looking_to",true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você é intrometido... E vive tentando ajudar os outros e falhando"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["BunBun, seja mais egoísta, caso o contrário você apenas irá machucar ainda mais as pessoas"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Assim como você machucou o Laszlo... E o Linus..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Você se propõe a fazer apenas uma coisa e ainda assim é falho nessa única coisa que deveria fazer"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Se realmente você deseja ajudar... Saia..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_jasenska,["Saia desse quarto e entenda que você não é bem vindo aqui"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Entendo..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... Você está certa"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Meu trabalho aqui está completo"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_bunbun],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
							[scr_cutscene_move_character,o_bunbun,395,442,false,1,true,true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Só vamos embora.... Por favor..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["BunBun..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",false],
							[scr_cutscene_variable,variable.normal,o_petter,"direction",0],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Vocês são horríveis!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Horríveis, horríveis, horríveis!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A Hierarquia Rosa é a pior coisa que aconteceu nessa casa!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["E eu odeio cada minuto que eu passei na Hierarquia Rosa!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["O BunBun é incrível e ele sim me ajudou!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["E eu não conseguiria sem o BunBun!..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Eu... Eu não teria coragem sem ele..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Se ele é intromedito então eu também sou!"]],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",true],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",180],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
							[scr_cutscene_wait,1.5],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Só vamos embora daqui..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_petter,"petter",0],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",true],
							[scr_cutscene_wait,1.5],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eles não merecem nem uma palavra..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Desculpe, BunBun... Apenas vamos embora daqui..."]],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",true],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh-hum"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_bunbun,395,563,false,1,true,true],[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
							[scr_cutscene_room_goto,rm_corridors,true,false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"x",1031],
							[scr_cutscene_variable,variable.normal,o_bunbun,"y",312],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_refresh_party_member,true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
							[scr_cutscene_variable,variable.normal,o_camera,"y",328],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_camera,"x",1031],
							[scr_cutscene_variable,variable.normal,o_camera,"y",328],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,1031,328],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_bunbun,1031,328,false,1,true,true],
							[scr_cutscene_refresh_party_member,false],
							[scr_cutscene_wait,1.5],
							[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,1031,328],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",false],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",false],
							[scr_cutscene_move_character,o_linus,-24,0,true,1,true,true],
							[scr_cutscene_variable,variable.normal,o_linus,"direction",0],
							[scr_cutscene_move_character,o_petter,0,24,true,1,true,true],
							[scr_cutscene_move_character,o_petter,24,0,true,1,true,true],
							[scr_cutscene_variable,variable.normal,o_petter,"direction",135],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh, BunBun... Você está bem? O que eles disseram para você foi crueldade extrema!"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu tenho que concordar, BunBun... Foi extremamente maldoso o que eles falaram"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Acho que sim... Mas Eles estavam certos"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se eu não tivesse me intrometido, o Laszlo e nem você teriam sido afetados..."]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah! Não BunBun! Você foi quem me ajudou a contar o que eu sinto para a Mamãe e para o Tio Big B!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Se você é um intrometido, então quero ser intrometido como você!"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu também, BunBun"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Se você não ajuda ninguém, como eles dizem, então não há ninguém que ajude"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Até por que os próprios Omnis foram intrometidos"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["E agora temos um lugar para nos abrigar da guerra"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Mas bem... Falando em ser intrometido"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vamos lá falar sobre o Tio Antony, com a Mamãe e o Tio Big B"]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah! É verdade! Eu tinha me esquecido por completo!!"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, ok ok..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E... Obrigado por isso"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Não se preocupe, BunBun, apenas vamos terminar com essa parte"]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ok, coelhamigo?"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ok, coelhamigo..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_petter,"ppl_flowing",true],
							[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vocês inventam cada coisa"]],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_bars,true,false]
						]
					]
				]
			]
			
			complete_cutscene=[
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true]
			];
			#endregion
		}
		break;
}