non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_b_bedroom_3,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",571],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_variable,variable.normal,o_camera,"x",571],
	[scr_cutscene_variable,variable.normal,o_camera,"y",441],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,571,441,false,1,true,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
];
switch global.day{
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto de Linus, Tomas, James e Rubbert Busca por algo?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Não não, só tô explorando mesmo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tendi tendi... Já parou para pensar que eles são os únicos que não andam com suas duplas?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, bom, tecnicamente não estamos obrigados a ficar o tempo todo com nossas duplas, mas você tem razão"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eles quase não ficam juntos, O Tomas sempre está longe do Linus e o Rubbert parece que tem medo do James"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu diria que o Rubbert gosta de ficar sozinho também"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tem isso também!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bom! Vamos lá tomar café! Eu to com fome!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ok ok!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][3]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.mother_list],
				[-1,quest_type.have_item,item.uncle_spices],
			]
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não acredito que a Mamãe vai estar no quarto de uma das crianças..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Certeza?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim e por que motivo ela estaria?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Por que ela é nossa mãe e sempre nos ajuda com tudo! Ela quem nos ensinava a arrumar a cama, bobo"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok, você tem um ponto, mas ainda assim, ela não vai estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá bom..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto do Tio Big B não é aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, eu sei, apenas pensei que ele pudesse estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E por que raios ele estaria em um quarto de uma das crianças?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele sempre se certifica do bem estar de todos aqui!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Chorei 5 unidades de lágrimas, vamos logo para o quarto dele"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bobo..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Depois você vê o que tem nas gavetas do povo, vamos entregar os temperos para a Mamãe!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["QUE?! Eu não vejo o que tem nas gavetas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vê sim! Você é todo curioso!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não!... Na realidade sim, sou curioso... MAS EU NÃO VEJO O QUE TEM NAS GAVETAS!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][4]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.love_letter],
				[-1,quest_type.talk_to,o_noah],
				[-1,quest_type.talk_to,o_hellen],
				[-1,quest_type.have_item,item.noah_gift],
			];
			complete_cutscene=[]
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... BunBun... Esse não é meu quarto..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele tem memória de curto prazo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você é quem tem memória de curto prazo!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Então vamos logo para o quarto da Hellen!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá tá..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O 45 estaria aqui?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu tenho certeza que vi ele no andar de baixo.."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh? Pensei que ele estava aqui, vamos lá então"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos nessa!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[2]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["A Wendy não está aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh? Como você sabe?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ela gosta de ficar lendo no quarto dela, depois de brincar lá fora..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, bom... Tudo bem, vamos lá então!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[3]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ainda temos que pegar o presente com o 45"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh! É verdade!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Se não sou eu"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, Não seja assim!..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O Fritz está lá em baixo..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Fica calma, já, respira, ok?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Falar é fácil!... Meu Deus, que medo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu sei!! Logo logo será eu!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][5]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.someone_party,o_petter],
				[-1,quest_type.talk_to,o_bunbun],
				[-1,quest_type.talk_to,o_door_2],
				[-1,quest_type.someone_party,o_linus],
				[-1,quest_type.have_item,item.linus_diary],
				[-1,quest_type.talk_to,o_linus]
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_b_bedroom_3,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",571],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",571],
				[scr_cutscene_variable,variable.normal,o_camera,"y",441],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,571,441,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_b_bedroom_3,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",571],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",571],
				[scr_cutscene_variable,variable.normal,o_camera,"y",441],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,571,441,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[2]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_petter],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah... BunBun..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh? Sim, Petter?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Podemos falar com a Mamãe?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, claro que sim, desculpe, Petter!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Apenas achei que ela estaria aqui dentro"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh, bom... A última viz que vi ela, ela estava na cafeteria..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Pois é lá mesmo que nós vamos!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[3]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_instance_create,746,237,"Instances_People_2",o_linus],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_petter],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah... BunBun..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh? Sim, Petter?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Posso... Posso eu falar com o Linus... Por favor?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Claro que sim!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Qualquer coisa eu estou aqui, tudo bem?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh-hum... Obrigado, BunBun..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_linus],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não se preocupe com isso, Petter! Vamos apenas-"]],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Oh! Vocês dois ai"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah!... Sim... Ah, Linus, podemos falar contigo um momento?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Claro claro... Até por que eu queria falar com vocês"]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Com o BunBun em específico..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eh?! Eu? Aconteceu algo?...."]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Na realidade sim... Aconteceu..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Você estava brincando de esconde-esconde com a Hierarquia Rosa hoje, né?..."]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Sim... Eu brinquei com eles sim... Eles fizeram algo?"]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sim... Eles pegaram algo de mim... Algo importante"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["E eu quero de volta"]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Eu sinto muito mesmo, Linus!! Eu não queria que chegasse a esse ponto"]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Não tem problema, BunBun..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu só quero de volta..."]],
				[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_petter],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_petter],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah! Desculpe, Petter, o que você queria falar comigo?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah!... Sim... Sobre isso... É que...."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Eu queria saber se o Tio Antony pega no seu pé também..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Eu já vi ele falando contigo uma vez, então achei melhor eu perguntar..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Oh... Bom, sim, na realidade sim, ele pega no meu pé, as vezes"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu não me incomodo tanto, mas quando é com o James, isso me deixa mais bravo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Aconteceu algo?..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_petter],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["É que... Eu acabei de falar com a Mamãe e com o Tio Big B sobre o Tio Antony e como ele fica pegando no meu pé..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["E eu pensei que seu depoimento poderia nos ajudar..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Claro, eu to dentro"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu só vou pegar minhas coisas com a Hierarquia Rosa"]],
				[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_petter],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A gente vai com você, se não tiver problemas..."]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah... Não não, não se preocupe, eu só vou lá, pego e já encontro com vocês"]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não... O único motivo pelo qual eles pegaram algo de ti, foi por que ele violou uma regra, e eu estava envolvido..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Isso tem haver com a brincadeira de esconde-esconde"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Desculpe de verdade, Linus, não queria que chegasse a esse ponto"]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_linus],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu já imaginava, na realidade..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ugh... Eu odeio as regras da Hierarquia Rosa..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Tá tudo bem, BunBun... Só vamos lá pegar o que é meu..."]],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_petter,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",false],
				[scr_cutscene_new_party_member,o_linus],
				[scr_cutscene_move_character,o_bunbun,0,8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[4]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, depois vemos isso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vamos apenas recuperar o que é meu, por favor..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro, desculpe"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[5]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, depois vemos isso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vamos apenas recuperar o que é meu, por favor..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro, desculpe"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A Mamãe não está aqui, BunBun, não se lembra?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro, desculpe"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah! N-Não se preocupe!..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Apenas vamos até a Mamãe para terminar com isso..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			#endregion
		}
		break;
}