if(global.event[0][2]==progress.non_complete){
	quest_array=[
		[0,quest_type.talk_to,o_boris],
	];
	complete_cutscene=[];
	non_complete_cutscene[0]=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1152,572,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
		[scr_cutscene_move_character,o_laszlo,1181,589,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["..."]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_boris,["..."]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Nós..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Te achamos... Boris..."]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["Não"],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh, sim, te achamos..."]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["..."],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_boris,["Tá bom..."],-1,[-1,[s_boris_casual_hide_n_seek_idletalk_1],[s_boris_casual_hide_n_seek_idletalk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
		[scr_cutscene_variable,variable.normal,o_boris,"x",659],
		[scr_cutscene_variable,variable.normal,o_boris,"y",593],
		[scr_cutscene_variable,variable.normal,o_boris,"ppl_act_state",ppl_act.npc],
		[scr_cutscene_variable,variable.normal,o_boris,"ppl_talked",true],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que foi isso?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Foi o Boris"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum... Justo"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ele é a minha dupla, já estou acostumado com ele"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Sinto muito?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não não! Eu gosto dele assim!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Tudo bem!!"]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	];
}