if(global.event[0][2]==progress.non_complete){
	quest_array=[
		[0,quest_type.talk_to,o_julia],
	]
	complete_cutscene=[];
	non_complete_cutscene[0]=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,212,584,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
		[scr_cutscene_move_character,o_laszlo,256,584,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",90],
		[scr_cutscene_wait,1],
		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_intro],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Te achamos, Julia!...."]],
		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_1],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["...."]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Foi um bom esconderijo, Dama de Espinhos..."]],
		[scr_cutscene_animation_sprite,o_julia,[s_julia_casual_hide_n_seek_idle_1],[s_julia_casual_hide_n_seek_idle_2],false,true,[.35,.2]],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_julia,["...."]],
		[scr_cutscene_wait,1],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
		[scr_cutscene_variable,variable.normal,o_julia,"x",621],
		[scr_cutscene_variable,variable.normal,o_julia,"y",552],
		[scr_cutscene_variable,variable.normal,o_julia,"ppl_act_state",ppl_act.npc],
		[scr_cutscene_variable,variable.normal,o_julia,"ppl_talked",true],
		[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
		[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Que clima..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não fica assim!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eles não aplicar um castigo em você, eu prometo em conversar com eles!!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Não é sobre isso..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh Tudo bem..."]],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
		[scr_cutscene_instance_destroy_nearst,204,547,o_cutscene_trigger_3],
	];
}