non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_g_bedroom_3,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",652],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_variable,variable.normal,o_camera,"x",652],
	[scr_cutscene_variable,variable.normal,o_camera,"y",441],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,652,441,false,1,true,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
];
switch global.day{
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto da Wendy, Clara, Amanda e Grettel... Busca por alguma coisa?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Não não, só tô explorando mesmo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok... Podemos tomar café?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro... Mas Todd..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["É ela?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["UH?! Como assim?!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Só queria saber se é a-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não, não é ninguém só vamos tomar café logo!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee! Ok! Vamos lá!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][3]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.mother_list],
				[-1,quest_type.have_item,item.uncle_spices],
			]
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não acredito que a Mamãe vai estar no quarto de uma das crianças..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Certeza?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim e por que motivo ela estaria?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Por que ela é nossa mãe e sempre nos ajuda com tudo! Ela quem nos ensinava a arrumar a cama, bobo"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok, você tem um ponto, mas ainda assim, ela não vai estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá bom..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto do Tio Big B não é aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, eu sei, apenas pensei que ele pudesse estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E por que raios ele estaria em um quarto de uma das crianças?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele sempre se certifica do bem estar de todos aqui!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Chorei 5 unidades de lágrimas, vamos logo para o quarto dele"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bobo..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Depois você vê o que tem nas gavetas do povo, vamos entregar os temperos para a Mamãe!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["QUE?! Eu não vejo o que tem nas gavetas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vê sim! Você é todo curioso!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não!... Na realidade sim, sou curioso... MAS EU NÃO VEJO O QUE TEM NAS GAVETAS!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][4]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.love_letter],
				[-1,quest_type.talk_to,o_noah],
				[-1,quest_type.talk_to,o_hellen],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... BunBun... Esse não é meu quarto..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele tem memória de curto prazo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você é quem tem memória de curto prazo!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Então vamos logo para o quarto da Hellen!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá tá..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Não acho que o o 45 vá estar ai no quarto delas..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["É o cabeção!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!... Desculpe, desculpe!..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Hum... Se bem que..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[2]=[
				[scr_cutscene_variable,variable.normal,o_hellen,"ppl_talked",true],
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,0,1],
				[scr_cutscene_room_goto,rm_g_bedroom_3,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",652],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",652],
				[scr_cutscene_variable,variable.normal,o_camera,"y",441],
				[scr_cutscene_instance_create,553,375,"Instances_People_2",o_wendy],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_idle_1],[s_wendy_casual_loveletter_idle_1],false,true,[.2,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_audio_stop,audio_type.bgm,bgm_008],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,652,441,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_move_character,o_bunbun,652,396,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				[scr_cutscene_move_character,o_hellen,652,390,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oi, Wendy"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Olá, BunBun... Olá, Todd..."],-1,[[-1],[s_wendy_casual_loveletter_idle_1],[s_wendy_casual_loveletter_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Olá, Hellen"],-1,[[-1],[s_wendy_casual_loveletter_idle_3],[s_wendy_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_idle_1],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Bom..."]],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_idle_2],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nós viemos para pedir sua ajuda!"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Elabore"],-1,[[-1],[s_wendy_casual_loveletter_idle_2],[s_wendy_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu queria pedir sua ajuda para..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu queria pedir sua ajuda para ficar mais..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bonita..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_idle_3],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Eu posso ajudar você com isso, Hellen..."],-1,[[-1],[s_wendy_casual_loveletter_idle_3],[s_wendy_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Porém eu peço que Todd e BunBun saiam..."],-1,[[-1],[s_wendy_casual_loveletter_idle_2],[s_wendy_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Hum?... Mas os dois estão me ajudando..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Tudo bem, afável, mas isso é algo mais íntimo..."],-1,[[-1],[s_wendy_casual_loveletter_idle_3],[s_wendy_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Uma coisa apenas de garotas..."],-1,[[-1],[s_wendy_casual_loveletter_idle_3],[s_wendy_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sem problemas!! Entendemos bem a situação!!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Grata pela decência..."],-1,[[-1],[s_wendy_casual_loveletter_idle_1],[s_wendy_casual_loveletter_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh... Uh-hum!..."]],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_idle_2],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vamos, Todd!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah!... D-Desculpe, BunBun"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah~ Apenas você, grandão... Vamos..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["T-Tá!..."]],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_move_character,o_bunbun,652,541,false,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Bom..."],-1,[[-1],[s_wendy_casual_loveletter_idle_3],[s_wendy_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Hellen..."],-1,[[-1],[s_wendy_casual_loveletter_idle_3],[s_wendy_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["S-Sim?"]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_book_1],[s_wendy_casual_loveletter_book_3],false,true,[.2,.3]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_book_2],[s_wendy_casual_loveletter_idle_4],false,true,[.2,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Bom... Agora que eles se foram..."],-1,[[-1],[s_wendy_casual_loveletter_idle_4],[s_wendy_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Poderia me explicar um pouco melhor a situação?..."],-1,[[-1],[s_wendy_casual_loveletter_idle_4],[s_wendy_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["B-Bom..."]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu... Queria ser um pouco mais bonita..."]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu queria ser mais bonita para Fritz..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["E é por que eu o amo..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O fritz é alguém tão inteligente e formidável, me sinto mal por ser como sou, perto dele..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Uma pessoa tão douta necessita de alguém, do mesmo nível, perto dele..."]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["E é o que eu quero..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu quero estar perto dele... Mas não sinto que..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Que não sou o suficiente..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Hellen..."],-1,[[-1],[s_wendy_casual_loveletter_idle_4],[s_wendy_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Uh... Sim?"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Dentro dessa comoda, por debaixo das minhas roupas, há um pequeno estojo, traga ele para mim"],-1,[[-1],[s_wendy_casual_loveletter_idle_4],[s_wendy_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah!... Claro"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.5],
				[scr_cutscene_move_character,o_hellen,559,390,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Aqui"]],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_makeup_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Obrigada... Sente-se, por favor"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_1],[s_wendy_casual_loveletter_makeup_idle_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Claro"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_move_character,o_hellen,577,390,false,1,true,true],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",315],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_makeup_idle_3],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_loveletter_getting_up],[s_hellen_casual_loveletter_idle_6],false,true,[.3,.2]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Então você está fazendo isso inteiramente por que gosta dele, né?"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Não \"unicamente\"... Mas posso dizer que um dos motivos principais é por que eu gosto dele..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Hum... Bom... Você sabe o que é isso, né?"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Ah... Bom... Me parece maquiagem..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["HeeHee, te parece por que é!"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Fecha os olhos"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Oh... Ok..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_idle_0],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.2,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["As garotas mais velhas usam isso para ficarem mais bonitas"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Uh! E como você conseguiu isso?"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Bom... Eu recebi de presente da Tia Anzhelika"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Isso é permitido aqui dentro da casa?"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Não, não é"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Então por que você tem isso?"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Por que, 1, o mundo não se importa se você faz o certo ou errado, com tanto que você tenha resultados"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Se você esconde bem, ou tem dinheiro o suficiente para pagar alguém que faça, então tudo bem, você ainda é alguém exemplar"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["E 2..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Hellen, nós somos mulheres... Em todas as histórias daqui de casa, você se lembra de uma história onde a mulher foi protagonista por sua inteligência?"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Uh... Não... Mas-"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Exato, Hellen..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Estamos jogando um jogo, que nem queriamos jogar, que ainda não nos deixa jogar dentro das regras, pois elas nos impedem"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.2,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você já passou por algo?..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Não... Pois aqui dentro de casa é diferente... Mas a Tia Anzhelika e a Mamãe já falaram sobre... Às vezes eu ouvia, sem querer, elas conservando sobre"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Então como você sabe que vai ser assim?"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Pois em todos os livros, em todas as histórias que nos contam, as mulheres são sempre lindas..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Como você... Sempre linda..."],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você me acha linda?..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Mais do que você pensa..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Isso é irônico..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Eu apenas uso meu laço por que eu acho você linda..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você sempre chama a atenção por onde passa... Claro, em um bom sentido"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_wendy,"ppl_custom_img_spd",0],
				[scr_cutscene_variable,variable.normal,o_wendy,"image_speed",0],
				[scr_cutscene_variable,variable.normal,o_wendy,"image_index",0],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_wendy,"sprite_index",s_wendy_casual_loveletter_makeup_idle_3],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Obrigada, Hellen... Vindo de ti, é uma honra ouvir isso"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_idle_0],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.2,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["A realidade... É que eu amo muito todas vocês... Todas vocês..."],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Todas as garotas que entraram e saíram dessa casa"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Eu tenho essa personalidade mais rude apenas para deixar os garotos longe de mim"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Uh?... Mas e o Tomas?"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Ah... Alguns garotos salvam... O Tomas, Fritz, Linus, BunBun... Laszlo nem tanto... "],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["E o Todd?"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["O que tem ele?"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você não acha que ele possa ser diferente?"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Pode ser... Ele é fofo"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["HeeHee..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Nunca pensei que eu iria te conhecer desse lado, Wendy..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Sabe... A Tia me ensinou uma palavra alguns anos atrás..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Sororidade... Sabe o que significa?"],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Não... Não tenho a menor ideia..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Amizade... Irmandade feminina..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_0],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Em um mundo onde a smulheres, além de serem tratadas de formas injustas, ainda culpabilizam umas as outras..."],-1,[[s_wendy_casual_loveletter_makeup_talk_1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],true,false,[.25,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Sororidade... É isso o que precisamos, Hellen, querida"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_2],[s_wendy_casual_loveletter_makeup_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_animation_sprite,o_wendy,[s_wendy_casual_loveletter_makeup_end],[s_wendy_casual_loveletter_makeup_idle_3],false,true,[.25,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Sororidade... Gostei da palavra..."],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Guarde ela em seu coração..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["O que me diz?"],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Ah!... Ficou incrível!!"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você é incrível nisso, Wendy!"],-1,[[-1],[s_hellen_casual_loveletter_idle_6],[s_hellen_casual_loveletter_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Obrigada, de verdade... Mas..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_wendy,["Posso dar uma recomendação?..."],-1,[[-1],[s_wendy_casual_loveletter_makeup_idle_3],[s_wendy_casual_loveletter_makeup_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_corridors,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",857],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",309],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_hellen,"x",888],
				[scr_cutscene_variable,variable.normal,o_hellen,"y",262],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",901],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",309],
				[scr_cutscene_room_goto,rm_corridors,true,false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",857],
				[scr_cutscene_variable,variable.normal,o_camera,"y",309],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,888,278],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_hellen,888,278,false,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,888,278],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh!! Hellen!..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você está linda!..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Sim sim!... Poxa... A Wendy realmente sabe o que faz"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee!... Ai garotos, vamos logo ver se o 45 já tem o presente!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[3]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ainda temos que pegar o presente com o 45"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh! É verdade!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Se não sou eu"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, Não seja assim!..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O Fritz está lá em baixo..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Fica calma, já, respira, ok?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Falar é fácil!... Meu Deus, que medo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu sei!! Logo logo será eu!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][5]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.someone_party,o_petter],
				[-1,quest_type.talk_to,o_door_1],
				[-1,quest_type.talk_to,o_bunbun],
				[-1,quest_type.talk_to,o_door_2],
				[-1,quest_type.someone_party,o_linus],
				[-1,quest_type.have_item,item.linus_diary],
				[-1,quest_type.talk_to,o_linus],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_g_bedroom_3,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",652],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",652],
				[scr_cutscene_variable,variable.normal,o_camera,"y",441],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,652,441,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[1]=non_complete_cutscene[0];
			non_complete_cutscene[2]=non_complete_cutscene[0];
			non_complete_cutscene[3]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh... BunBun... Você acha que a Mamãe está aqui mesmo?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["É que eu me lembro de ter visto ela na cafeteria"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Nesse caso, vamos até lá!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[4]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh... BunBun... Esse não é o quarto do Linus"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não? Jurava que sim..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[5]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, depois vemos isso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vamos apenas recuperar o que é meu, por favor..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro, desculpe"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[6]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A Mamãe não está aqui, BunBun, não se lembra?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro, desculpe"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah! N-Não se preocupe!..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Apenas vamos até a Mamãe para terminar com isso..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}
		break;
}