non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_big_b_bedroom,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",543],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",190],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_variable,variable.normal,o_camera,"x",689],
	[scr_cutscene_variable,variable.normal,o_camera,"y",215],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,906,328],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,543,217,false,1,true,true],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,906,328],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false],
];
switch global.day{
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["A porta está trancada"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Queria ver o jardim do Tio Big B"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mais tarde ele vai estar ai e então você vai poder ficar ai dentro"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Isso me lembra o Dhan, ele gostava muito de ficar ai também"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim! Principalmente depois do café, o Marco sempre ficava mostrando pedras para ele"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Os dois eram uma boa dupla"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim! Espero ver eles do lado de fora!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Digo o mesmo"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
		#endregion
		}else if(global.event[0][3]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.mother_list],
				[-1,quest_type.have_item,item.uncle_spices],
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun, já fizemos o que tinhamos que fazer"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos lá entregar os temperos para a Mamãe!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				//[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_todd],
				//[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				//[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_bunbun],
				//[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun, para onde você está indo?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, eu só queria ver as flores do Tio Big B"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mais tarde nós vamos, eu prometo, ok?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tudo bem"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,0,1],
				[scr_cutscene_room_goto,rm_big_b_bedroom,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",543],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",190],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",689],
				[scr_cutscene_variable,variable.normal,o_camera,"y",215],
				[scr_cutscene_instance_create,689,215,"Instances_People_1",o_uncle_bruce],
				[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_bedroom_1_idle_1],[s_uncle_bruce_casual_bedroom_1_idle_1],false,true,[1,.2]],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_audio_stop,audio_type.bgm,bgm_008],
				[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_bedroom_1_sadness],[s_uncle_bruce_casual_bedroom_1_idle_2],false,true,[.1,.2]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["....."]],
				[scr_cutscene_audio_play,audio_type.sfx,sfx_007,false,0,1],
				[scr_cutscene_wait,3],
				[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_bedroom_1_putting_photo_down],[s_uncle_bruce_casual_bedroom_1_idle_3],false,true,[.1,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_uncle_bruce,[s_uncle_bruce_casual_bedroom_1_getting_up_1],[s_uncle_bruce_casual_idle_1_left],false,true,[.1,.2]],
				[scr_cutscene_variable,variable.normal,o_uncle_bruce,"direction",180],
				[scr_cutscene_variable,variable.normal,o_uncle_bruce,"ppl_act_state",ppl_act.npc],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Pode entrar..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_camera,543+24,217,false,1,false,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,689,217],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,543,217,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_move_character,o_bunbun,24,0,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,689,217],
				[scr_cutscene_wait,1],
				[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,1,0],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Oh! BunBun! Todd, a dupla dinâmica!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["O que trazem vocês aqui?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! A Mamãe nos pediu para pegar alguns temperos com o senhor!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Ah... Ela pediu..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Bom! Por mim tudo bem!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Se bem que...."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Venham aqui"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_move_character,o_uncle_bruce,516,215,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_move_character,o_uncle_bruce,516,283,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_move_character,o_bunbun,540,284,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_move_character,o_bunbun,540,284,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_move_character,o_todd,495,284,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_big_b_bedroom_getting_up_1_1],[s_bunbun_casual_big_b_bedroom_idle_1_1],false,true,[.2,.2]],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_big_b_bedroom_getting_up_1_1],[s_todd_casual_big_b_bedroom_idle_1_1],false,true,[.2,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_camera,621,441,false,1,false,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_camera,540,284,false,1,false,false],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Bem, como vocês sabem, eu tenho bastante plantas pela casa"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Plantas de vários tipos"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Legumes, verduras, temperos..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["E flores!!"],-1,[[-1],[s_bunbun_casual_big_b_bedroom_idle_2_1],[s_bunbun_casual_big_b_bedroom_talk_2_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["HaaHaa... E flores também!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["E por que flores, Tio?"],-1,[[-1],[s_todd_casual_big_b_bedroom_idle_2_1],[s_todd_casual_big_b_bedroom_talk_2_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Por que flores?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Elas são bonitas"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Apenas por isso?"],-1,[[-1],[s_todd_casual_big_b_bedroom_idle_2_1],[s_todd_casual_big_b_bedroom_talk_2_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Uh-Hum"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Faz sentido"],-1,[[-1],[s_todd_casual_big_b_bedroom_idle_1_1],[s_todd_casual_big_b_bedroom_talk_1_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Realmente faz"],-1,[[-1],[s_bunbun_casual_big_b_bedroom_idle_1_1],[s_bunbun_casual_big_b_bedroom_talk_1_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Bom, nessa vida, nada é de graça"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["E eu vou entregar os temperos para vocês, apenas quando vocês terminarem de aguar essas plantas"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Oshe, meu Deus, mas viemos aqui por causa da Mamãe"],-1,[[-1],[s_todd_casual_big_b_bedroom_idle_2_1],[s_todd_casual_big_b_bedroom_talk_2_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Sim, eu sei"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Então por que-"],-1,[[-1],[s_todd_casual_big_b_bedroom_idle_2_1],[s_todd_casual_big_b_bedroom_talk_2_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["A gente vai aguar as plantas, Tio!"],-1,[[-1],[s_bunbun_casual_big_b_bedroom_idle_2_1],[s_bunbun_casual_big_b_bedroom_talk_2_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["É assim que se fala, BunBun!"]],
				[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_big_b_bedroom_getting_down_1_1],[s_bunbun_casual_idle_1_down],false,true,[.2,.2]],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_big_b_bedroom_getting_down_1_1],[s_todd_casual_idle_1_down],false,true,[.2,.2]],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",315],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Ali embaixo, na estante, há um regador, ele já está com água que utilizei de manhã, será o suficiente"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Reguem e os temperos serão de vocês!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Pode deixar, Tio Big B!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_bruce,["Se precisarem de algo, estarei ali embaixo, podando algumas plantas, tudo bem?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Pode deixar!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_uncle_bruce,560,283,false,1,true,true],
				[scr_cutscene_move_character,o_uncle_bruce,672,395,false,1,true,true],
				[scr_cutscene_move_character,o_uncle_bruce,696,395,false,1,true,true],
				[scr_cutscene_move_character,o_uncle_bruce,696,426,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_move_character,o_uncle_bruce,690,426,false,1,true,true],
				[scr_cutscene_set_path,o_uncle_bruce,p_undle_big_b_bedroom_1,path_action_restart,true,path_act.state],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][4]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Depois tu fala com o Tio Big B"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Temos outras coisas para resolver"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][5]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.someone_party,o_petter],
				[-1,quest_type.talk_to,o_door_1],
				[-1,quest_type.talk_to,o_bunbun],
				[-1,quest_type.talk_to,o_door_2],
				[-1,quest_type.someone_party,o_linus],
				[-1,quest_type.have_item,item.linus_diary],
				[-1,quest_type.talk_to,o_linus],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_corridors,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",543],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",190],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",543],
				[scr_cutscene_variable,variable.normal,o_camera,"y",217],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,906,328],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,543,217,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,906,328],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[1]=non_complete_cutscene[0];
			non_complete_cutscene[2]=non_complete_cutscene[0];
			non_complete_cutscene[3]=non_complete_cutscene[0];
			non_complete_cutscene[4]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah... BunBun... Podemos ir falar com o Linus?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, desculpe, Petter"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[5]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, podemos não envolver os tios nisso?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você tem certeza? Se a Hierarquia Rosa pegou algo, eles precisam saber"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Eu sei... Só que... É vergonhoso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Bom... Ok...."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[6]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["O Tio Big B não está no quarto dele, ele está na cafeteria com a Mamãe"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! É verdade!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Bom, vamos lá falar com eles estão"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
		}
		#endregion
		break;
}