if(global.event[0][3]==progress.non_complete){
	quest_array=[
		[0,quest_type.talk_to,o_edgar]
	];
	non_complete_cutscene[0]=[
		[scr_cutscene_variable,variable.normal,o_edgar,"ppl_talked",true],
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1229,415,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
		[scr_cutscene_move_character,o_todd,1179,415,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá, Edgar!!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oi, Edgar..."]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Olá, pequeno BunBun"],-1,[-1,[s_edgar_casual_chill_1_idle_3],[s_edgar_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["E ai, Todd?"],-1,[-1,[s_edgar_casual_chill_1_idle_1],[s_edgar_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Como estão a grandiosa dupla?"],-1,[-1,[s_edgar_casual_chill_1_idle_1],[s_edgar_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_edgar,"sprite_index",s_edgar_casual_chill_1_idle_2],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["A gente tá bem, e ocupados"]],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Anda, BunBun, temos mais o que fazer..."]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["HeeHee, calma lá, Todd"],-1,[-1,[s_edgar_casual_chill_1_idle_2],[s_edgar_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Apenas perguntei como vocês estão"],-1,[-1,[s_edgar_casual_chill_1_idle_2],[s_edgar_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_edgar,"sprite_index",s_edgar_casual_chill_1_idle_3],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A gente está bem, Edgar, apenas resolvendo umas coisinhas"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Oh! E que coisinhas seriam essas?"],-1,[-1,[s_edgar_casual_chill_1_idle_3],[s_edgar_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_edgar,"sprite_index",s_edgar_casual_chill_1_idle_5],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Coisa minha e do BunBun"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Ah sim sim"],-1,[-1,[s_edgar_casual_chill_1_idle_4],[s_edgar_casual_chill_1_talk_4]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Apenas cuide do BunBun, tudo bem?"],-1,[-1,[s_edgar_casual_chill_1_idle_5],[s_edgar_casual_chill_1_talk_5]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Ah! E você, BunBun"],-1,[-1,[s_edgar_casual_chill_1_idle_3],[s_edgar_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["se cuide, pequeno BunBun"],-1,[-1,[s_edgar_casual_chill_1_idle_4],[s_edgar_casual_chill_1_talk_4]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele está bem boas mãos!"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Não duvido de ti, apenas me preocupo com o BunBun"],-1,[-1,[s_edgar_casual_chill_1_idle_1],[s_edgar_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Obrigado..."]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Vamos, Todd"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Hump!"]],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	];
	complete_cutscene=[
		[scr_cutscene_variable,variable.normal,o_edgar,"ppl_talked",true],
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,1229,415,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
		[scr_cutscene_move_character,o_todd,1179,415,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Pequeno BunBun, Todd"],-1,[-1,[s_edgar_casual_chill_1_idle_1],[s_edgar_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Hump..."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, Edgar?"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Terminaram essa coisinha que tinham mencionado?"],-1,[-1,[s_edgar_casual_chill_1_idle_3],[s_edgar_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_edgar,"sprite_index",s_edgar_casual_chill_1_idle_5],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Entendo..."],-1,[-1,[s_edgar_casual_chill_1_idle_4],[s_edgar_casual_chill_1_talk_4]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Quando estiverem entediados, podem vir falar comigo"],-1,[-1,[s_edgar_casual_chill_1_idle_2],[s_edgar_casual_chill_1_talk_2]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Farei meu melhor para não ser um pé no saco"],-1,[-1,[s_edgar_casual_chill_1_idle_3],[s_edgar_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!... Obrigado!"]],
		[scr_cutscene_variable,variable.normal,o_edgar,"sprite_index",s_edgar_casual_chill_1_idle_5],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mas não é preciso"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Você quem sabe, Todd"],-1,[-1,[s_edgar_casual_chill_1_idle_1],[s_edgar_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["Mas o convite está de pé para ti, BunBun"],-1,[-1,[s_edgar_casual_chill_1_idle_3],[s_edgar_casual_chill_1_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_edgar,"sprite_index",s_edgar_casual_chill_1_idle_5],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Como eu disse, não é preciso"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_edgar,["HeeHee, tudo bem!"],-1,[-1,[s_edgar_casual_chill_1_idle_1],[s_edgar_casual_chill_1_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	]
	
}