non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,x,y],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_house_ext_back,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",492],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",1496-16],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_variable,variable.normal,o_camera,"x",492],
	[scr_cutscene_variable,variable.normal,o_camera,"y",1496],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,492,1496],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,492,1496,false,1,true,true],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,492,1496],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
]

switch global.day{
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Quer saltar o café?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não sei se estou com tanta fome"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh? Você tem certeza?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, eu sou pequeno, meu estômago também é pequeno"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mais um motivo para irmos tomar café, para você comer, crescer e ficar grande"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá bom.."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][2]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Está desistindo de brincar?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não, por que?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Oh, é por que o limite é dentro da casa"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Claro, fora o porão e o terceiro andar"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Nesse caso!..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			#endregion
		}else if(global.event[0][3]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.mother_list],
				[-1,quest_type.have_item,item.uncle_spices],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun, a cozinha não fica aí... E você sabe"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Queria ver as outras crianças"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ué, mas você não fez sua checagem diária?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh, sim... Mas eu gosto de ver outras crianças brincando"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, depois vemos isso, BunBun!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O Tio e as outras crianças já entraram"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você não gosta de tomar um ar livre não?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não quando a Mamãe pede um favor!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá bom, tá bom!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Qual é, vamos entregar logo os temperos para a Mamãe!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ok ok"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			#endregion
		}else if(global.event[0][4]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu tenho quase certeza que não precisamos fazer nada ai fora"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu concordo com o Todd"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Desculpe"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			#endregion
		}else if(global.event[0][5]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.someone_party,o_petter],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_house_ext_back,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",492],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",1496],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",492],
				[scr_cutscene_variable,variable.normal,o_camera,"y",1496],
				[scr_cutscene_instance_create,460,1532,"Instances_People_1",o_petter],
				[scr_cutscene_animation_sprite,o_petter,[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_idle_1],false,true,[.2,.2]],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["...?"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,485,1532,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Petter?..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Ah... Oi, BunBun"],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Posso me sentar?"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Claro, a vontade..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_idle_1],false,true,[.2,.2]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_1],
				[scr_cutscene_wait,2],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_2],
				[scr_cutscene_wait,2],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_6],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Petter..."],-1,[[0],[s_bunbun_casual_sadness_idle_2],[s_bunbun_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Sim?..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["É sobre ele?..."],-1,[[0],[s_bunbun_casual_sadness_idle_2],[s_bunbun_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Sim..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,2],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_6],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["O que ele falou dessa vez?"],-1,[[0],[s_bunbun_casual_sadness_idle_6],[s_bunbun_casual_sadness_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_2],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["O de sempre..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Que sou um disperdicio pelo meu tamanho..."],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Como?..."],-1,[[0],[s_bunbun_casual_sadness_idle_2],[s_bunbun_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Sim..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["As vezes eu penso que talvez ele tenha razão..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Logo logo é a minha formatura, e eu vou ter que fazer algo para minha vida..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Há uma guerra do lado de fora..."],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["E eu preciso ser útil de alguma forma..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_2],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Foi ele quem te falou para ser útil?..."],-1,[[0],[s_bunbun_casual_sadness_idle_2],[s_bunbun_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Também..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Mas parte desse sentimento é meu... Eu realmente sinto que preciso ser útil..."],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas... Útil para ele ou para você mesmo?...."],-1,[[0],[s_bunbun_casual_sadness_idle_2],[s_bunbun_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Como assim, BunBun?..."],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu não posso simplesmente dizer para você não se importar com isso, até por que é uma solução muito leviana"],-1,[[0],[s_bunbun_casual_sadness_idle_6],[s_bunbun_casual_sadness_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas eu posso dizer que utilidade é algo relativo"],-1,[[0],[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_5],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["O que você quer dizer com isso?"],-1,[[0],[s_petter_casual_sadness_idle_5],[s_petter_casual_sadness_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Simples..."],-1,[[0],[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Para o Tio Antony, você pode ser inútil por não usar seu tamanho para ser um grande soldado"],-1,[[0],[s_bunbun_casual_sadness_idle_5],[s_bunbun_casual_sadness_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_4],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas para mim, você é tão útil, pois seus abraços sãos os melhores que eu já recebi"],-1,[[0],[s_bunbun_casual_sadness_idle_5],[s_bunbun_casual_sadness_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_5],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Claro, você pode dizer que algumas coisas são mais uteis que outras"],-1,[[0],[s_bunbun_casual_sadness_idle_6],[s_bunbun_casual_sadness_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Até por que não tem como comparar uma pessoa que abraça com um soldado"],-1,[[0],[s_bunbun_casual_sadness_idle_5],[s_bunbun_casual_sadness_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas sabe... O Tio Big B também é gigante e tem ótimos abraços"],-1,[[0],[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Isso não faz ele ser um inútil, faz?..."],-1,[[0],[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Oh... Eu..."],-1,[[0],[s_petter_casual_sadness_idle_5],[s_petter_casual_sadness_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu entendo o que você quer dizer, BunBun... Entendo mesmo... Mas..."],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Não é a mesma coisa..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_2],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Pra você... Pra você não é a mesma coisa..."],-1,[[0],[s_bunbun_casual_sadness_idle_2],[s_bunbun_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_5],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Pois você é uma das pessoas mais uteis que eu conheço"],-1,[[0],[s_bunbun_casual_sadness_idle_3],[s_bunbun_casual_sadness_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu já te falei que você me inspira?"],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["E-Eu?... Mas..."],-1,[[0],[s_petter_casual_sadness_idle_5],[s_petter_casual_sadness_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você é sempre bondoso e honesto! Sempre que pode ajuda a Mamãe com os bebês!"],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_4],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Me atrevo a dizer que você seria um ótimo Tio, se não um ótimo pai!"],-1,[[0],[s_bunbun_casual_sadness_idle_7],[s_bunbun_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_7],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu... Eu não esperava..."],-1,[[0],[s_petter_casual_sadness_idle_3],[s_petter_casual_sadness_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu não esperava nada disso vindo de ti, BunBun..."],-1,[[0],[s_petter_casual_sadness_idle_3],[s_petter_casual_sadness_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_7],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu não sei se você sabe, mas eu tenho orgulho da pessoa que você é..."],-1,[[0],[s_bunbun_casual_sadness_idle_3],[s_bunbun_casual_sadness_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Da pessoa que voocê se tornou!..."],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu só fico triste que você vai se formar e não sei qual vai ser a próxima vez que vou ver meu coelhamigo!"],-1,[[0],[s_bunbun_casual_sadness_idle_7],[s_bunbun_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Coelhamigo?..."],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["D-Desculpe! Eu falei em voz alta!... Mas..."],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu sempre quis te chamar assim! De Coelhamigo!"],-1,[[0],[s_bunbun_casual_sadness_idle_7],[s_bunbun_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_4],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Oh!..."],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Você e a Hellen... São coelhamigos?"],-1,[[0],[s_petter_casual_sadness_idle_4],[s_petter_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_7],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu nunca falei diretamente com ela sobre isso... Nem com ela, nem com a Jasenska ou Grettel, sobre esse termo"],-1,[[0],[s_bunbun_casual_sadness_idle_6],[s_bunbun_casual_sadness_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas eu gosto da ideia de nós sermos amigos coelhos!!"],-1,[[0],[s_bunbun_casual_sadness_idle_7],[s_bunbun_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Se você quiser, pode ser apenas eu e você por enquanto!!"],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_6],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Por que você é bondoso assim comigo?..."],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_7],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Por que você é uma das pessoas que mais amo nesse mundo!"],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Isso... É sério? Pensei que você fosse mais amigo do Todd"],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sou amigo de todos, nessa casa"],-1,[[0],[s_bunbun_casual_sadness_idle_7],[s_bunbun_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Mas sempre quis ter meus coelhamigos!!"],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Coelhamigos..."],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Coelhamigos..."],-1,[[0],[s_petter_casual_sadness_idle_6],[s_petter_casual_sadness_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["BunBun... Você pode me acompanhar?..."],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Claro! Do que você precisa?"],-1,[[0],[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu..."],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Eu quero sua companhia para me ajudar a contar para a Mamãe sobre o Tio Antony..."],-1,[[0],[s_petter_casual_sadness_idle_4],[s_petter_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_7],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah! Claro que sim, Petter!"],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_sadness_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Mas... Antes..."],-1,[[0],[s_petter_casual_sadness_idle_4],[s_petter_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim?"],-1,[[0],[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Me ajuda a buscar uma pelúcia minha?..."],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Pelúcia?..."],-1,[[0],[s_bunbun_casual_sadness_idle_1],[s_bunbun_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["O Tio Antony tirou ela de mim... Ele deve ter dado para outra cirança"],-1,[[0],[s_petter_casual_sadness_idle_2],[s_petter_casual_sadness_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Segundo ele, eu já estou grande demais para ter pelúcias..."],-1,[[0],[s_petter_casual_sadness_idle_1],[s_petter_casual_sadness_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_petter,"sprite_index",s_petter_casual_sadness_idle_7],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sem problemas, Petter! Te ajudo a buscar sua pelúcia! E então nós vamos falar com a Mamãe sobre o Tio Antony, ok?!"],-1,[[0],[s_bunbun_casual_sadness_idle_4],[s_bunbun_casual_sadness_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Claro claro..."],-1,[[0],[s_petter_casual_sadness_idle_6],[s_petter_casual_sadness_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_petter,["Obrigado... Coelhamigo!..."],-1,[[0],[s_petter_casual_sadness_idle_7],[s_petter_casual_sadness_talk_7]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_petter,[s_petter_casual_sadness_getting_up],[s_petter_casual_idle_1_down],false,true,[.2,.2]],
				[scr_cutscene_new_party_member,o_petter],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah... Esqueceu algo, BunBun?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não não, desulpe Petter"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Não se preocupe, BunBun"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,false,true],
			];
			#endregion
		}else if(global.event[0][6]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.someone_party,o_calina],
				[-1,quest_type.have_item,item.crayon],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_house_ext_back,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",492],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",1496-16],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",492],
				[scr_cutscene_variable,variable.normal,o_camera,"y",1496],
				[scr_cutscene_instance_create,461,1529,"Instances_People_1",o_vladmir],
				[scr_cutscene_instance_create,517,1522,"Instances_People_1",o_julian],
				[scr_cutscene_instance_create,471,1595,"Instances_People_1",o_paxton],
				[scr_cutscene_instance_create,507,1595,"Instances_People_1",o_gleb],
				[scr_cutscene_animation_sprite,o_vladmir,[s_vladmir_casual_crayon_idle_1],[s_vladmir_casual_crayon_idle_1],false,true,[10,.2]],
				[scr_cutscene_animation_sprite,o_julian,[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_idle_1],false,true,[10,.2]],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,492,1496],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,492,1496,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,492,1496],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,x,y],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_house_ext_back,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",492],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",1496-16],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_variable,variable.normal,o_camera,"x",492],
				[scr_cutscene_variable,variable.normal,o_camera,"y",1530],
				[scr_cutscene_instance_create,461,1529,"Instances_People_1",o_vladmir],
				[scr_cutscene_instance_create,517,1522,"Instances_People_1",o_julian],
				[scr_cutscene_instance_create,471,1595,"Instances_People_1",o_paxton],
				[scr_cutscene_instance_create,507,1595,"Instances_People_1",o_gleb],
				[scr_cutscene_animation_sprite,o_vladmir,[s_vladmir_casual_crayon_idle_3],[s_vladmir_casual_crayon_idle_3],false,true,[10,.2]],
				[scr_cutscene_animation_sprite,o_julian,[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_idle_1],false,true,[10,.2]],
				[scr_cutscene_set_path,o_paxton,p_paxton_crayon,1.5,path_action_restart,true,path_act.state],
				[scr_cutscene_set_path,o_gleb,p_gleb_crayon,1.5,path_action_restart,true,path_act.state],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Vamos vamos, força, Gleb!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Para já, chefe!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Vlad! Vlad! Vlad! Vlad!"],-1,[[-1],[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Fala, Julian"],-1,[[-1],[s_vladmir_casual_crayon_idle_1],[s_vladmir_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Nada... Eu gosto do seu nome"],-1,[[-1],[s_julian_casual_crayon_idle_3],[s_julian_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_julian,"sprite_index",s_julian_casual_crayon_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Obrigado, Julian"],-1,[[-1],[s_vladmir_casual_crayon_idle_1],[s_vladmir_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Mas foi você quem o escolheu"],-1,[[-1],[s_vladmir_casual_crayon_idle_2],[s_vladmir_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Sim, acho que fui eu sim"],-1,[[-1],[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Sim, foi você quem escolheu"],-1,[[-1],[s_vladmir_casual_crayon_idle_1],[s_vladmir_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Fui eu?!"],-1,[[-1],[s_julian_casual_crayon_idle_2],[s_julian_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Então eu tenho um bom gosto!"],-1,[[-1],[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Afinal, sempre que eu lembro de Vladmir, lembro de Oblast de Vladmir, que me lembra da cidade de Vladimir, que me lembra que no século 13, foi a antiga capital da Rússia!"],-1,[[-1],[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_paxton,"spd",0],
				[scr_cutscene_variable,variable.normal,o_gleb,"spd",0],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_julian],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_julian],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_looking_to",true],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Que me lembra das antigas Kommunalka, que eram, basicamente, apartamento compartilhados, que me lembra do fato dos antigos russos compartilharem suas casa com outras pessoas..."],-1,[[-1],[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Que me lembra daqui da casa, que me lembra quando você colocou meu nome de Julian!"],-1,[[-1],[s_julian_casual_crayon_idle_3],[s_julian_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Mas por que Julian?"],-1,[[-1],[s_julian_casual_crayon_idle_4],[s_julian_casual_crayon_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Ah! Lembrei!"],-1,[[-1],[s_julian_casual_crayon_idle_3],[s_julian_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["É por que Julian descende de Julio que, significa \"Consagrado de Juptér\"?!"],-1,[[-1],[s_julian_casual_crayon_idle_2],[s_julian_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Se isso incluí o fato de você sempre estar com a cabeça nos ares, então sim... Seu nome significa isso mesmo"],-1,[[-1],[s_vladmir_casual_crayon_idle_2],[s_vladmir_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Pera, por que vocè sabe de tanta coisa sobre a Rússia, Julian?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Exato! Por que você sabe tanta coisa sobre a Rússia?"]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Ah!... Eu.. Eu gosto da Rússia"],-1,[[-1],[s_julian_casual_crayon_idle_5],[s_julian_casual_crayon_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["A Rússia tem neve, que me lembra que no ano passado nós fizemos um boneco de neve!"],-1,[[-1],[s_julian_casual_crayon_idle_2],[s_julian_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["E que a Rússia foi o primeiro país a ir para o espaço!"],-1,[[-1],[s_julian_casual_crayon_idle_3],[s_julian_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Eu quero ir para o espaço!..."],-1,[[-1],[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["A gente pode ir para o espaço quando a gente se formar?"],-1,[[-1],[s_julian_casual_crayon_idle_2],[s_julian_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Não vejo o do por que não"],-1,[[-1],[s_vladmir_casual_crayon_idle_2],[s_vladmir_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Me parece uma ideia fenomenal!!"]],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_paxton],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_gleb],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Oh, então vamos para o espaço?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Sim!! Nós vamos para o espaço!!"]],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_paxton,"direction",270],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_4],
				[scr_cutscene_variable,variable.normal,o_julian,"sprite_index",s_julian_casual_crayon_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Vamos ser as primeiras crianças rebeldes a ir para o espaço!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["E mostrar para todos quem é quem manda!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Vamos derrubar a Hierarquia Rosa e então dominar todo o espaço!"]],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_gleb,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Perfeito, perfeito! Vamos para o espaço!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Mas como que vamos fazer isso?..."]],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_vladmir],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_vladmir],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_looking_to",true],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Um problema de cada vez, Gleb..."],-1,[[-1],[s_vladmir_casual_crayon_idle_4],[s_vladmir_casual_crayon_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Vamos primeiro acabar com a Hierarquia Rosa"],-1,[[-1],[s_vladmir_casual_crayon_idle_3],[s_vladmir_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Vladmir está certo!! Vamos nos preocupar com a Hierarquia Rosa por enquanto!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Certo chefe!!"]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_5],
				[scr_cutscene_variable,variable.normal,o_julian,"sprite_index",s_julian_casual_crayon_idle_4],
				[scr_cutscene_move_character,o_camera,492,1496,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",492],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",1496-16],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,492,1496],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,492,1496,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_move_character,o_todd,522,1496,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_variable,variable.normal,o_calina,"ppl_flowing",false],
				[scr_cutscene_move_character,o_calina,462,1496,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_calina,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,492,1496],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Grande irmão, Todd!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Pequeno irmão, Gleb!!"]],
				[scr_cutscene_variable,variable.normal,o_calina,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Você está do lado deles?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O Gleb é apenas meu pequeno irmão não biológico"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Como que você conhece a palavra \"biológico\""]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E por que eu não iria conhecer?"]],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["BunBun, você está meio racista hoje"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!! Não não! Desculpe, Todd!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá tudo bem, bobão!"]],
				[scr_cutscene_variable,variable.normal,o_calina,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Completamente sem foco nenhum vocês dois..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Desculpe mesmo, Calina"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim, foi mal ai!"]],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_julian,"sprite_index",s_julian_casual_crayon_idle_5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Devolvam as coisas da Calina!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["UH-HUM!!! Eu quero meus materiais de volta!..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Não há a necessidade de tudo isso, assim que o Julian terminar de usar, ele te devolve"],-1,[[-1],[s_vladmir_casual_crayon_idle_5],[s_vladmir_casual_crayon_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Esse foi o combinado"],-1,[[-1],[s_vladmir_casual_crayon_idle_6],[s_vladmir_casual_crayon_talk_6]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Que combinado?"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["O combinado que vocês fizeram, dele usar seus lápis para desenhar e que depois você devolveria"],-1,[[-1],[s_vladmir_casual_crayon_idle_5],[s_vladmir_casual_crayon_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Julian..."],-1,[[-1],[s_vladmir_casual_crayon_idle_1],[s_vladmir_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Ah... É... É que..."],-1,[[-1],[s_julian_casual_crayon_idle_5],[s_julian_casual_crayon_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Que feio Julian! Não se pode roubar dos outros!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Sim sim! O chefe está certo! Roubar é feio!!"]],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_gleb],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_paxton],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Mas chefe... E roubar da Hierarquia Rosa... Isso é feio?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Eles já roubaram coisas de outras pessoas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Olho por olho! Dente por dente!"]],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_vladmir],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_vladmir],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Olho por olho e o mundo fica cego..."],-1,[[-1],[s_vladmir_casual_crayon_idle_3],[s_vladmir_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_1],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Eu não roubei!"],-1,[[-1],[s_julian_casual_crayon_idle_5],[s_julian_casual_crayon_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["O que é o que é.... Pega as coisas das pessoas sem pedir"],-1,[[-1],[s_vladmir_casual_crayon_idle_2],[s_vladmir_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Ah! Essa eu sei!!"],-1,[[-1],[s_julian_casual_crayon_idle_2],[s_julian_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["É um ladrão!"],-1,[[-1],[s_julian_casual_crayon_idle_2],[s_julian_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,2],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Oh..."],-1,[[-1],[s_julian_casual_crayon_idle_5],[s_julian_casual_crayon_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Exatamente"],-1,[[-1],[s_vladmir_casual_crayon_idle_2],[s_vladmir_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Agora devolva o que você pegou"],-1,[[-1],[s_vladmir_casual_crayon_idle_1],[s_vladmir_casual_crayon_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_julian,["Tudo bem..."],-1,[[-1],[s_julian_casual_crayon_idle_5],[s_julian_casual_crayon_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_3],
				[scr_cutscene_variable,variable.normal,o_julian,"sprite_index",s_julian_casual_crayon_idle_4],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_calina],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_paxton],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Espera..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["O Julian pode ter roubado, mas isso não justifica você ter sido grosseira com ele!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Ah?... Mas... Eu não fui grosseira!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Foi sim!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Sim! O chefe tem razão! Você foi grossa com o Julian"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Não, ela não foi"],-1,[[-1],[s_vladmir_casual_crayon_idle_2],[s_vladmir_casual_crayon_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_1],
				[scr_cutscene_variable,variable.normal,o_julian,"sprite_index",s_julian_casual_crayon_idle_5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Exato, a Calina não foi grossa com ninguém!..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Exatamente, a Calina só quer os lápis dela de volta"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Exatamente!"]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Ah... O grande irmão falou que ela não foi, mas o chefe falou que foi..."]],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_gleb],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_gleb,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Gleb não sabe o que fazer!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Gleb fica do lado do grande irmão ou do chefe?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Gleb não sabe o que fazer!!"]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Pequeno irmão!!"]],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_todd],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_to_look_at",o_todd],
				[scr_cutscene_variable,variable.normal,o_calina,"direction",0],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Grande irmão?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não se preocupe, se você ganhar ou se eu ganhar, não vai mudar nossa irmandade!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Você vai ser para sempre meu pequeno irmão!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Sério?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Claro!! Agora junte-se ao seu time!! Vamos batalhar por esses lápis de cores!!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Para já, grande irmão!! Gleb vai dar o melhor que pode!!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["É assim que se fala, pequeno irmão!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Que?..."]],
				[scr_cutscene_variable,variable.normal,o_calina,"direction",270],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Lindas palavras, Todd... Mas ainda assim!!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Iremos lutar, não pelos lápis de cores, mas pelo respeito ao Julian!!"]],
				[scr_cutscene_wait,2],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Vem cá, isso é sério?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Isso... Não é justo..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E Calina nem foi grossa com o Julian!"]],
				[scr_cutscene_variable,variable.normal,o_vladmir,"sprite_index",s_vladmir_casual_crayon_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Blá blá blá!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Se vocês querem o lápis de volta, então lute por eles!!"]],
				[scr_cutscene_variable,variable.normal,o_gleb,"ppl_to_look_at",o_paxton],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_paxton,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["EM UMA CORRIDA!!!"]],
				[scr_cutscene_variable,variable.normal,o_paxton,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Porém, ao meu comando, você terão que parar exatamente onde estão!!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Me parece uma ideia legal"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_gleb,["Oh!! Sim sim!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["BunBun, você vai disputar contra o Vladmir!!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Não vai não"],-1,[[-1],[s_vladmir_casual_crayon_idle_3],[s_vladmir_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Não vou participar disso"],-1,[[-1],[s_vladmir_casual_crayon_idle_3],[s_vladmir_casual_crayon_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["E o Todd vai disputar contra o Gleb!!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_vladmir,["Brincadeira viu..."],-1,[[-1],[s_vladmir_casual_crayon_idle_4],[s_vladmir_casual_crayon_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Vamos lá!! Preparem-se todos!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas eu sou péssimo em esportes..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_can_play",false],
				[scr_cutscene_wait,1],
				[scr_cutscene_minigame,minigame_set.freeze],
				[scr_cutscene_wait,4],
				[scr_cutscene_variable,variable.normal,o_mini_game,"t_cutscene_play",
					[
						[scr_cutscene_room_goto,rm_house_ext_back,true,false],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_can_play",true],
						[scr_cutscene_bars,false,true],
						[scr_cutscene_wait,2],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Hum!!.... Vocês ganharam!!!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Vocês são muito bons!"]],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Uff-Uff... Ok..."]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Isso foi divertido..."]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Mas quero meus materiais de volta"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Tudo bem! Devolve para ela, Julian"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_julian,["Aqui, Calina"]],
						[scr_cutscene_item,o_bunbun,-1,[item.crayon,1],true,false],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_vladmir,["Como que se fala?..."]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_julian,["Desculpe roubar suas coisas, Calina, irei pedir na próxima..."]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Tudo bem, irei pedir com jeitinho na próxima, desculpe ser grossa com vocês"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_vladmir,["Relaxa, você não foi..."]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Deixamos isso de lado... Mas vocês querem desenhar?"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_paxton,["Oh! Podemos?!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Uh-hum! Claro que sim!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_calina,["Vamos lá para dentro, assim podemos desenhar melhor"]],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_vladmir,["Tudo isso foi em vão, senhor...."]],
						[scr_cutscene_wait,1],
						[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
						[scr_cutscene_set_event,[0,6,progress.complete],[0,7,progress.non_complete]],
						[scr_cutscene_room_goto,rm_corridors,false,false],
						[scr_cutscene_variable,variable.normal,o_camera,"x",852],
						[scr_cutscene_variable,variable.normal,o_camera,"y",309],
						[scr_cutscene_variable,variable.normal,o_bunbun,"x",852],
						[scr_cutscene_variable,variable.normal,o_bunbun,"y",309],
						[scr_cutscene_instance_layer,o_bunbun,"Instances_People_2"],
						[scr_cutscene_instance_layer,o_todd,"Instances_People_2"],
						[scr_cutscene_instance_layer,o_calina,"Instances_People_2"],
						[scr_cutscene_refresh_party_member,true],
						[scr_cutscene_wait,.25],
						[scr_cutscene_instance_create,767,302,"Instances_People_2",o_gleb],
						[scr_cutscene_animation_sprite,o_gleb,[s_gleb_casual_crayon_idle_1],[s_gleb_casual_crayon_idle_1],false,true,[1,.2]],
						[scr_cutscene_instance_create,797,296,"Instances_People_2",o_paxton],
						[scr_cutscene_animation_sprite,o_paxton,[s_paxton_casual_crayon_idle_1],[s_paxton_casual_crayon_idle_1],false,true,[1,.2]],
						[scr_cutscene_instance_create,856,345,"Instances_People_2",o_vladmir],
						[scr_cutscene_animation_sprite,o_vladmir,[s_vladmir_casual_crayon_idle_7],[s_vladmir_casual_crayon_idle_7],false,true,[1,.2]],
						[scr_cutscene_instance_create,907,345,"Instances_People_2",o_julian],
						[scr_cutscene_animation_sprite,o_julian,[s_julian_casual_crayon_idle_1],[s_julian_casual_crayon_idle_1],false,true,[1,.2]],
						[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
						[scr_cutscene_variable,variable.normal,o_todd,"x",826],
						[scr_cutscene_variable,variable.normal,o_todd,"y",302],
						[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_crayon_idle_1],[s_todd_casual_crayon_idle_1],false,true,[1,.2]],
						[scr_cutscene_variable,variable.normal,o_calina,"ppl_flowing",false],
						[scr_cutscene_variable,variable.normal,o_calina,"x",880],
						[scr_cutscene_variable,variable.normal,o_calina,"y",337],
						[scr_cutscene_animation_sprite,o_calina,[s_calina_casual_crayon_idle_7],[s_calina_casual_crayon_idle_7],false,true,[1,.2]],
						[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_casual_crayon_idle_0],[s_bunbun_casual_crayon_idle_0],false,true,[1,.2]],
						[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
						[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
						[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
						[scr_cutscene_wait,2],
						[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
						[scr_cutscene_move_character,o_camera,888,262,false,.5,false,false],
						[scr_cutscene_instance_create,888,262,"Instances_People_2",o_linus],
						[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_linus],
						[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
						[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",false],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.nearst,o_door_1,"open",true,888,270],
						[scr_cutscene_wait,1],
						[scr_cutscene_move_character,o_linus,888,294,false,1,true,true],
						[scr_cutscene_variable,variable.normal,o_linus,"direction",225],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.nearst,o_door_1,"open",false,888,270],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_casual_crayon_idle_1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Oh... Estou atrapalhando?..."]],
						[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah! Não não! Apenas estamos desenhando juntos!!"],-1,[[-1],[s_bunbun_casual_crayon_idle_2],[s_bunbun_casual_crayon_talk_2]],false,false,[0,.2,.25]],
						[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Quer desenhar também?"],-1,[[-1],[s_bunbun_casual_crayon_idle_2],[s_bunbun_casual_crayon_talk_2]],false,false,[0,.2,.25]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah, não obrigado... Apenas queria falar contigo..."]],
						[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh! Sim, você tinha mencionado mesmo!!"],-1,[[-1],[s_bunbun_casual_crayon_idle_2],[s_bunbun_casual_crayon_talk_2]],false,false,[0,.2,.25]],
						[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Um momento que já irei contigo!!"],-1,[[-1],[s_bunbun_casual_crayon_idle_2],[s_bunbun_casual_crayon_talk_2]],false,false,[0,.2,.25]],
						[scr_cutscene_wait,1],
						[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
						[scr_cutscene_remove_party_member,o_calina],
						[scr_cutscene_remove_party_member,o_todd],
						[scr_cutscene_instance_destroy,o_calina],
						[scr_cutscene_instance_destroy,o_gleb],
						[scr_cutscene_instance_destroy,o_paxton],
						[scr_cutscene_instance_destroy,o_julian],
						[scr_cutscene_instance_destroy,o_vladmir],
						[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.npc],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
						[scr_cutscene_variable,variable.normal,o_todd,"y",302],
						[scr_cutscene_variable,variable.normal,o_bunbun,"y",302],
						[scr_cutscene_variable,variable.normal,o_linus,"y",302],
						[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
						[scr_cutscene_variable,variable.normal,o_linus,"direction",180],
						[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
						[scr_cutscene_variable,variable.normal,o_camera,"x",852],
						[scr_cutscene_variable,variable.normal,o_camera,"y",309],
						[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_bunbun],
						[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
						[scr_cutscene_new_party_member,o_linus],
						[scr_cutscene_save_game],
						[scr_cutscene_wait,1],
						[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
						[scr_cutscene_wait,1],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh... Então o Linus quer falar contigo?"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Sim sim, não é nada grave"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, menos mal! Querem que eu espere?"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não tá tudo bem! pode ir jantar, Todd!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Hum... Você tem certeza?"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Pode sim!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se te faz sentir melhor, pode ficar com metade da minha janta!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Espera... Posso mesmo?!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim, fique a vontade!!"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Obrigado mesmo, BunBun!!"]],
						[scr_cutscene_wait,1],
						[scr_cutscene_set_path,o_todd,p_todd_dinner_1,1.5,path_action_stop,true,path_act.delet],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_todd],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
						[scr_cutscene_variable,variable.normal,o_linus,"ppl_to_look_at",o_todd],
						[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",true],
						[scr_cutscene_wait,3],
						[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
						[scr_cutscene_variable,variable.normal,o_linus,"ppl_looking_to",false],
						[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
						[scr_cutscene_variable,variable.normal,o_linus,"direction",180],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Você sempre deixa ele comer sua comida?"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Na maioria das vezes eu não aguento comer tudo..."]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Então eu deixo ele comer"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah... Tudo bem, eu acho... Mas isso não pode te fazer mal? Por ficar sem comer"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Não não! Eu como o suficiente! Apenas colocam comida demais para mim"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Ah... Bom... Tudo bem então"]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Bom, vamos lá para o banheiro, lá é um lugar mais seguro para o que quero te falar..."]],
						[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh!... Ok..."]],
						[scr_cutscene_wait,1],
						[scr_cutscene_variable,variable.normal,o_linus,"ppl_flowing",true],
						[scr_cutscene_wait,1],
						[scr_cutscene_bars,true,false],
					]
				]
			];
			#endregion
		}
		break;
}