if(global.event[0][4]==progress.non_complete){
	quest_array=[
		[0,quest_type.have_item,item.noah_gift],
	]
	complete_cutscene=[];
	non_complete_cutscene[0]=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_move_character,o_bunbun,288,632,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
		[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		[scr_cutscene_move_character,o_todd,256,619,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
		[scr_cutscene_move_character,o_hellen,321,619,false,1,true,true],
		[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Olá, BunBun"],-1,[[-1],[s_fritz_casual_loveletter_idle_1],[s_fritz_casual_loveletter_talk_1]],false,false,[0,.2,.25]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Está fazendo sua checagem de novo?"],-1,[[-1],[s_fritz_casual_loveletter_idle_2],[s_fritz_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá, Fritz"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Acho que sim! Gosto de me preocupar com os outros"]],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Isso é bonito"],-1,[[-1],[s_fritz_casual_loveletter_idle_2],[s_fritz_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Ah! Olá Hellen, desculpe, acabei não notando sua presença, desculpe!..."],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["N-Não se preocupe, Fritz!"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Mas... Como você está?..."]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Bom... Estou bem!... E Você?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["HeeHee! Estou bem também!..."]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Me alegro de ver que está bem, de verdade!"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Digo o mesmo de ti!~"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["HeeHee... Bom, nós temos que ir, ok?"]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Claro, sem problemas, Hellen, se cuide"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Pois a ti també, Fritz"]],
		[scr_cutscene_wait,1],
		[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_idle_1],
		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
		[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
		[scr_cutscene_move_character,o_bunbun,0,-8,true,1,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	]
}