#region dia 0
non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_g_bedroom_2,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",652],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"x",652],
	[scr_cutscene_variable,variable.normal,o_camera,"y",441],
	[scr_cutscene_wait,1],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,652,441,false,1,true,true],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
];
#endregion
switch global.day{
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region
			non_avaliable_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto da Hellen, Eleanor, Jill e Nina... Busca por alguma coisa?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nu-uh! Apenas explorando... Mas..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que foi?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A Nina é tão legal, você não acha?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Você acha? Eu gosto mais da Jill e da Elanor!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim, elas são legais também!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["É que você e a Nina são parecidos em alguns aspéctos"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tipo, ela é toda boba e não consegue falar não"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Sobre isso você tem razão..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Hum... Ou talvez seja por outra coisa, vocês não são bobos..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["De fato, não conseguem falar não, mas não são bobos"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!... Obrigado, eu acho"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][2]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.talk_to,o_ksenia],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_g_bedroom_2,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",652],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",652],
				[scr_cutscene_variable,variable.normal,o_camera,"y",441],
				[scr_cutscene_instance_create,661,384,"Instances_People_2",o_ksenia],
				[scr_cutscene_animation_sprite,o_ksenia,[s_ksenia_casual_hide_n_seek__idle_2],[s_ksenia_casual_hide_n_seek__idle_2],false,true,[1,1]],
				[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_talked",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,652,441,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_move_character,o_bunbun,634,411,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",false],
				[scr_cutscene_move_character,o_laszlo,683,411,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
				[scr_cutscene_wait,1],
				[scr_cutscene_animation_sprite,o_ksenia,[s_ksenia_casual_hide_n_seek__looking],[s_ksenia_casual_hide_n_seek__idle_1],false,true,[.35,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nós... Te achamos..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Você ficou desenhando e não se escondeu?"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_ksenia,"direction",180],
				[scr_cutscene_animation_sprite,o_ksenia,[s_ksenia_casual_hide_n_seek__getting_up],[s_ksenia_casual_idle_1_left],false,true,[.35,.2]],
				[scr_cutscene_variable,variable.normal,o_ksenia,"ppl_act_state",ppl_act.npc],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_ksenia,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_ksenia,"direction",270],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_ksenia],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_to_look_at",o_ksenia],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_looking_to",true],
				[scr_cutscene_move_character,o_ksenia,652,441,false,1,true,true],
				//[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				//[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_looking_to",false],
				//[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//[scr_cutscene_variable,variable.normal,o_laszlo,"direction",135],
				[scr_cutscene_move_character,o_ksenia,652,541,false,1,true,true],
				[scr_cutscene_instance_destroy,o_ksenia],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_laszlo,"direction",180],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nem uma palavra?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Ela só fala com a Julia e com Danica, que é sua dupla"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Tirando elas, ela nunca falou com mais ninguém..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Sério, isso?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_laszlo,["Sim, além de que ela fala naturalmente quando estão sozinhas, mas na frente dos outros, ela sussurra nos ouvidos delas..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_laszlo,"ppl_flowing",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_g_bedroom_2,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",652],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",652],
				[scr_cutscene_variable,variable.normal,o_camera,"y",441],
				[scr_cutscene_wait,1],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,652,441,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			#endregion
		}else if(global.event[0][3]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.mother_list],
				[-1,quest_type.have_item,item.uncle_spices],
			]
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não acredito que a Mamãe vai estar no quarto de uma das crianças..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Certeza?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim e por que motivo ela estaria?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Por que ela é nossa mãe e sempre nos ajuda com tudo! Ela quem nos ensinava a arrumar a cama, bobo"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok, você tem um ponto, mas ainda assim, ela não vai estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tá bom..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O quarto do Tio Big B não é aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim, eu sei, apenas pensei que ele pudesse estar aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E por que raios ele estaria em um quarto de uma das crianças?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele sempre se certifica do bem estar de todos aqui!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Chorei 5 unidades de lágrimas, vamos logo para o quarto dele"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bobo..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Depois você vê o que tem nas gavetas do povo, vamos entregar os temperos para a Mamãe!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["QUE?! Eu não vejo o que tem nas gavetas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vê sim! Você é todo curioso!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não!... Na realidade sim, sou curioso... MAS EU NÃO VEJO O QUE TEM NAS GAVETAS!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][4]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.love_letter],
				[-1,quest_type.talk_to,o_noah],
				[-1,quest_type.talk_to,o_hellen],
				[-1,quest_type.have_item,item.noah_gift],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_g_bedroom_2,true,false],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",662],
				[scr_cutscene_variable,variable.normal,o_camera,"y",360],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",639],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",401],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_todd,"x",682],
				[scr_cutscene_variable,variable.normal,o_todd,"y",401],
				[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_hellen,"x",662],
				[scr_cutscene_variable,variable.normal,o_hellen,"y",360],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				[scr_cutscene_animation_sprite,o_hellen,[s_hellen_casual_loveletter_idle_1],[s_hellen_casual_loveletter_idle_1],false,true,[1,.2]],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Pera... Então é isso?"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_hellen,["Sim... basicamente..."],dag_002,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh! Isso é bonito!!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Sim... Mas eu não tenho ideia de como falar isso para ele..."],-1,[[-1],[s_hellen_casual_loveletter_idle_1],[s_hellen_casual_loveletter_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Ainda mais ele sendo..."],-1,[[-1],[s_hellen_casual_loveletter_idle_1],[s_hellen_casual_loveletter_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Tão ingeligente..."],-1,[[-1],[s_hellen_casual_loveletter_idle_2],[s_hellen_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Tão bonito..."],-1,[[-1],[s_hellen_casual_loveletter_idle_2],[s_hellen_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Tão sério..."],-1,[[-1],[s_hellen_casual_loveletter_idle_2],[s_hellen_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Tão elegante..."],-1,[[-1],[s_hellen_casual_loveletter_idle_2],[s_hellen_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Tão... Ah~"],-1,[[-1],[s_hellen_casual_loveletter_idle_2],[s_hellen_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee! O amor faz essas coisas!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["De fato faz..."],-1,[[-1],[s_hellen_casual_loveletter_idle_2],[s_hellen_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Mas como que eu faço para ele isso?..."],-1,[[-1],[s_hellen_casual_loveletter_idle_1],[s_hellen_casual_loveletter_talk_1]],false,false,[0,.2,.25]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_idle_3],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Que tal uma carta?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Uma carta?"],-1,[[-1],[s_hellen_casual_loveletter_idle_3],[s_hellen_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim, uma carta de amor... Coloque nesse papel tudo o que você sente por ele"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Há certas palavras que são melhor escritas que ditas"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sem falar que algumas palavras simplesmente não saem da boca, e sim do coração"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Oh..."],-1,[[-1],[s_hellen_casual_loveletter_idle_3],[s_hellen_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Todd, isso foi lindo, honestamente falando!..."],-1,[[-1],[s_hellen_casual_loveletter_idle_4],[s_hellen_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_idle_3],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah!... Quando eu quero, eu dou uma bola dentro! Valeu ai!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["HeeHee"],-1,[[-1],[s_hellen_casual_loveletter_idle_5],[s_hellen_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Mas você já escreveu alguma carta?..."],-1,[[-1],[s_hellen_casual_loveletter_idle_3],[s_hellen_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah... Não... Mas eu tabmém quero escrever uma carta para alguém"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Oh! Quer compartilhar isso conosco?"],-1,[[-1],[s_hellen_casual_loveletter_idle_4],[s_hellen_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bom... Se você prometer que não vão falar para ninguém"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Eu prometo!"],-1,[[-1],[s_hellen_casual_loveletter_idle_5],[s_hellen_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu também prom-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eh, bom..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["HeeHee... Bem..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu gosto.... Eu gosto da Wendy"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Wendy? A dupla da Grettel?"],-1,[[-1],[s_hellen_casual_loveletter_idle_4],[s_hellen_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh-hum!!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Você tem certeza sobre ela?... Ela pode ser meio... Cruel..."],-1,[[-1],[s_hellen_casual_loveletter_idle_4],[s_hellen_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim... Mas tudo bem! Vai valer a pena!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Quanto maior o desafio, melhor serão os resultados!!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Se você diz! HeeHee"],-1,[[-1],[s_hellen_casual_loveletter_idle_5],[s_hellen_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Mas e você, BunBun? Gosta de alguém?"],-1,[[-1],[s_hellen_casual_loveletter_idle_3],[s_hellen_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! É verdade?! Você gosta de alguém também?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Bem..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não... Eu não gosto de ninguém..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh? Certeza?..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu jurava que você gostava de alguém..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não... Eu não gosto..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas tudo bem! Ainda assim vou escrever uma carta para praticar com vocês!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh! Sério?! Isso vai ser supimpa!!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos te ajudar, Hellen!!"]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Ah! Perfeito!!"],-1,[[-1],[s_hellen_casual_loveletter_idle_5],[s_hellen_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_hellen,"sprite_index",s_hellen_casual_loveletter_idle_3],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... O Fritz gosta de palavras bonitas e inteligente"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele ama livros e poesias, sem falar que ele ama rosas!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Perfeito! Acho que podemos escrever algo com isso!"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_hellen,["Perfeito!! Vamos para a ação então!"],-1,[[-1],[s_hellen_casual_loveletter_idle_5],[s_hellen_casual_loveletter_talk_5]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_can_play",false],
				[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,0,1],
				[scr_cutscene_wait,1],
				[scr_cutscene_audio_stop,audio_type.bgm,bgm_008],
				[scr_cutscene_minigame,minigame_set.love_letter],//[scr_cutscene_instance_create,639,401,"Instances_Config",o_mini_game],
				[scr_cutscene_wait,4],
				[scr_cutscene_variable,variable.normal,o_mini_game,"t_cutscene_play",[
					[scr_cutscene_room_goto,rm_g_bedroom_2,true,false],
					[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
					[scr_cutscene_variable,variable.normal,o_hellen,"ppl_pos",48],
					[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
					[scr_cutscene_variable,variable.normal,o_hellen,"x",661],
					[scr_cutscene_variable,variable.normal,o_hellen,"y",385],
					[scr_cutscene_variable,variable.normal,o_hellen,"ppl_act_state",ppl_act.flow],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_can_play",true],
					[scr_cutscene_bars,false,true],
					[scr_cutscene_wait,1],
					[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,1,1],
					[scr_cutscene_item,o_bunbun,-1,[item.love_letter,1],true,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Terminamos!!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Obrigado, garotos, de verdade!!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sem problemas!! Vamos entregar isso para ele?"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... Bom... Agora não..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ué? E por que? Nós todos fizemos cartas, se você entregar a sua, eu entrego a minha!"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Não não!! Não é isso!"]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu gostaria de falar com o 45..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Com ele? Por que?"]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Apenas acredito que apenas uma carta não seja o suficiente, acredito que ele possa ter algo que sirva como um presente..."]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bom, tudo bem, vamos nessa!"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
				]]
			];
			non_complete_cutscene[1]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O 45 estaria aqui?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu tenho certeza que vi ele no andar de baixo.."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh? Pensei que ele estava aqui, vamos lá então"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos nessa!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[2]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["A Wendy não está aqui"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh? Como você sabe?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ela gosta de ficar lendo no quarto dela, depois de brincar lá fora..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, bom... Tudo bem, vamos lá então!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			non_complete_cutscene[3]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ainda temos que pegar o presente com o 45"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oh! É verdade!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Se não sou eu"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, Não seja assim!..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			]
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O Fritz está lá em baixo..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Fica calma, já, respira, ok?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Falar é fácil!... Meu Deus, que medo"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu sei!! Logo logo será eu!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else if(global.event[0][5]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.someone_party,o_petter],
				[-1,quest_type.talk_to,o_door_1],
				[-1,quest_type.talk_to,o_bunbun],
				[-1,quest_type.talk_to,o_door_2],
				[-1,quest_type.someone_party,o_linus],
				[-1,quest_type.have_item,item.linus_diary],
				[-1,quest_type.talk_to,o_linus],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_g_bedroom_2,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",652],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",541],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",652],
				[scr_cutscene_variable,variable.normal,o_camera,"y",441],
				[scr_cutscene_wait,1],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,652,441,false,1,true,true],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			non_complete_cutscene[1]=non_complete_cutscene[0];
			non_complete_cutscene[2]=non_complete_cutscene[0];
			non_complete_cutscene[3]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh... BunBun... Você acha que a Mamãe está aqui mesmo?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["É que eu me lembro de ter visto ela na cafeteria"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Nesse caso, vamos até lá!!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[4]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Uh... BunBun... Esse não é o quarto do Linus"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não? Jurava que sim..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[5]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["BunBun, depois vemos isso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Vamos apenas recuperar o que é meu, por favor..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro, desculpe"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			non_complete_cutscene[6]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["A Mamãe não está aqui, BunBun, não se lembra?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro claro, desculpe"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_petter,["Ah! N-Não se preocupe!..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_linus,["Apenas vamos até a Mamãe para terminar com isso..."]],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,0,-8,true,.5,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}
		break;
}