#region dia 0
non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_corridors,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",591],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",487],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"x",591],
	[scr_cutscene_variable,variable.normal,o_camera,"y",505],
	[scr_cutscene_wait,1],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,591,505],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,591,505,false,1,true,true],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,591,505],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
];
switch global.day{
	case 0:
		if(global.event[0][3]==progress.non_complete){
			quest_array=[
				[0,quest_type.talk_to,o_mommy_allegra],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_corridors,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",591],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",487],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",591],
				[scr_cutscene_variable,variable.normal,o_camera,"y",505],
				[scr_cutscene_wait,1],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,591,505],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,591,505,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,591,505],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_set_event,[0,3,progress.complete],[0,4,progress.non_complete]],
				[scr_cutscene_room_goto,rm_corridors,false,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",591],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",487],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",591],
				[scr_cutscene_variable,variable.normal,o_camera,"y",505],
				[scr_cutscene_set_children],
				//[scr_cutscene_instance_create,591,567,"Instances_People_1",o_hellen],
				//[scr_cutscene_instance_create,272,610,"Instances_People_1",o_cutscene_trigger_3],
				//[scr_cutscene_instance_create,288,619,"Instances_People_1",o_fritz],
				//[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_loveletter_idle_1],[s_fritz_casual_loveletter_idle_1],false,true,[.2,.2]],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",4.25,272,610],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",.625,272,610],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_complete_cutscene",
				//	[
				//		[
				//			[scr_cutscene_bars,true,true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_move_character,o_bunbun,288,632,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_move_character,o_todd,256,619,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//			[scr_cutscene_move_character,o_hellen,321,619,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Olá, BunBun"],-1,[[-1],[s_fritz_casual_loveletter_idle_1],[s_fritz_casual_loveletter_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Está fazendo sua checagem de novo?"],-1,[[-1],[s_fritz_casual_loveletter_idle_2],[s_fritz_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá, Fritz"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Acho que sim! Gosto de me preocupar com os outros"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Isso é bonito"],-1,[[-1],[s_fritz_casual_loveletter_idle_2],[s_fritz_casual_loveletter_talk_2]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Ah! Olá Hellen, desculpe, acabei não notando sua presença, desculpe!..."],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["N-Não se preocupe, Fritz!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Mas... Como você está?..."]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Bom... Estou bem!... E Você?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["HeeHee! Estou bem também!..."]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Me alegro de ver que está bem, de verdade!"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Digo o mesmo de ti!~"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["HeeHee... Bom, nós temos que ir, ok?"]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Claro, sem problemas, Hellen, se cuide"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Pois a ti també, Fritz"]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_fritz,"sprite_index",s_fritz_casual_loveletter_idle_1],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
				//			[scr_cutscene_move_character,o_bunbun,0,-8,true,1,true,true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_bars,true,false],
				//		]
				//	],
				//272,610],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"complete_cutscene",[],272,610],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"quest_array",
				//	[
				//		[0,quest_type.have_item,item.noah_gift],
				//	],
				//272,610],
				//[scr_cutscene_instance_create,1194,386,"Instances_People_1",o_noah],
				//[scr_cutscene_animation_sprite,o_noah,[s_noah_casual_chill_idle_0],[s_noah_casual_chill_idle_0],false,true,[.2,.2]],
				//[scr_cutscene_instance_create,1170,396,"Instances_People_1",o_cutscene_trigger_3],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_xscale",6,1170,396],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"image_yscale",.5,1170,396],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"non_complete_cutscene",
				//	[
				//		[
				//			[scr_cutscene_bars,true,true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_move_character,o_bunbun,1194,426,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				//			[scr_cutscene_move_character,o_bunbun,1194,421,false,1,true,true],
				//			[scr_cutscene_move_character,o_todd,1165,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_move_character,o_hellen,1223,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá, 45!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Oi, 45!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá tudo bem?"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Precisam de alguma coisa?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Não não! Apenas viemos ver como você está!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Uh-hum!! Animado para seu aniversário?"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Não sei, na realidade... Acho que só quero saber meu nome mesmo..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Sim sim!! Já pensou em um nome para o 46?"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Sim, já faz um tempo"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sério?! E qual?!"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Não posso falar, você sabe quais são as regras"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Qual é! Fala ai, pra nós!"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["E o que eu ganho com isso?"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Nem assim você deixa de pensar em negócios"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Troca de informação por monetário... Tempo é dinheiro, Todd"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Tão jovem e tão capitalista..."]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Alguém tem que fazer o capital de giro..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ele só tem dois anos, isso não assusta vocês não?"]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim, mas depois nós nos acostumamos..."]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",315],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Eu já comprei algumas coisas  com ele..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["E o que ele vende?"]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Depende, de que você precisa?..."],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",315],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["O que você comprou?"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Balas, flores... O Joe tinha comprado o capacete com o 45"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["...."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Tendi..."]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_0],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_bars,true,false],
				//		],
				//		[
				//			[scr_cutscene_variable,variable.normal,o_noah,"ppl_talked",true],
				//			[scr_cutscene_bars,true,true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_move_character,o_bunbun,1194,426,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				//			[scr_cutscene_move_character,o_bunbun,1194,421,false,1,true,true],
				//			[scr_cutscene_move_character,o_todd,1165,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_move_character,o_hellen,1223,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Olá, 45!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Oi, 45!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá tudo bem?"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Precisam de alguma coisa?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... Bom..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Na realidade sim, precisamos..."]],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Do que precisam?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Um presente..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Precisamos de um presente para alguém..."]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["E quem seria esse alguém?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["B-Bom..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Seria o Frtiz..."]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Fritz, você diz, não?"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["E qual o motivo do presente? É por causa do aniversário?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah!! Sim sim! É por causa do aniversário!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim! Exato, queremos fazer algo especial para ele!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Uh-Hum! Confia!!"]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Tudo bem, tudo bem..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Bom, quem realizará o pagamento?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",315],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Deixa na minha conta"]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Na sua conta, BunBun?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Tudo bem, tudo bem..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Você tem um crédito sobrando comigo... Considere isso pago"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Mas agora, em termos de crádito, você está zerado, tudo bem?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sem problemas!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Como que se consegue crédito com você? E como se realiza o pagamento?"]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Isso depende..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Algumas coisas são mais caras que outras, mas no geral, eu aceito tudo"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Balas, flores, cartas, comida,  folhas... Isso tudo pode variar"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Como o BunBun tem o costume de me pedir coisas baratas, ele me paga em flores ou comida"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",315],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Pera, então é por isso que quando você não aguenta comer tudo, você dá sua comida para ele?"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bom... Sim..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Poxa... Eu eu pensando que você gostava mais dele do que de mim..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh?! Não! Vocè sempre vai ser meu favorito!!"]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Ahem!... Voltando ao assunto..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["O serviço já está pago... O que vocês desejam presentear para ele?"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bem, nesse caso... Creio que algo fofo"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Flores?"]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",315],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se fosse para ser flores, teriamos ido lá fora pegar..."]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ele está certo, Todd.."]],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não está mais aqui quem falou..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah!! Desculpe desculpe, Todd!!"]],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",315],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá tudo bem, baixote, já superei"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Já sei!!"]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Um livro! Um livro de romance!"]],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Um livro de romance... Tudo bem... Voltem mais tarde, aqui mesmo, que eu entrego ele para vocês"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Muito obrigada!! De verdade!!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Obrigado, 45!!"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Valeu mesmo!!"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Não precisam agradecer... Negócios são negócios"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_0],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bem, precisa de algo a mais?"]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["..."]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["..."]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.custom],
				//			[scr_cutscene_variable,variable.normal,o_todd,"image_speed",0],
				//			[scr_cutscene_variable,variable.normal,o_todd,"image_index",0],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Podemos falar com a Wendy?"]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_wait,.5],
				//			[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_blush_1],[s_todd_casual_blush_3],false,true,[.3,1]],
				//			[scr_cutscene_wait,.5],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["..."]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu queria estar em bom estado para ele... E como é é bonita...."]],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["T-Tá~..."]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Se você ficar nervoso, eu seguro a sua mão"]],
				//			[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_casual_blush_2],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["..."]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Desculpe"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["T-Tá~..."]],
				//			[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_blush_4],[s_todd_casual_idle_1_right],false,true,[.3,1]],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Só vamos lá falar com ela..."]],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_bars,true,false],
				//		],
				//		[
				//			[scr_cutscene_bars,true,true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_move_character,o_bunbun,1194,426,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				//			[scr_cutscene_move_character,o_bunbun,1194,421,false,1,true,true],
				//			[scr_cutscene_move_character,o_todd,1165,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_move_character,o_hellen,1223,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Ora... Precisam de algo mais?"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah, não não, só queriamos saber quando mais ou menos vai estar pronto"]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Logo logo... Ainda não pensei em nada... As variedades são grandes, mas eu ainda tenho que avaliar e buscar por eles..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Oh, tudo bem, temos que resolver umas coisas também, voltaremos mais tarde, tudo bem?"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Claro, tudo bem"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_0],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_bars,true,false]
				//		],
				//		[
				//			[scr_cutscene_bars,true,true],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_move_character,o_bunbun,1194,426,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				//			[scr_cutscene_move_character,o_bunbun,1194,421,false,1,true,true],
				//			[scr_cutscene_move_character,o_todd,1165,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//			[scr_cutscene_move_character,o_hellen,1223,418,false,1,true,true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Oi, 45, conseguiu?"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Oh, vocês de novo"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Sim sim, aqui está"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_item,o_bunbun,-1,[item.noah_gift,1],true,false],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah! Muito obrigada!!"]],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Não se preocupe, apenas estou fazendo meu trabalho"],-1,[[-1],[s_noah_casual_chill_idle_1],[s_noah_casual_chill_talk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Seu trabalho vai me ajudar a deixar uma pessoa feliz, 45"]],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["E você escolheu um bom exemplar, estou muito feliz e orgulhosa!"]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Ah... Que gentil, que gentil..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_1],
				//			[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom, nós nos vamos, muito obrigada de novo!!"]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Eu quem agradeço..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_0],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				//			[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
				//			[scr_cutscene_instance_create,420,557,"Instances_People_1",o_cutscene_trigger_2],
				//			[scr_cutscene_variable,variable.normal,o_cutscene_trigger_2,"image_xscale",1.125],
				//			[scr_cutscene_variable,variable.normal,o_cutscene_trigger_2,"image_yscale",5.625],
				//			[scr_cutscene_variable,variable.normal,o_cutscene_trigger_2,"non_avaliable_cutscene",
				//				[
				//					[scr_cutscene_bars,true,true],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_hellen],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_hellen],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... Bom... Garotos..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Acho... Acho que eu consigo daqui para frente..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh, você tem certeza, Hellen?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Sim... Acho que sim"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Quer que a gente fique em algum lugar para te dar suporte ou algo do tipo?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom... Se quiserem ficar lá em cima, tudo bem"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sem problemas! Vamos ficar caladinhos, te dando suporte"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Sim sim! Estaremos te desejando o melhor"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Obrigado, garotos!"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_instance_create,357,470,"Instances_People_2",o_wendy],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				//					[scr_cutscene_move_character,o_bunbun,503,574,false,1,true,true],
				//					[scr_cutscene_move_character,o_bunbun,503,532,false,1,true,true],
				//					[scr_cutscene_move_character,o_bunbun,431,532,false,1,true,true],
				//					[scr_cutscene_move_character,o_bunbun,384,502,false,1,true,true],
				//					[scr_cutscene_move_character,o_bunbun,384,502,false,1,true,true],
				//					[scr_cutscene_move_character,o_bunbun,304,413,false,1,true,true],
				//					[scr_cutscene_move_character,o_bunbun,304,466,false,1,true,true],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//					[scr_cutscene_move_character,o_todd,-24,0,true,1,true,true],
				//					[scr_cutscene_move_character,o_todd,0,24,true,1,true,true],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Wendy?..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Sim?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Nada, apenas não esperava por você aqui"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Bom... Eu ajudei ela também, não?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["De fato sim!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Bom, ficarei aqui"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Claro que você pode ficar"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Não foi uma pergunta, eu ficarei aqui"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh, desculpe-"]],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Desculpe também"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd..."]],
				//					[scr_cutscene_wait,.5],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Desculpe..."]],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				//					[scr_cutscene_wait,.5],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Bobo"]],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				//					[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_player",false],
				//					[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_layer",1],
				//					[scr_cutscene_move_character,o_camera,288,619,false,1,false,false],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Uff... Vamos Hellen..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Você consegue!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Você consegue! Você consegue!"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_move_character,o_hellen,423,582,false,1,true,true],
				//					[scr_cutscene_move_character,o_hellen,321,619,false,1,true,true],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah... Fritz!..."]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Ah! Olá, Hellen!"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Deseja algo?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu... Eu queria saber o que você está lendo, na realidade"]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Oh! Isso? Bom..."],-1,[[-1],[s_fritz_casual_loveletter_idle_4],[s_fritz_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["É um romance, na realidade"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Um romance? Nunca imaginei você lendo romance"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Sei que você conhece o movimento romancista"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Mas consumir... Isso é inovador, na realidade"]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Bom, sim, na realidade, é um livro tragediano, que conta a história de um romance"],-1,[[-1],[s_fritz_casual_loveletter_idle_4],[s_fritz_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Mas não se deixe enganar pelas tragédias, o amor empregado nesse livro é realmente bom e lindo"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Você gosta de livros romancistas, não?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom, sim, eu gosto, apesar de preferir os mais didáticos"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Como está acontecendo uma guerra aos exteriores dessa casa, eu prefiro consumir coisas mais positivas... Entende?"]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Eu entendo... Apesar de que eu prefira ler os poemas daqueles que estavam na guerra, ler seus pensamentos e memórias em estrofes é uma experiência"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu... Nunca li esses poemas... Você poderia... Me mostrar alguns?"]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Para ti? Com todo o prazer, Hellen!..."],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Mas..."],-1,[[-1],[s_fritz_casual_loveletter_idle_4],[s_fritz_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Posso te fazer uma pergunta?"],-1,[[-1],[s_fritz_casual_loveletter_idle_3],[s_fritz_casual_loveletter_talk_3]],false,false,[0,.2,.25]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Claro, o que quiser"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_loveletter_look_1],[s_fritz_casual_loveletter_idle_4],false,true,[.3,.2]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_fritz,["Você veio apenas para falar do meu livro, certo?..."],-1,[[-1],[s_fritz_casual_loveletter_idle_4],[s_fritz_casual_loveletter_talk_4]],false,false,[0,.2,.25]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Na realidade..."]],
				//					[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_loveletter_look_2],[s_fritz_casual_loveletter_idle_look_2],false,true,[.3,.2]],
				//					[scr_cutscene_animation_sprite,o_fritz,[s_fritz_casual_loveletter_getting_up],[s_fritz_casual_idle_1_down],false,true,[.3,.2]],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"ppl_act_state",ppl_act.npc],
				//					[scr_cutscene_wait,.5],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",315],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",0],
				//					[scr_cutscene_wait,.5],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Eu vi que você estava andando para cima e para baixo com o BunBun e com o Todd, tem algo errado?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Tem algo te incomodando?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah! Não não..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eles estavam apenas me ajudando"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Ajudando? Hellen... Está tudo bem de verdade?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Fritz... Eles só estavam... Me ajudando..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Com isso!!"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_instance_create,328,465,"Instances_People_2",o_nickolai],
				//					[scr_cutscene_instance_create,256,470,"Instances_People_2",o_rubbert],
				//					[scr_cutscene_instance_create,333,473,"Instances_People_2",o_clara],
				//					[scr_cutscene_instance_create,295,457,"Instances_People_2",o_nina],
				//					[scr_cutscene_instance_create,260,456,"Instances_People_2",o_amanda],
				//					[scr_cutscene_instance_create,383,457,"Instances_People_2",o_eleanor],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Um livro?..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["É para você..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Pedi ajuda para eles para me ajudar a buscar um livro que você ainda não leu..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Um livro?... Que ainda não li..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Isso é tão doce, Hellen!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Você é tão atenta e..."]],
									
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Uma carta? Isso estava aqui antes?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu coloquei"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["A carta é sua?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Sim..."]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Ela... É linda, Hellen"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Uh!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Você... Você realmente gostou?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["É tudo isso o que você sente?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Sim... Cada palavra..."]],
									
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Aqui, para você"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Espera... Você... Você também?..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Sim... Cada palavra..."]],
									
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["F-Frtiz..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Hellen..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Frtiz..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Hellen..."]],
				//					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_bunbun,["Shhh!"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
				//					[scr_cutscene_talk_custom,cutscene_talk_mode.normal,o_todd,["Shhh você!"],-1,(global.cw/2),global.ch/2,150,make_color_rgb(36,34,52),true,true,false],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["..."]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_player",true],
				//					[scr_cutscene_variable,variable.normal,o_graphic,"graphic_flow_layer",2],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",45],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",90],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Ignora a gente"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Exato, não estamos aqui"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_eleanor,["Ajam normalmente"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["A culpa é do Nickolai..."]],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",225],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["O QUE?! POR QUE?!"]],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_nina,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_eleanor,"direction",225],
				//					[scr_cutscene_variable,variable.normal,o_wendy,"direction",180],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Apenas fiquem quietos de uma vez, por favor!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Wendy está certa, deixem eles terminarem!"]],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_nina,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_eleanor,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_wendy,"direction",270],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Ignora a gente"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["..."]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu... Eu não sabia disso..."]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",45],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",0],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Fritz, eu não sabia que eles estavam vendo, me desculpe!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Hellen!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Deixem que eles vejam"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Ui, meu Deus-"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["A existência deles, no NOSSO mundo, não importa"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Ai... Me machucou..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Hellen, eu queria..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Ai, é agora!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Eu queria dizer..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ele vai falar, ele vai falar!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Dizer que..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Minha nossa, isso é tão romântico!"]],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",90],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["VOCÊS PODEM, POR FAVOR, CALAREM A BOCA?!"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Aff, que mal educado"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["É a internet de hoje em dia"]],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que é internet"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sei lá, acabei de criar essa palavra"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["É uma boa palavra"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ah! Valeu BunBun!"]],
				//					[scr_cutscene_variable,variable.normal,o_wendy,"direction",180],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_nina,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_eleanor,"direction",225],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Seguinte, ou vocês ficam quietos, eu vou fazer questão de fazer cada um se arrepender de ter vindo para cá..."]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_nina,"direction",270],
				//					[scr_cutscene_variable,variable.normal,o_eleanor,"direction",270],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_wendy,"direction",270],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_wendy,["Desculpem, podem continuar"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Tá..."]],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//					[scr_cutscene_wait,.5],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Eu queria dizer que eu te amo, Hellen"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Que esse sentimento que você expressou nessa carta, é reciproco"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Fritz!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Frtiz!... Isso... É tão lindo!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu... Eu quero que você fique com esse livro, se possível..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Logo logo é o seu aniversário e não sei qual será a próxima vez que iremos nos ver depois desse dia"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Uma confissão e uma despedida?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Desculpe... Eu apenas tomei coragem hoje..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Antes tarde do que nunca, minha querida Hellen"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Oh, Fritz!... Eu te amo tanto"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["E te amo igualmente, Hellen"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_fritz,["Sou o ser mais sortudo por te ter em minha vida"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Somos sortudos por termos um ao outro"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",45],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",90],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Todd! BunBun! Muito obrigada pela ajuda"]],
				//					[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				//					[scr_cutscene_variable,variable.normal,o_fritz,"direction",0],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Que evento tão lindo! Isso é tão romântico!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Gente, que final feliz!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_eleanor,["Hellen, minha dupla, eu vi ela crescendo!! A vida é tão rápida!~"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Eu acho que não vou suportar! Meu coração, eu to quase chorando"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Ai gente! Que iti malia!"]],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O que é \"ti Malia\"?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sei lá, acabei de criar essa palavra também!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Que criativa você está hoje!"]],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá parecendo a Hellen! Criando palavras do nada"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["A mãe aqui pode tudo, chefe!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee!!"]],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",270],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E ai? Vai falar com ela?"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Quem? Eu?!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["E quem mais seria?"]],
				//					[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_blush_1],[s_todd_casual_blush_3],false,true,[.25,.2]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee! Eu vou contigo, bobo!!"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_blush_4],[s_todd_casual_idle_1_left],false,true,[.25,.2]],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
				//					[scr_cutscene_instance_create,382,404,"Instances_People_1",o_uncle_dmitriy],
				//					[scr_cutscene_move_character,o_uncle_dmitriy,303,404,false,1,true,true],
				//					[scr_cutscene_variable,variable.normal,o_uncle_dmitriy,"direction",270],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Uh... O que está acontecendo?"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_variable,variable.normal,o_wendy,"direction",225],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",315],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_wendy,"direction",180],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_eleanor,"direction",225],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",135],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_wendy,"direction",135],
				//					[scr_cutscene_variable,variable.normal,o_todd,"direction",90],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",45],
				//					[scr_cutscene_variable,variable.normal,o_eleanor,"direction",180],
				//					[scr_cutscene_variable,variable.normal,o_rubbert,"direction",135],
				//					[scr_cutscene_variable,variable.normal,o_nina,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",180],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_eleanor,"direction",135],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",90],
				//					[scr_cutscene_variable,variable.normal,o_rubbert,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_nina,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",315],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",135],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_rubbert,"direction",45],
				//					[scr_cutscene_variable,variable.normal,o_nina,"direction",45],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",0],
				//					[scr_cutscene_variable,variable.normal,o_clara,"direction",90],
				//					[scr_cutscene_wait,.1],
				//					[scr_cutscene_variable,variable.normal,o_amanda,"direction",45],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Foi lindo, tio!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nina,["Sim, tio! Foi tão romântico!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_eleanor,["Foi babilônico!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Teve drama, teve romance, teve tudo! Uma novela inteira!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Eu vou chorar, foi tão lindo!"]],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",135],
				//					[scr_cutscene_variable,variable.normal,o_rubbert,"direction",45],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["E não me critica por isso, Nickolai!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Não vou, por que eu vou chorar também!!"]],
				//					[scr_cutscene_variable,variable.normal,o_nickolai,"direction",90],
				//					[scr_cutscene_variable,variable.normal,o_rubbert,"direction",45],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Foi fofo, eu achei lindissimo!!"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Eu deveria ter terminado aquele mestrado...."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["AHEM!... Bom! Acho melhor vocês se recomporem"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Pois a aula já vai começar"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_rubbert,["Mesmo no nosso estado emocional?!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Não importa quando e onde, é sempre bom aprender"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Aprendizagem nessa ecônomia... Que coisa..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["O Tio Big B vai contar sobre a história do mundo, para vocês"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Sério?!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Diz que é verdade!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_nickolai,["Não brinca!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["Se eu pedir eu acho que ele canta..."]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_uncle_dmitriy,["AHEM! Sim! Ele vai cantar"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Yay!! Vamos!!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_amanda,["Já estamos baixando!"]],
				//					[scr_cutscene_talk,cutscene_talk_mode.normal,o_clara,["Vamos vamos!!"]],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
				//					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_can_play",false],
				//					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//					[scr_cutscene_audio_play,audio_type.bgm,bgm_008,true,0,1],
				//					[scr_cutscene_wait,1],
				//					[scr_cutscene_audio_stop,audio_type.bgm,bgm_008],
				//					[scr_cutscene_variable,variable.normal,o_camera,"x",592],
				//					[scr_cutscene_variable,variable.normal,o_camera,"y",555],
				//					[scr_cutscene_wait,2],
				//					[scr_cutscene_video,story_tell.world_1,sq_world_story],
				//					[scr_cutscene_remove_party_member,o_hellen],
				//					[scr_cutscene_bars,true,false]
				//				]
				//			],
				//			[scr_cutscene_wait,1],
				//			[scr_cutscene_bars,true,false],
				//		],
				//	],
				//1170,396],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"complete_cutscene",
				//	[
				//		[scr_cutscene_bars,true,true],
				//		[scr_cutscene_wait,1],
				//		[scr_cutscene_move_character,o_bunbun,1194,426,false,1,true,true],
				//		[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				//		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				//		[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",false],
				//		[scr_cutscene_move_character,o_bunbun,1194,421,false,1,true,true],
				//		[scr_cutscene_move_character,o_todd,1165,418,false,1,true,true],
				//		[scr_cutscene_variable,variable.normal,o_todd,"direction",45],
				//		[scr_cutscene_move_character,o_hellen,1223,418,false,1,true,true],
				//		[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				//		[scr_cutscene_wait,1],
				//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Ora... Precisam de algo mais?"],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Não, apenas viemos dar um oi!"]],
				//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Olá, 45!"]],
				//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oi, 45!"]],
				//		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E ai, 45?"]],
				//		[scr_cutscene_wait,1],
				//		[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idletalk_1],
				//		[scr_cutscene_wait,1],
				//		[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_noah,["Ah... Bom... Olá..."],-1,[[-1],[s_noah_casual_chill_idletalk_1],[s_noah_casual_chill_idletalk_1]],false,false,[0,.2,.25]],
				//		[scr_cutscene_wait,1],
				//		[scr_cutscene_variable,variable.normal,o_noah,"sprite_index",s_noah_casual_chill_idle_0],
				//		[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				//		[scr_cutscene_variable,variable.normal,o_hellen,"ppl_flowing",true],
				//		[scr_cutscene_wait,1],
				//		[scr_cutscene_bars,true,false],
				//	],
				//1170,396],
				//[scr_cutscene_variable,variable.nearst,o_cutscene_trigger_3,"quest_array",
				//	[
				//		[0,quest_type.have_item,item.love_letter],
				//		[-1,quest_type.talk_to,o_noah],
				//		[-1,quest_type.talk_to,o_hellen],
				//		[-1,quest_type.have_item,item.noah_gift],
				//	],
				//1170,396],
				[scr_cutscene_wait,1],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,591,505],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,591,505,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,591,505],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_move_character,o_bunbun,-16,0,true,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_move_character,o_todd,16,0,true,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_spices_intro],[s_todd_casual_spices_idle],false,true,[.35,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Ah mano!! Você ouviu!! Ela vai fazer espagueti com molho branco!!"],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Soufflé de cenoura!!..."],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["E suco de abacaxi com hortelã!!..."],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas eu pensei que você nem gostava de soufflé de cenoura..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Sendo dela, eu gosto!"],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum... Eu ainda prefiro as comidas do Tio Big B..."]],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_spices_outro],[s_todd_casual_idle_1_down],false,true,[.35,.2]],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, o Tio Big B só serve para contar histórias"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele é quem cuida da horta no quintal e do jardim dele... Que é da onde vem os temperos..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele, ele só serve para contar histórias e para isso"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele também é o primeiro a levantar para cuidar dos bebês"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E isso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Tio Big B também é responsável pela manutenção pesada de algumas coisas da casa... Lembra quando o gerador quebrou no ano passado?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá... E isso também..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Eu esqueci daquela vez que-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu já entendi, BunBun!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee, desculpe... Mas sim, as histórias do Tio Big B são boas!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tanto as dele quanto as do Fritz!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Sim!! Qual será a história que ele vai contar hoje a noite?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["A última foi legal mas eu não entendi muito..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Fritz tem dessas, ele gosta de histórias não convencionais"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["BunBun, Todd"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Olá, Hellen! No que podemos ajudar?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oi, Hellen"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah, é que... Eu ouvi vocês falando sobre o Fritz..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim sim, ele é incrivel"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Inteligente e sempre criativo, me dá um pouco de medo pelo modo de agir"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mas ainda assim o admiro muito"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh-Hum!! Ele sempre conhece uma história! E nsempre são boas histórias!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Oh, então vocês são bastente amigos dele?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu diria que mais o BunBun do que eu"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh? Como assim?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim, você sempre está perguntando para as pessoas como elas estão, se precisam de ajuda e tudo mais"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não me surpreenderia se ele te considerasse você fosse mais amigo dele do que eu"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele fala comigo por que sou sua dupla, isso eu tenho certeza"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Se você diz..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Então você, conhece mais o Fritz, posso dizer?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Posso dizer que sim"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Que atiçador..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ati o que?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Interessante"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Valeu"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["BunBun, Todd, eu preciso da ajuda de vocês... É sobre o Fritz.."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Hum... Do que precisa?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["É um segredo, mas não é nada atroz"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["É o que?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["É segredo, mas não nada ruim"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Por que ela fica inventando palavra?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu não to inventando palavra... Atroz é uma palavra que existe!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu acho mais é que você e o BunBun tem um dialeto secreto"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Mas-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ok. Tudo bem-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom, ainda assim, podem me ajudar?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que a gente ganha?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que?! Eu sou gente, não vou trabalhar de graça"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A gente vai te ajudar, Hellen"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["HaaHaa! Muito obrigada!! De verdade!"]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom, podemos ir para meu quarto? Falar aqui é meio... Vergonhoso..."]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",45],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sem problemas, vamos nessa!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_new_party_member,o_hellen],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
		}
		break;
}
#endregion