#region dia 0
non_avaliable_cutscene=[
	[scr_cutscene_bars,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
	[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
	[scr_cutscene_wait,1],
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
	[scr_cutscene_room_goto,rm_corridors,true,false],
	[scr_cutscene_variable,variable.normal,o_bunbun,"x",591],
	[scr_cutscene_variable,variable.normal,o_bunbun,"y",487],
	[scr_cutscene_refresh_party_member,true],
	[scr_cutscene_variable,variable.normal,o_camera,"x",591],
	[scr_cutscene_variable,variable.normal,o_camera,"y",505],
	[scr_cutscene_wait,1],
	//[setting the camera x]
	//[setting the camera y]
	[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,591,505],
	[scr_cutscene_wait,1],
	[scr_cutscene_move_character,o_bunbun,591,505,false,1,true,true],
	[scr_cutscene_refresh_party_member,false],
	[scr_cutscene_wait,1],
	[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
	[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,591,505],
	[scr_cutscene_wait,1],
	[scr_cutscene_bars,true,false]
];
switch global.day{
	case 0:
		if(global.event[0][3]==progress.non_complete){
			quest_array=[
				[0,quest_type.talk_to,o_mommy_allegra],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_room_goto,rm_corridors,true,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",591],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",487],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",591],
				[scr_cutscene_variable,variable.normal,o_camera,"y",505],
				[scr_cutscene_set_children],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_darya,"image_xscale",-1],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,591,505],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,591,505,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,591,505],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
				[scr_cutscene_move_character,o_bunbun,0,100,true,1,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
				[scr_cutscene_set_event,[0,3,progress.complete],[0,4,progress.non_complete]],
				[scr_cutscene_room_goto,rm_corridors,false,false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"x",591],
				[scr_cutscene_variable,variable.normal,o_bunbun,"y",487],
				[scr_cutscene_refresh_party_member,true],
				[scr_cutscene_variable,variable.normal,o_camera,"x",591],
				[scr_cutscene_variable,variable.normal,o_camera,"y",505],
				[scr_cutscene_set_children],
				[scr_cutscene_wait,1],
				//[setting the camera x]
				//[setting the camera y]
				[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",true,591,505],
				[scr_cutscene_wait,1],
				[scr_cutscene_move_character,o_bunbun,591,505,false,1,true,true],
				[scr_cutscene_refresh_party_member,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.nearst,o_door_2,"open",false,591,505],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",false],
				[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
				[scr_cutscene_move_character,o_bunbun,-16,0,true,1,true,true],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_move_character,o_todd,16,0,true,1,true,true],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_spices_intro],[s_todd_casual_spices_idle],false,true,[.35,.2]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Ah mano!! Você ouviu!! Ela vai fazer espagueti com molho branco!!"],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Soufflé de cenoura!!..."],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["E suco de abacaxi com hortelã!!..."],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Mas eu pensei que você nem gostava de soufflé de cenoura..."]],
				[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Sendo dela, eu gosto!"],-1,[[0],[s_todd_casual_spices_idle],[s_todd_casual_spices_talk]],false,false,[0,.2,.25]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum... Eu ainda prefiro as comidas do Tio Big B..."]],
				[scr_cutscene_animation_sprite,o_todd,[s_todd_casual_spices_outro],[s_todd_casual_idle_1_down],false,true,[.35,.2]],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, o Tio Big B só serve para contar histórias"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele é quem cuida da horta no quintal e do jardim dele... Que é da onde vem os temperos..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele, ele só serve para contar histórias e para isso"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele também é o primeiro a levantar para cuidar dos bebês"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["E isso..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Tio Big B também é responsável pela manutenção pesada de algumas coisas da casa... Lembra quando o gerador quebrou no ano passado?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Tá... E isso também..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Eu esqueci daquela vez que-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu já entendi, BunBun!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee, desculpe... Mas sim, as histórias do Tio Big B são boas!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Tanto as dele quanto as do Fritz!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Sim!! Qual será a história que ele vai contar hoje a noite?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["A última foi legal mas eu não entendi muito..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["O Fritz tem dessas, ele gosta de histórias não convencionais"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["BunBun, Todd"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah! Olá, Hellen! No que podemos ajudar?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Oi, Hellen"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ah, é que... Eu ouvi vocês falando sobre o Fritz..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim sim, ele é incrivel"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Inteligente e sempre criativo, me dá um pouco de medo pelo modo de agir"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Mas ainda assim o admiro muito"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh-Hum!! Ele sempre conhece uma história! E nsempre são boas histórias!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Oh, então vocês são bastente amigos dele?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu diria que mais o BunBun do que eu"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh? Como assim?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sim, você sempre está perguntando para as pessoas como elas estão, se precisam de ajuda e tudo mais"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Não me surpreenderia se ele te considerasse você fosse mais amigo dele do que eu"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ele fala comigo por que sou sua dupla, isso eu tenho certeza"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Oh... Se você diz..."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Então você, conhece mais o Fritz, posso dizer?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Posso dizer que sim"]],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Que atiçador..."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ati o que?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Interessante"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah! Valeu"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_wait,.5],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",225],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",180],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_wait,.1],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",90],
				[scr_cutscene_wait,.5],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["BunBun, Todd, eu preciso da ajuda de vocês... É sobre o Fritz.."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Hum... Do que precisa?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["É um segredo, mas não é nada atroz"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["É o que?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["É segredo, mas não nada ruim"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Por que ela fica inventando palavra?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Eu não to inventando palavra... Atroz é uma palavra que existe!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Eu acho mais é que você e o BunBun tem um dialeto secreto"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Mas-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Ok. Tudo bem-"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom, ainda assim, podem me ajudar?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que a gente ganha?"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Todd!!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que?! Eu sou gente, não vou trabalhar de graça"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
				[scr_cutscene_variable,variable.normal,o_todd,"direction",270],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["A gente vai te ajudar, Hellen"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["HaaHaa! Muito obrigada!! De verdade!"]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",135],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_hellen,["Bom, podemos ir para meu quarto? Falar aqui é meio... Vergonhoso..."]],
				[scr_cutscene_variable,variable.normal,o_hellen,"direction",45],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Sem problemas, vamos nessa!"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
				[scr_cutscene_new_party_member,o_hellen],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
		}
		break;
}
#endregion