children_array=-1
i=0;
switch global.day{
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region
			children_array=[
				[false,405,376,"Instances_People_1",ppl_act.custom,o_calina,s_calina_casual_dinner_idle_1_1,.2],
				[false,463,376,"Instances_People_1",ppl_act.custom,o_nickolai,s_nickolai_casual_dinner_idle_1_1,.25],
				[false,741,466,"Instances_People_1",ppl_act.custom,o_eleanor,s_eleanor_casual_dinner_idle_1_1,.25],
				[false,405,558,"Instances_People_1",ppl_act.custom,o_petter,s_petter_casual_dinner_idle_1_1,.2],
				[false,434,558,"Instances_People_1",ppl_act.custom,o_edgar,s_edgar_casual_dinner_idle_1_1,.2],
				[false,654,558,"Instances_People_1",ppl_act.custom,o_wendy,s_wendy_casual_dinner_idle_1_1,.2],
				[false,683,558,"Instances_People_1",ppl_act.custom,o_tomas,s_tomas_casual_dinner_idle_1_1,.25],
				[false,742,558,"Instances_People_1",ppl_act.custom,o_clara,s_clara_casual_dinner_idle_1_1,.2],
				[false,405,329,"Instances_People_1",ppl_act.custom,o_danya,s_danya_casual_dinner_idle_1_1,.2],
				[false,434,329,"Instances_People_1",ppl_act.custom,o_darya,s_darya_casual_dinner_idle_1_1,.2],
				[false,465,329,"Instances_People_1",ppl_act.custom,o_fritz,s_fritz_casual_dinner_idle_1_1,.2],
				[false,492,329,"Instances_People_1",ppl_act.custom,o_grettel,s_grettel_casual_dinner_idle_1_1,.2],
				[false,742,510,"Instances_People_1",ppl_act.custom,o_amanda,s_amanda_casual_dinner_idle_1_1,.25],
				[false,655,511,"Instances_People_1",ppl_act.custom,o_jill,s_jill_casual_dinner_idle_1_1,.2],
				[false,683,511,"Instances_People_1",ppl_act.custom,o_nina,s_nina_casual_dinner_idle_1_1,.2],
				[false,434,511,"Instances_People_1",ppl_act.custom,o_rubbert,s_rubbert_casual_dinner_idle_1_1,.2],
				[false,654,420,"Instances_People_1",ppl_act.custom,o_james,s_james_casual_dinner_idle_1_1,.2],
				[false,683,420,"Instances_People_1",ppl_act.custom,o_linus,s_linus_casual_dinner_idle_1_1,.25],
				[false,712,420,"Instances_People_1",ppl_act.custom,o_iriya,s_iriya_casual_dinner_idle_1_1,.2],
				[false,741,420,"Instances_People_1",ppl_act.custom,o_hellen,s_hellen_casual_dinner_idle_1_1,.2],
				[false,434,420,"Instances_People_1",ppl_act.custom,o_jeyjey,s_jeyjey_casual_dinner_idle_1_1,.2],
				[false,405,420,"Instances_People_1",ppl_act.custom,o_larry,s_larry_casual_dinner_talk_1_1,.25],
				[false,709,364,"Instances_People_1",ppl_act.custom,o_uncle_dmitriy,s_uncle_dmitriy_casual_dinner_idle_0,.2],
				[false,852,316,"Instances_People_1",ppl_act.custom,o_uncle_bruce,s_uncle_bruce_casual_dinner_idle_1,.2]
			];
			#endregion
		}else if(global.event[0][1]==progress.non_complete){
			children_array=[
				[false,522,1532,"Instances_People_1",ppl_act.custom,o_calina,s_calina_casual_playground_idle_1_1,.2],
				[false,1786,1672,"Instances_People_1",ppl_act.custom,o_eleanor,s_eleanor_casual_playground_idle_1_1,.25],
				[false,2102,1351,"Instances_People_1",ppl_act.custom,o_petter,s_petter_casual_playground_idle_1_1,.2],
				[false,326,1677,"Instances_People_1",ppl_act.custom,o_edgar,s_edgar_casual_playground_idle_1_1,.2],
				[false,955,1737,"Instances_People_1",ppl_act.custom,o_wendy,s_wendy_casual_playground_idle_1_1,.2],
				[false,578,1762,"Instances_People_1",ppl_act.custom,o_tomas,s_tomas_casual_playground_idle_1_1,.25],
				[false,1226,1692,"Instances_People_1",ppl_act.custom,o_clara,s_clara_casual_playground_idle_1_1,.2],
				[false,1790,1431,"Instances_People_1",ppl_act.custom,o_danya,s_danya_casual_playground_idle_1_1,.2],
				[false,1813,1431,"Instances_People_1",ppl_act.custom,o_darya,s_darya_casual_playground_idle_1_1,.2],
				[false,291,1851,"Instances_People_1",ppl_act.custom,o_fritz,s_fritz_casual_playground_talk_1_1,.2],
				[false,297,1584,"Instances_People_1",ppl_act.custom,o_grettel,s_grettel_casual_playground_idle_1_1,.2],
				[false,1482,1783,"Instances_People_1",ppl_act.npc,o_amanda,90,.25],
				[false,2077,1341,"Instances_People_1",ppl_act.custom,o_jill,s_jill_casual_playground_idle_1_1,.2],
				[false,870,1766,"Instances_People_1",ppl_act.custom,o_nina,s_nina_casual_playground_idle_1_1,.2],
				[false,1128,1665,"Instances_People_1",ppl_act.custom,o_rubbert,s_rubbert_casual_playground_idle_1_1,.2],
				[false,992,1683,"Instances_People_1",ppl_act.custom,o_james,s_james_casual_playground_idle_1_1,.2],
				[false,1013,1676,"Instances_People_1",ppl_act.custom,o_linus,s_linus_casual_playground_talk_1_1,.25],
				[false,1503,1550,"Instances_People_1",ppl_act.custom,o_iriya,s_iriya_casual_playground_idle_1_1,.2],
				[false,1757,1670,"Instances_People_1",ppl_act.custom,o_hellen,s_hellen_casual_playground_idle_1_1,.2],
				[false,1688,1491,"Instances_People_1",ppl_act.custom,o_jeyjey,s_jeyjey_casual_playground_idle_1_1,.2],
				[false,1197,1681,"Instances_People_1",ppl_act.custom,o_larry,s_larry_casual_playground_idle_1_1,.25],
				[false,1105,1668,"Instances_People_1",ppl_act.custom,o_uncle_bruce,s_uncle_bruce_casual_playground_idle_1_1,.2],
				[false,2102,1351,"Instances_People_1",ppl_act.npc,o_todd,270,.2],
				[false,2102,1351,"Instances_People_1",ppl_act.npc,o_nickolai,270,.2],
			];
		}else if(global.event[0][4]==progress.non_complete){
			if(room==rm_cafeteria){
				#region
				children_array=[
					[false,405,376,"Instances_People_1",ppl_act.custom,o_calina,s_calina_casual_dinner_idle_1_1,.2],
					[false,463,376,"Instances_People_1",ppl_act.custom,o_nickolai,s_nickolai_casual_dinner_idle_1_1,.25],
					[false,741,466,"Instances_People_1",ppl_act.custom,o_eleanor,s_eleanor_casual_dinner_idle_1_1,.25],
					[false,405,558,"Instances_People_1",ppl_act.custom,o_petter,s_petter_casual_dinner_idle_1_1,.2],
					[false,434,558,"Instances_People_1",ppl_act.custom,o_edgar,s_edgar_casual_dinner_idle_1_1,.2],
					[false,654,558,"Instances_People_1",ppl_act.custom,o_wendy,s_wendy_casual_dinner_idle_1_1,.2],
					[false,683,558,"Instances_People_1",ppl_act.custom,o_tomas,s_tomas_casual_dinner_idle_1_1,.25],
					[false,742,558,"Instances_People_1",ppl_act.custom,o_clara,s_clara_casual_dinner_idle_1_1,.2],
					[false,405,329,"Instances_People_1",ppl_act.custom,o_danya,s_danya_casual_dinner_idle_1_1,.2],
					[false,434,329,"Instances_People_1",ppl_act.custom,o_darya,s_darya_casual_dinner_idle_1_1,.2],
					[false,465,329,"Instances_People_1",ppl_act.custom,o_fritz,s_fritz_casual_dinner_idle_1_1,.2],
					[false,492,329,"Instances_People_1",ppl_act.custom,o_grettel,s_grettel_casual_dinner_idle_1_1,.2],
					[false,742,510,"Instances_People_1",ppl_act.custom,o_amanda,s_amanda_casual_dinner_idle_1_1,.25],
					[false,655,511,"Instances_People_1",ppl_act.custom,o_jill,s_jill_casual_dinner_idle_1_1,.2],
					[false,683,511,"Instances_People_1",ppl_act.custom,o_nina,s_nina_casual_dinner_idle_1_1,.2],
					[false,434,511,"Instances_People_1",ppl_act.custom,o_rubbert,s_rubbert_casual_dinner_idle_1_1,.2],
					[false,654,420,"Instances_People_1",ppl_act.custom,o_james,s_james_casual_dinner_idle_1_1,.2],
					[false,683,420,"Instances_People_1",ppl_act.custom,o_linus,s_linus_casual_dinner_idle_1_1,.25],
					[false,712,420,"Instances_People_1",ppl_act.custom,o_iriya,s_iriya_casual_dinner_idle_1_1,.2],
					[false,741,420,"Instances_People_1",ppl_act.custom,o_hellen,s_hellen_casual_dinner_idle_1_1,.2],
					[false,434,420,"Instances_People_1",ppl_act.custom,o_jeyjey,s_jeyjey_casual_dinner_idle_1_1,.2],
					[false,405,420,"Instances_People_1",ppl_act.custom,o_larry,s_larry_casual_dinner_talk_1_1,.25],
					[false,709,364,"Instances_People_1",ppl_act.custom,o_uncle_dmitriy,s_uncle_dmitriy_casual_dinner_idle_0,.2],
					[false,852,316,"Instances_People_1",ppl_act.custom,o_uncle_bruce,s_uncle_bruce_casual_dinner_idle_1,.2]
				];
				#endregion
			}else{
				#region
				children_array=[
					[false,288,619,"Instances_People_1",ppl_act.custom,o_fritz,s_fritz_casual_loveletter_idle_1,.2],
					[false,591,567,"Instances_People_1",ppl_act.npc,o_hellen,270,.25],
					[false,1194,386,"Instances_People_1",ppl_act.custom,o_noah,s_noah_casual_chill_idle_0,.25],
					//[false,405,558,"Instances_People_1",ppl_act.custom,o_petter,s_petter_casual_dinner_idle_1_1,.2],
				];
				#endregion
			}
		}else if(global.event[0][6]==progress.non_complete){
			children_array=[
				[false,884,568,"Instances_People_1",ppl_act.custom,o_calina,s_calina_casual_crayon_idle_1,.2],
			]
		}else if(global.event[0][7]==progress.non_complete){
			#region
			if(room==rm_cafeteria){
				children_array=[
					[false,405,376,"Instances_People_1",ppl_act.custom,o_calina,s_calina_casual_dinner_idle_1_1,.2],
					[false,463,376,"Instances_People_1",ppl_act.custom,o_nickolai,s_nickolai_casual_dinner_idle_1_1,.25],
					[false,741,466,"Instances_People_1",ppl_act.custom,o_eleanor,s_eleanor_casual_dinner_idle_1_1,.25],
					[false,405,558,"Instances_People_1",ppl_act.custom,o_petter,s_petter_casual_dinner_idle_1_1,.2],
					[false,434,558,"Instances_People_1",ppl_act.custom,o_edgar,s_edgar_casual_dinner_idle_1_1,.2],
					[false,654,558,"Instances_People_1",ppl_act.custom,o_wendy,s_wendy_casual_dinner_idle_1_1,.2],
					[false,683,558,"Instances_People_1",ppl_act.custom,o_tomas,s_tomas_casual_dinner_idle_1_1,.25],
					[false,742,558,"Instances_People_1",ppl_act.custom,o_clara,s_clara_casual_dinner_idle_1_1,.2],
					[false,405,329,"Instances_People_1",ppl_act.custom,o_danya,s_danya_casual_dinner_idle_1_1,.2],
					[false,434,329,"Instances_People_1",ppl_act.custom,o_darya,s_darya_casual_dinner_idle_1_1,.2],
					[false,465,329,"Instances_People_1",ppl_act.custom,o_fritz,s_fritz_casual_dinner_idle_1_1,.2],
					[false,492,329,"Instances_People_1",ppl_act.custom,o_grettel,s_grettel_casual_dinner_idle_1_1,.2],
					[false,742,510,"Instances_People_1",ppl_act.custom,o_amanda,s_amanda_casual_dinner_idle_1_1,.25],
					[false,655,511,"Instances_People_1",ppl_act.custom,o_jill,s_jill_casual_dinner_idle_1_1,.2],
					[false,683,511,"Instances_People_1",ppl_act.custom,o_nina,s_nina_casual_dinner_idle_1_1,.2],
					[false,434,511,"Instances_People_1",ppl_act.custom,o_rubbert,s_rubbert_casual_dinner_idle_1_1,.2],
					[false,654,420,"Instances_People_1",ppl_act.custom,o_james,s_james_casual_dinner_idle_1_1,.2],
					[false,683,420,"Instances_People_1",ppl_act.custom,o_linus,s_linus_casual_dinner_idle_1_1,.25],
					[false,712,420,"Instances_People_1",ppl_act.custom,o_iriya,s_iriya_casual_dinner_idle_1_1,.2],
					[false,741,420,"Instances_People_1",ppl_act.custom,o_hellen,s_hellen_casual_dinner_idle_1_1,.2],
					[false,434,420,"Instances_People_1",ppl_act.custom,o_jeyjey,s_jeyjey_casual_dinner_idle_1_1,.2],
					[false,405,420,"Instances_People_1",ppl_act.custom,o_larry,s_larry_casual_dinner_talk_1_1,.25],
					[false,709,364,"Instances_People_1",ppl_act.custom,o_uncle_dmitriy,s_uncle_dmitriy_casual_dinner_idle_0,.2],
					[false,852,316,"Instances_People_1",ppl_act.custom,o_uncle_bruce,s_uncle_bruce_casual_dinner_idle_1,.2]
				];
			}
			#endregion
		}
		break;
}