if(global.event[0][9]==progress.non_complete){
	quest_array=[
		[0,quest_type.talk_to,o_todd],
	];
	non_complete_cutscene[0]=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["......."]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Me pergunto se o Todd vai querer ir comigo..."]],
		[scr_cutscene_choice,[["Acordar Todd"],["Deixa-lo dormir"]],
			[
				[
					[scr_cutscene_wait,2],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele não vai achar ruim... Né?..."]],
					[scr_cutscene_wait,1],
					[scr_cutscene_move_character,o_bunbun,618,393,false,1,true,true],
					[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
					[scr_cutscene_wait,1],
					[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_pijama_todd_bedtalk_getting_up],[s_bunbun_pijama_todd_bedtalk_idle_1],false,true,[.25,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
					[scr_cutscene_move_character,o_camera,0,-100,true,1,false,false],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá acordado, Todd?.."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Melão..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_sleeping],[s_todd_pijama_todd_bedtalk_sleeping]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Melão..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
					[scr_cutscene_wait,1],
					[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_waking_up],[s_todd_pijama_todd_bedtalk_waking_up_idle],false,true,[.2,.2]],
					[scr_cutscene_wait,1],
					[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_getting_up],[s_todd_pijama_todd_bedtalk_idle_1],false,true,[.3,.2]],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá acordado, Todd?.."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["E o que tu acha?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Desculpe..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["É que eu queria te pedir uma coisa..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Você teve um pesadelo?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah... Não não... É que..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tem algo na minha cabeça que não consigo deixar de pensar..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["É que... Eu quero..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Queria pedir se você pode descer comigo..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu quero ver o que tem no porão..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Que?!... Você sabe que a gente não pode descer lá!..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_4],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu sei que não... Só que não consigo tirar isso da mente..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,2],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Por favor, não me olha assim!..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_3],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Se a gente descer lá..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Você vai sussegar o faxo e me deixar dormir?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim sim!! Prometo!!"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_4],[s_bunbun_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_2],
					[scr_cutscene_wait,1],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Apenas saiba que estou arrependido já..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
					[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["confia em mim"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_4],[s_bunbun_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
					[scr_cutscene_wait,1],
					[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
					[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
					[scr_cutscene_new_party_member,o_todd],
					[scr_cutscene_refresh_party_member,true],
					[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
					[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
					[scr_cutscene_wait,1],
					[scr_cutscene_circle_wake_up,true,false,663,394-48,true,true,false,make_color_rgb(36,34,52)],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
				],
				[
					[scr_cutscene_wait,2],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum..."]],
					[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não me importo, vou ver o que tem lá embaixo"]],
					[scr_cutscene_wait,1],
					[scr_cutscene_bars,true,false],
				]
			]
		]
	];
	complete_cutscene=[
		[scr_cutscene_bars,true,true],
		[scr_cutscene_wait,1],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bateu preguiça agora?"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Não"]],
		[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Apenas vamos lá de uma vez"]],
		[scr_cutscene_wait,1],
		[scr_cutscene_bars,true,false],
	]
}