switch global.day{
	#region dia 0
	case 0:
		if(global.event[0][0]==progress.non_complete){
			#region trocar de roupa
		quest_array=[
			[0,quest_type.switch_clothes,clothes.casual],
			[-1,quest_type.have_item,item.jeyjey_colar],
		];
		non_complete_cutscene[0]=[
			[scr_cutscene_bars,true,true],
			[scr_cutscene_wait,1],
			//[scr_cutscene_variable,variable.normal,o_cutscene,"cutscene_circle_radius",global.cw],
			[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,true,-1,make_color_rgb(36,34,52)],
			[scr_cutscene_variable,variable.normal,o_bunbun,"clothe",clothes.casual],
			[scr_cutscene_variable,variable.normal,o_bunbun,"x",565],
			[scr_cutscene_variable,variable.normal,o_bunbun,"y",386],
			[scr_cutscene_variable,variable.normal,o_todd,"y",394],
			[scr_cutscene_wait,1],
			[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],//[scr_cutscene_transition,cutscene_transition_type.bars,true,false,-1,make_color_rgb(36,34,52)],
			[scr_cutscene_wait,1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",270],
			[scr_cutscene_wait,.5],
			[scr_cutscene_move_character,o_bunbun,565,394,false,1,true,true],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
			[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
			[scr_cutscene_wait,.5],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Prontinho!","¡Listo!","I'm Ready!"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Boa, BunBun!","¡Genial, BunBun!","Nice, BunBun!"],-1],
			[scr_cutscene_move_character,o_bunbun,584,394,false,1,true,true],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos lá tomar café!","¡Vamos desayunar!","Let's go have the breakfast!"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_jeyjey,["Ah... Não não!...","Ay... ¡No, no!...","Ah... No, no!"],-1],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
			[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
			[scr_cutscene_move_character,o_bunbun,16,16,true,.5,true,false],
			[scr_cutscene_move_character,o_todd,8,0,true,.5,true,false],
			[scr_cutscene_move_character,o_camera,548,385,false,1,false,false],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"direction",90],
			[scr_cutscene_animation_sprite,o_jeyjey,[s_jeyjey_casual_searching_intro_closing],[s_jeyjey_casual_idletalk_1_up],false,true,[.3,.2]],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"ppl_act_state",ppl_act.npc],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"direction",45],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"direction",0],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"direction",315],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"direction",270],
			[scr_cutscene_wait,.5],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Não estou achando em lugar algum!!","¡¡No lo encuentro en lugar ninguno!!","I can't find it anywhere!!"],-1,[[s_jeyjey_casual_panic_searching_intro],[s_jeyjey_casual_panic_searching_idle],[s_jeyjey_casual_panic_searching_talk]],true,false,[.3,.3,.35]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Oh, JeyJey... Calma lá, cara!","Oh, JeyJey... ¡Tenga calma, tío!","Oh, JeyJey... Calm down, bro"],-1,[-1,[s_larry_casual_waiting_intro_idle_1],[s_larry_casual_waiting_intro_talk_1]],false,false,[0,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Nós vamos encontrar esse colar, ok?","Nosotros vamos encontrar este collar, ¿vale?","We gonna find this necklace, ok?"],-1,[-1,[s_larry_casual_waiting_intro_idle_2],[s_larry_casual_waiting_intro_talk_2]],false,false,[0,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Mas mas mas!","¡Pero pero pero!","But but but!"],-1,[-1,[s_jeyjey_casual_panic_searching_idle],[s_jeyjey_casual_panic_searching_talk]],false,false,[0,.3,.35]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["JeyJey, se liga!","¡Mira, JeyJey!","JeyJey, look!"],-1,[-1,[s_larry_casual_waiting_intro_idle_1],[s_larry_casual_waiting_intro_talk_1]],false,false,[0,.2,.25]],
			[scr_cutscene_animation_sprite,o_larry,[s_larry_casual_waiting_intro_getting_up],[s_larry_casual_idle_1_downleft],false,true,[.35,.2]],
			[scr_cutscene_variable,variable.normal,o_larry,"ppl_act_state",ppl_act.npc],
			[scr_cutscene_move_character,o_larry,569,386,false,.5,true,true],
			[scr_cutscene_animation_sprite,o_jeyjey,[s_jeyjey_casual_panic_searching_outro],[s_jeyjey_casual_idle_1_down],false,true,[.35,.2]],
			[scr_cutscene_wait,.5],
			[scr_cutscene_animation_sprite,o_larry,[s_larry_casual_conforting_jeyjey_idle],[s_larry_casual_conforting_jeyjey_idle],false,true,[1,1]],
			[scr_cutscene_animation_sprite,o_jeyjey,[s_nothing],[s_nothing],false,true,[1,1]],
			[scr_cutscene_variable,variable.normal,o_larry,"image_speed",.35],
			[scr_cutscene_animation_sprite,o_larry,[s_larry_casual_conforting_jeyjey_intro],[s_larry_casual_conforting_jeyjey_idle_4],false,true,[.35,.3]],
			[scr_cutscene_animation_sprite,o_jeyjey,[s_jeyjey_casual_conforting_jeyjey_idle_1],[s_jeyjey_casual_conforting_jeyjey_idle_1],false,true,[1,1]],
			[scr_cutscene_animation_sprite,o_larry,[s_larry_casual_conforting_jeyjey_idle_1],[s_larry_casual_conforting_jeyjey_idle_1],false,true,[.3,.3]],
			[scr_cutscene_wait,1],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Relaxa, cachorrão, na volta do café, iremos achar isso!!","¡¡Relajate, cachorro, lo encontraremos cuando volvamos del desayuno!!","Don't worry, puppy, we'll find it when we get back from the breakfast!!"],-1,[[-1],[s_larry_casual_conforting_jeyjey_idle_1],[s_larry_casual_conforting_jeyjey_talk_1]],false,false,[0,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Só quando estivermos de barriga cheia, iremos achar seu colar, ok?","Solo cuando tengamos la barriga llena, es que vamos encontrar su collar, ¿vale?","Only when our bellies are full will we find your necklace, alright?"],-1,[[-1],[s_larry_casual_conforting_jeyjey_idle_2],[s_larry_casual_conforting_jeyjey_talk_2]],false,false,[0,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Oh... Ok... Eu acho...","Oh... Bueno... Por supuesto...","Oh... Well... Ok..."],-1,[-1,[s_jeyjey_casual_conforting_jeyjey_idle_2],[s_jeyjey_casual_conforting_jeyjey_talk_2]],false,false,[0,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Apenas quero achar isso...","Solo lo quiero ecnotrar...","I just want to find it..."],-1,[-1,[s_jeyjey_casual_conforting_jeyjey_idle_1],[s_jeyjey_casual_conforting_jeyjey_talk_1]],false,false,[0,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Sei que quer achar! E é por isso que vamos tomar café para acalmar a barriga e a mente e então pensaremos melhor, ok?!!","¡¡Lo sé que lo quieres encontrar, y es por eso que vamos desayunar para acalmar la barriga y la miente, y solo entonces vamos pensar mejor!! ¡¿Vale?!","I know you want to find out! And that's why we're going to eat, to calm our bellies and minds and then we'll think better, okay?!!"],-1,[[s_larry_casual_conforting_jeyjey_thumb_up],[s_larry_casual_conforting_jeyjey_idle_3],[s_larry_casual_conforting_jeyjey_talk_3]],true,false,[.35,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_jeyjey,["Ok... Pode me soltar, por favor?","Vale... ¿Puedes soltarme, porfa?...","Ok... Can you let me go, please?"],-1,[-1,[s_jeyjey_casual_conforting_jeyjey_idle_1],[s_jeyjey_casual_conforting_jeyjey_talk_1]],false,false,[0,.2,.25]],
			[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_larry,["Belê!","¡Vale!","Fine!"],-1,[[-1],[s_larry_casual_conforting_jeyjey_idle_3],[s_larry_casual_conforting_jeyjey_talk_3]],false,false,[0,.2,.25]],
			[scr_cutscene_wait,.5],
			[scr_cutscene_animation_sprite,o_larry,[s_larry_casual_conforting_jeyjey_down],[s_larry_casual_conforting_jeyjey_idle],false,true,[.35,.3]],
			[scr_cutscene_variable,variable.normal,o_larry,"direction",225],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"direction",270],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"ppl_act_state",ppl_act.npc],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"ppl_anm_state",ppl_anm.idle],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"ppl_talk",false],
			[scr_cutscene_variable,variable.normal,o_larry,"ppl_act_state",ppl_act.npc],
			[scr_cutscene_wait,.5],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_larry,["Boa, cachorrão! Agora sem mais chorar, ok ok?!","¡Genial, cachorro. Ahora sin más llorar! ¡¿Vale?!","Nice, puppy! Now no cry no more, ok ok?!"],-1],
			[scr_cutscene_wait,.5],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_jeyjey,["Tá tá... Só fala baixo...","Vale vale... Solo no grites...","Fine fine... Just speak quietly"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_larry,["BOA, VAMOS!! ","¡¡GENIAL, VENGA!!","GOOD, LET'S GO!!"],-1],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"ppl_to_look_at",o_larry],
			[scr_cutscene_variable,variable.normal,o_jeyjey,"ppl_looking_to",true],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_larry],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_larry],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
			[scr_cutscene_wait,1],
			[scr_cutscene_move_character,o_larry,571,442,false,1,true,true],
			[scr_cutscene_move_character,o_larry,571,442+64,false,1,true,true],
			[scr_cutscene_instance_destroy,o_larry],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",225],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",180],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_todd,"direction",180],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",135],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_todd,"direction",135],
			[scr_cutscene_wait,.5],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_jeyjey,["Vamos...","Vamos...","Let's go..."],-1],
			[scr_cutscene_wait,1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_jeyjey],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_jeyjey],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
			[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_jeyjey],
			[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
			[scr_cutscene_move_character,o_jeyjey,571,442,false,1,true,true],
			[scr_cutscene_move_character,o_jeyjey,571,442+64,false,1,true,true],
			[scr_cutscene_instance_destroy,o_jeyjey],
			[scr_cutscene_wait,1],
			[scr_cutscene_move_character,o_camera,600,410,false,1,false,false],
			[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
			[scr_cutscene_variable,variable.normal,o_camera,"npc_to_flow",o_bunbun],
			[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
			[scr_cutscene_wait,1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ok então...","Vale, entonces...","Ok, so..."],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Coitado do JeyJey...","JeyJey, pobrecito...","Poor JeyJey..."],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Acho que o Larry tem razão, ele só vai achar quando estiver de barriga cheia","Creo que Larry tiene razón, él solo lo vas encontrar cuando tener la barriga llena","I think Larry is right, like, they'll only find it when bellies are full"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Com o estômago vazio, não pensamos em nada","Con el estómago vacío, no pensamos en nada","With an empty stomach, we don't think about anything"],-1],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",315],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",0],
			[scr_cutscene_wait,.1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",45],
			[scr_cutscene_wait,.5],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["HeeHee, você também é outro que só pensa em comigo!","¡JeeJee, Y tu también solo piensas en comida!","HeeHee, and you only think about food, too!"],-1],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_todd,"direction",225],
			[scr_cutscene_wait,.5],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Ah, BunBun, deixa disso! Também sou gente!!","¡Oh, por Dios, BunBun! ¡¡También soy gente!!","Oh, BunBun, C'mon! I'm a person too!!"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Pançudinho!","¡Panzón!","Muffin!"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["HaaHaa! O pançudinho aqui está com fome, vamos logo comer!","¡JaaJaa, el pazón aqui tiene hambre, vamos comer de una vez!","HaaHaa! The Muffin here's hungry, let's eat already!"],-1],
			[scr_cutscene_wait,1],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.flow],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
			[scr_cutscene_wait,1],
			[scr_cutscene_bars,true,false],
		];
		non_complete_cutscene[1]=[
			[scr_cutscene_bars,true,true],
			[scr_cutscene_wait,1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Onde está?...","¿Donde está?...","Where is it?..."],-1],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_bunbun],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Espera, foi você quem escondeu?!","¡¿Espera, fuiste tu quien lo escondió?!","Wait, did you hid it?!"],-1],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_todd],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Uh?! Não não! Estou encontrando para ele... Ontém eu vi ele colocando por aqui...","¡¿Uh?!  ¡No no! Es que estoy buscando para él... Ayer lo he visto él metiendo eso por aqui....","Uh?! No no! I'm just trying to find it to him... Yesterday i saw him putting right here..."],-1],
			[scr_cutscene_wait,.5],
			[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
			[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
			[scr_cutscene_wait,1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Encontrei!!","¡¡Lo encontré!!","I find it!!"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Boa, BunBun!!","¡¡Genial, BunBun!!","Nice, BunBun!!"],-1],
			[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
			[scr_cutscene_item,o_bunbun,-1,[item.jeyjey_colar,1],true,false],
			[scr_cutscene_wait,1],
			[scr_cutscene_bars,true,false],
		];
		complete_cutscene=[
			[scr_cutscene_bars,true,true],
			[scr_cutscene_wait,1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Vamos tomar café, BunBun!","¡Venga, el Desayuno, BunBun!","Let's go to the breakfast, BunBun!"],-1],
			[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah, desculpe","Ah, perdón...","Oh, sorry..."]],
			[scr_cutscene_wait,1],
			[scr_cutscene_bars,true,false],
		]
		break;
		#endregion
		}else if(global.event[0][8]==progress.non_complete){
			#region
			quest_array=[
				[0,quest_type.have_item,item.pijamas],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hummm...."]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_to_look_at",o_todd],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",true],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_to_look_at",o_bunbun],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",true],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Aqui o seu pijama!"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Valeu"]],
				[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_todd,"ppl_looking_to",false],
				[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
				[scr_cutscene_wait,1],
				[scr_cutscene_item,o_bunbun,-1,[item.pijamas,1],true,false],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false]
			];
			complete_cutscene=[]
			#endregion
		}
	#endregion
}
