if(global.event[0][9]==progress.non_complete){
		if(!o_ending_control.basement_find[0][0]){
		#region
			quest_array=[
				[0,quest_type.someone_party,o_todd],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["......."]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Me pergunto se o Todd vai querer ir comigo..."]],
				[scr_cutscene_choice,[["Acordar Todd"],["Deixa-lo dormir"]],
					[
						[
							[scr_cutscene_wait,2],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ele não vai achar ruim... Né?..."]],
							[scr_cutscene_wait,1],
							[scr_cutscene_move_character,o_bunbun,618,393,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_pijama_todd_bedtalk_getting_up],[s_bunbun_pijama_todd_bedtalk_idle_1],false,true,[.25,.2]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_move_character,o_camera,0,-100,true,1,false,false],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá acordado, Todd?.."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Melão..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_sleeping],[s_todd_pijama_todd_bedtalk_sleeping]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Melão..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_waking_up],[s_todd_pijama_todd_bedtalk_waking_up_idle],false,true,[.2,.2]],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_getting_up],[s_todd_pijama_todd_bedtalk_idle_1],false,true,[.3,.2]],
							[scr_cutscene_wait,2],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá acordado, Todd?.."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["E o que tu acha?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Desculpe..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_3],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["É que eu queria te pedir uma coisa..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Você teve um pesadelo?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah... Não não... É que..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tem algo na minha cabeça que não consigo deixar de pensar..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["É que... Eu quero..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Queria pedir se você pode descer comigo..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu quero ver o que tem no porão..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Que?!... Você sabe que a gente não pode descer lá!..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_4],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu sei que não... Só que não consigo tirar isso da mente..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,2],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Por favor, não me olha assim!..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_3],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Se a gente descer lá..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Você vai sussegar o faxo e me deixar dormir?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim sim!! Prometo!!"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_4],[s_bunbun_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_2],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Apenas saiba que estou arrependido já..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["confia em mim"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_4],[s_bunbun_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
							[scr_cutscene_variable,variable.normal,o_bunbun,"ppl_act_state",ppl_act.play],
							[scr_cutscene_new_party_member,o_todd],
							[scr_cutscene_refresh_party_member,true],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_flowing",true],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",true],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,false,663,394-48,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,1],
							[scr_cutscene_bars,true,false],
						],
						[
							[scr_cutscene_wait,2],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Hum..."]],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Não me importo, vou ver o que tem lá embaixo"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_bars,true,false],
						]
					]
				]
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["O que?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_todd,["Bateu preguiça agora?"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Ah... Não"]],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["Apenas vamos lá de uma vez"]],
				[scr_cutscene_wait,1],
				[scr_cutscene_bars,true,false],
			];
			#endregion
		}else{
			#region
			quest_array=[
				[0,quest_type.end_condition,o_todd],
			];
			non_complete_cutscene[0]=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["......."]],
				[scr_cutscene_choice,[["Acordar Todd"],["Deixa-lo dormir"]],
					[
						[
							[scr_cutscene_wait,2],
							[scr_cutscene_move_character,o_bunbun,618,393,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_pijama_todd_bedtalk_getting_up],[s_bunbun_pijama_todd_bedtalk_idle_1],false,true,[.25,.2]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_move_character,o_camera,0,-100,true,1,false,false],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá acordado, Todd?.."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_waking_up],[s_todd_pijama_todd_bedtalk_waking_up_idle],false,true,[.2,.2]],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_getting_up],[s_todd_pijama_todd_bedtalk_idle_1],false,true,[.3,.2]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["BunBun?..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Tá tudo bem?..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sim... Apenas..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Apenas... Apenas tive um pesadelo..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_3],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Oh! Um pesadelo?..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Hum... Tudo bem..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Mas com o que você sonhou?..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_2],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sonhei que estava em um lugar escuro..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["E que algo queria me pegar..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Não se preocupa, BunBun"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Estou aqui e nada vai te pegar, ok?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Deita aí..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_2],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Desculpe por te incomodar tão tarde..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Você nunca vai me incomodar, BunBun"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Vem... Deita..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Até por que Está ficando frio"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_2],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá bom"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Bobo"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você quem é..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
							[scr_cutscene_new_party_member,o_todd],
							[scr_cutscene_wait,1],
							[scr_cutscene_room_goto,rm_house_ext_front,true,false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_nothing],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.custom],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_nothing],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"x",1152],
							[scr_cutscene_variable,variable.normal,o_camera,"y",608],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,2],
							[scr_cutscene_move_character,o_camera,1152,288,false,1,false,false],
							[scr_cutscene_variable,variable.normal,o_graphic,"graphic_snow",true],
							[scr_cutscene_wait,10],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,c_black],
							[scr_cutscene_wait,1],
							[scr_cutscene_video,story_tell.credit],
						],
						[
							[scr_cutscene_wait,2],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["......"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_video,story_tell.credit],
						]
					]
				]
			];
			complete_cutscene=[
				[scr_cutscene_bars,true,true],
				[scr_cutscene_wait,1],
				[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["......."]],
				[scr_cutscene_choice,[["Acordar Todd"],["Deixa-lo dormir"]],
					[
						[
							[scr_cutscene_wait,2],
							[scr_cutscene_move_character,o_bunbun,618,393,false,1,true,true],
							[scr_cutscene_variable,variable.normal,o_bunbun,"direction",90],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_bunbun,[s_bunbun_pijama_todd_bedtalk_getting_up],[s_bunbun_pijama_todd_bedtalk_idle_1],false,true,[.25,.2]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_move_character,o_camera,0,-100,true,1,false,false],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá acordado, Todd?.."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Todd..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_waking_up],[s_todd_pijama_todd_bedtalk_waking_up_idle],false,true,[.2,.2]],
							[scr_cutscene_wait,1],
							[scr_cutscene_animation_sprite,o_todd,[s_todd_pijama_todd_bedtalk_getting_up],[s_todd_pijama_todd_bedtalk_idle_1],false,true,[.3,.2]],
							[scr_cutscene_wait,2],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_4],
							[scr_cutscene_wait,2],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Desculpe..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_3],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Duas vezes em uma noite? Acho bom ter um bom motivo..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Desculpe..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["É que..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu tive um pesadelo com o que a gente viu lá em baixo...."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Você diz de dentro daquela caixa?..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Não... Digo..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Da criatura..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu não tiro da cabeça as mãos dela saltando da porta..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Eu... Eu to com muito medo..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Que... Criatura?..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,2],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Da criatura... Que saiu... Daquela porta..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ela... Era cheia de braços e..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você estava lá, você viu ela!..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Não viu?..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_4],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Isso é algum tipo de pegadinha?"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você realmente não viu?"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Eu só vi que a porta estava emperrada"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Você começou a se desculpar, depois você ficou meio apreensivo e basicamente me ajudou a abrir a porta"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Eu não vi criatura nenhuma..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Sério?..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Sim, cara..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_2],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Oh..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Acho que foi só um pesadelo então..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Desculpe, Todd, vou deixar você dormir, ok?"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_4],[s_bunbun_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Deita logo..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Ah... Sim, desculpe... Eu já to indo para minha cama"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_1],[s_bunbun_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Não, te dou um espaço..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Eu vejo que você tá com medo..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Então só deita logo..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Até por que eu to com sono..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_2],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você está bravo comigo... Né?"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Um pouco..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Na real foi até divertido..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_3],[s_todd_pijama_todd_bedtalk_talk_3]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Mas não vem achando que é festa!"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_4],[s_todd_pijama_todd_bedtalk_talk_4]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_todd_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Vem... Deita..."],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Até por que Está ficando frio"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_1],[s_todd_pijama_todd_bedtalk_talk_1]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_bunbun_pijama_todd_bedtalk_idle_2],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Tá bom"],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_todd,["Bobo"],-1,[[-1],[s_todd_pijama_todd_bedtalk_idle_2],[s_todd_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_talk_animated,cutscene_talk_mode.normal,o_bunbun,["Você quem é..."],-1,[[-1],[s_bunbun_pijama_todd_bedtalk_idle_2],[s_bunbun_pijama_todd_bedtalk_talk_2]],false,false,[0,.2,.25]],
							[scr_cutscene_wait,1],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,make_color_rgb(36,34,52)],
							[scr_cutscene_new_party_member,o_todd],
							[scr_cutscene_wait,1],
							[scr_cutscene_room_goto,rm_house_ext_front,true,false],
							[scr_cutscene_variable,variable.normal,o_bunbun,"sprite_index",s_nothing],
							[scr_cutscene_variable,variable.normal,o_todd,"ppl_act_state",ppl_act.custom],
							[scr_cutscene_variable,variable.normal,o_todd,"sprite_index",s_nothing],
							[scr_cutscene_variable,variable.normal,o_camera,"flow_npc",false],
							[scr_cutscene_variable,variable.normal,o_camera,"x",1152],
							[scr_cutscene_variable,variable.normal,o_camera,"y",608],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,true,false,make_color_rgb(36,34,52)],
							[scr_cutscene_wait,2],
							[scr_cutscene_move_character,o_camera,1152,288,false,1,false,false],
							[scr_cutscene_variable,variable.normal,o_graphic,"graphic_snow",true],
							[scr_cutscene_wait,10],
							[scr_cutscene_circle_wake_up,true,true,-1,-1,true,false,false,c_black],
							[scr_cutscene_wait,1],
							[scr_cutscene_video,story_tell.credit],
						],
						[
							[scr_cutscene_wait,2],
							[scr_cutscene_talk,cutscene_talk_mode.normal,o_bunbun,["......"]],
							[scr_cutscene_wait,1],
							[scr_cutscene_video,story_tell.credit],
						]
					]
				]
			];
			#endregion
		}

}